### ISSUE TITLE
[0.27.0] bad CPU type in executable on OSX (Intel)

### ISSUE THREAD

**Issue by alycklama** [redhat-developer/vscode-xml#1001]
I'm trying to run LemMinX 0.27.0 on Sonoma 14.4.1 (2,4 GHz 8-Core Intel Core i9), but I get the following error:

`bad CPU type in executable`

Version 0.26.1 works as expected.

**Comment by angelozerr** [comment]
@rgrunber @datho7561 have you some idea?

**Comment by rgrunber** [comment]
I think I see the problem :
```
$ file ./new/extension/server/lemminx-osx-x86_64
./new/extension/server/lemminx-osx-x86_64: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

It wasn't "arm64" in 0.26.1 . That looks completely wrong. We should get to the bottom of it and produce a bug fix release.

**Comment by alycklama** [comment]
Thanks for the lightning fast replies, and awesome to see you already found something! I know it's far too early, but If I can test anything, just let me know 👍

**Comment by fbricon** [comment]
@rgrunber according to https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories, macos-latest runs on Mac M1s

**Comment by rgrunber** [comment]
@alycklama , this should be published as pre-release version `0.27.2024053103` . You can switch to pre-release from the VS Code extension view to try it.

**Comment by alycklama** [comment]
@rgrunber I can confirm the issue is gone with the pre-release. Thanks a lot for the quick fix everyone!

**Comment by angelozerr** [comment]
@alycklama glad the issue has been fixed.

@rgrunber thanks so much!
