### ISSUE TITLE
AVX2

### ISSUE THREAD

**Issue by michaelcarno** [redhat-developer/vscode-xml#1008]
![image](https://github.com/redhat-developer/vscode-xml/assets/19550611/5f83e6ca-8aac-449e-be9a-ba284058423a)

Hi! Got this. We using old servers cpu's. Looks like i dont have AVX2 and probably some other instruction, so how can i rebuild executable without avx2?

**Comment by fbricon** [comment]
Can you try using the [java version](https://github.com/redhat-developer/vscode-xml?tab=readme-ov-file#requirements) first? 

If you _really_ need to recompile the binary, maybe try [rebuilding lemminx](https://github.com/eclipse/lemminx/tree/main?tab=readme-ov-file#generating-a-native-binary) with the [-march=compatibility](https://www.graalvm.org/latest/reference-manual/native-image/overview/Options/) flag in https://github.com/eclipse/lemminx/blob/main/org.eclipse.lemminx/pom.xml#L169

Then you can configure the [`xml.server.binary.path`](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#server-binary-mode) in your vscode settings, pointing at your new binary.

**Comment by michaelcarno** [comment]
Thanks you and sorry, everything was in readme.
