### ISSUE TITLE
Extra space in new line after click ENTER at the end of a comment

### ISSUE THREAD

**Issue by gengyj16** [redhat-developer/vscode-xml#1019]
![image](https://github.com/user-attachments/assets/0fd9920f-fa2b-4213-b075-a40d2a47583d)
click ENTER at the end of a comment that contains space result in extra space in new line

**Comment by angelozerr** [comment]
Could you record a demo with the problem please, I don't understdand very well your issue?

**Comment by gengyj16** [comment]
https://github.com/user-attachments/assets/d976fdf6-61b2-422b-832b-0f651da18a00


Demo screen record here. Note the extra space in line 4, which is unexpected.

https://github.com/user-attachments/assets/eb420c77-a15c-4385-9a9a-156a2f2eb828

After disable this extension, this problem is gone. I'm not sure if it is directly related to the extension. Any other details I should provide?
