### ISSUE TITLE
Content of completionItem detail is not well-rendered

### ISSUE THREAD

**Issue by Eskibear** [redhat-developer/vscode-xml#102]
See below;
![image](https://user-images.githubusercontent.com/2351748/51666216-54689000-1ff8-11e9-96f3-19cfd9b721e6.png)

#### Current
```
xxx<code>&lt;name&gt;value&lt;/name&gt;</code>yyy
```

#### Expected

xxx`<name>value</name>`yyy

**Comment by fbricon** [comment]
Closing as duplicate of #32
