### ISSUE TITLE
Windows terminal keeps popping up

### ISSUE THREAD

**Issue by careri** [redhat-developer/vscode-xml#1025]
Hi, 

You can ignore this issue, it seems like my Windows installation for some reason has started to show the terminal window for all executing processes. It's not just the extension.

~~I've been running v0.27.1 for a while.~~
~~Today all of a sudden the Xml extension has started to open a terminal that just flashes by. Quite annoying since it steels keyboard focus.~~

~~The extension keeps launching some processes:~~
~~c:\Users\secer\.vscode\extensions\redhat.vscode-xml-0.27.1-win32-x64\server\lemminx-win32.exe ""~~
~~"C:\WINDOWS\system32\cmd.exe" /c "tasklist /FI PID" eq "31164 | findstr 31164" ~~

~~I guess this should be executed in the background, but for some reason the terminal window is visible now.~~
~~If I disable the extension the terminal stops popping up.~~

~~More info~~
~~![image](https://github.com/user-attachments/assets/7b5cb426-b1f2-4829-95f0-cf44ed29852e)~~
~~![image](https://github.com/user-attachments/assets/fa0472c2-7eb3-4c47-b1cf-f1cb55f378d6)~~

~~Reverting to v0.26.1 doesn't solve the problem. Very strange, maybe it's not related to the extension after all?~~

**Comment by Scal-Human** [comment]
Let us know if you find any reason to do this. It simply smells.
Uninstall planned and done.

**Comment by fbricon** [comment]
Not necessarily. We still have over 10% of users on Java 8,  so it'd be good to keep that support. We could do Reflection or use Multi-Release jars, but it would complicate the build. See https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html#multi-release
