### ISSUE TITLE
No xml support when opening files on shared folders

### ISSUE THREAD

**Issue by lgiammattei** [redhat-developer/vscode-xml#1033]
Hellò, 
Version: 1.95.1 (user setup)
Commit: 65edc4939843c90c34d61f4ce11704f09d3e5cb6
Date: 2024-10-31T05:14:54.222Z
Electron: 32.2.1
ElectronBuildId: 10427718
Chromium: 128.0.6613.186
Node.js: 20.18.0
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.19045

XML 0.27.1 installed

When I open an xml file and go for formatting i receive the message "no xml formatter found" and i am ask to install one that is already installed.

In activating the extension in the output i read:
[info] ExtensionService#_doActivateExtension redhat.vscode-xml, startup: false, activationEvent: 'onLanguage:xml'
[warning] [redhat.vscode-xml] Accessing a resource scoped configuration without providing a resource is not expected. To get the effective value for '[xml]', provide the URI of a resource or 'null' for any resource.

**Comment by angelozerr** [comment]
Can you [enable verbose logging](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Troubleshooting.md#no-support-on-xml-file) and paste your logs from the `XML Support` output view?

You can also try setting `"xml.server.preferBinary": true` in your settings.json

**Comment by lgiammattei** [comment]
Here is he output of the XML Support output view:

[Trace - 2:53:29 PM] Sending request 'initialize - (0)'.
Params: {
    "processId": 10460,
    "clientInfo": {
        "name": "Visual Studio Code",
        "version": "1.95.1"
    },
    "locale": "en-us",
    "rootPath": null,
    "rootUri": null,
    "capabilities": {
        "workspace": {
            "applyEdit": true,
            "workspaceEdit": {
                "documentChanges": true,
                "resourceOperations": [
                    "create",
                    "rename",
                    "delete"
                ],
                "failureHandling": "textOnlyTransactional",
                "normalizesLineEndings": true,
                "changeAnnotationSupport": {
                    "groupsOnLabel": true
                }
            },
            "configuration": true,
            "didChangeWatchedFiles": {
                "dynamicRegistration": true,
                "relativePatternSupport": true
            },
            "symbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "resolveSupport": {
                    "properties": [
                        "location.range"
                    ]
                }
            },
            "codeLens": {
                "refreshSupport": true
            },
            "executeCommand": {
                "dynamicRegistration": true
            },
            "didChangeConfiguration": {
                "dynamicRegistration": true
            },
            "workspaceFolders": true,
            "semanticTokens": {
                "refreshSupport": true
            },
            "fileOperations": {
                "dynamicRegistration": true,
                "didCreate": true,
                "didRename": true,
                "didDelete": true,
                "willCreate": true,
                "willRename": true,
                "willDelete": true
            },
            "inlineValue": {
                "refreshSupport": true
            },
            "inlayHint": {
                "refreshSupport": true
            },
            "diagnostics": {
                "refreshSupport": true
            }
        },
        "textDocument": {
            "publishDiagnostics": {
                "relatedInformation": true,
                "versionSupport": false,
                "tagSupport": {
                    "valueSet": [
                        1,
                        2
                    ]
                },
                "codeDescriptionSupport": true,
                "dataSupport": true
            },
            "synchronization": {
                "dynamicRegistration": true,
                "willSave": true,
                "willSaveWaitUntil": true,
                "didSave": true
            },
            "completion": {
                "dynamicRegistration": true,
                "contextSupport": true,
                "completionItem": {
                    "snippetSupport": true,
                    "commitCharactersSupport": true,
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "deprecatedSupport": true,
                    "preselectSupport": true,
                    "tagSupport": {
                        "valueSet": [
                            1
                        ]
                    },
                    "insertReplaceSupport": true,
                    "resolveSupport": {
                        "properties": [
                            "documentation",
                            "detail",
                            "additionalTextEdits"
                        ]
                    },
                    "insertTextModeSupport": {
                        "valueSet": [
                            1,
                            2
                        ]
                    },
                    "labelDetailsSupport": true
                },
                "insertTextMode": 2,
                "completionItemKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25
                    ]
                },
                "completionList": {
                    "itemDefaults": [
                        "commitCharacters",
                        "editRange",
                        "insertTextFormat",
                        "insertTextMode"
                    ]
                }
            },
            "hover": {
                "dynamicRegistration": true,
                "contentFormat": [
                    "markdown",
                    "plaintext"
                ]
            },
            "signatureHelp": {
                "dynamicRegistration": true,
                "signatureInformation": {
                    "documentationFormat": [
                        "markdown",
                        "plaintext"
                    ],
                    "parameterInformation": {
                        "labelOffsetSupport": true
                    },
                    "activeParameterSupport": true
                },
                "contextSupport": true
            },
            "definition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "references": {
                "dynamicRegistration": true
            },
            "documentHighlight": {
                "dynamicRegistration": true
            },
            "documentSymbol": {
                "dynamicRegistration": true,
                "symbolKind": {
                    "valueSet": [
                        1,
                        2,
                        3,
                        4,
                        5,
                        6,
                        7,
                        8,
                        9,
                        10,
                        11,
                        12,
                        13,
                        14,
                        15,
                        16,
                        17,
                        18,
                        19,
                        20,
                        21,
                        22,
                        23,
                        24,
                        25,
                        26
                    ]
                },
                "hierarchicalDocumentSymbolSupport": true,
                "tagSupport": {
                    "valueSet": [
                        1
                    ]
                },
                "labelSupport": true
            },
            "codeAction": {
                "dynamicRegistration": true,
                "isPreferredSupport": true,
                "disabledSupport": true,
                "dataSupport": true,
                "resolveSupport": {
                    "properties": [
                        "edit"
                    ]
                },
                "codeActionLiteralSupport": {
                    "codeActionKind": {
                        "valueSet": [
                            "",
                            "quickfix",
                            "refactor",
                            "refactor.extract",
                            "refactor.inline",
                            "refactor.rewrite",
                            "source",
                            "source.organizeImports"
                        ]
                    }
                },
                "honorsChangeAnnotations": false
            },
            "codeLens": {
                "dynamicRegistration": true
            },
            "formatting": {
                "dynamicRegistration": true
            },
            "rangeFormatting": {
                "dynamicRegistration": true
            },
            "onTypeFormatting": {
                "dynamicRegistration": true
            },
            "rename": {
                "dynamicRegistration": true,
                "prepareSupport": true,
                "prepareSupportDefaultBehavior": 1,
                "honorsChangeAnnotations": true
            },
            "documentLink": {
                "dynamicRegistration": true,
                "tooltipSupport": true
            },
            "typeDefinition": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "implementation": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "colorProvider": {
                "dynamicRegistration": true
            },
            "foldingRange": {
                "dynamicRegistration": true,
                "rangeLimit": 5000,
                "lineFoldingOnly": true,
                "foldingRangeKind": {
                    "valueSet": [
                        "comment",
                        "imports",
                        "region"
                    ]
                },
                "foldingRange": {
                    "collapsedText": false
                }
            },
            "declaration": {
                "dynamicRegistration": true,
                "linkSupport": true
            },
            "selectionRange": {
                "dynamicRegistration": true
            },
            "callHierarchy": {
                "dynamicRegistration": true
            },
            "semanticTokens": {
                "dynamicRegistration": true,
                "tokenTypes": [
                    "namespace",
                    "type",
                    "class",
                    "enum",
                    "interface",
                    "struct",
                    "typeParameter",
                    "parameter",
                    "variable",
                    "property",
                    "enumMember",
                    "event",
                    "function",
                    "method",
                    "macro",
                    "keyword",
                    "modifier",
                    "comment",
                    "string",
                    "number",
                    "regexp",
                    "operator",
                    "decorator"
                ],
                "tokenModifiers": [
                    "declaration",
                    "definition",
                    "readonly",
                    "static",
                    "deprecated",
                    "abstract",
                    "async",
                    "modification",
                    "documentation",
                    "defaultLibrary"
                ],
                "formats": [
                    "relative"
                ],
                "requests": {
                    "range": true,
                    "full": {
                        "delta": true
                    }
                },
                "multilineTokenSupport": false,
                "overlappingTokenSupport": false,
                "serverCancelSupport": true,
                "augmentsSyntaxTokens": true
            },
            "linkedEditingRange": {
                "dynamicRegistration": true
            },
            "typeHierarchy": {
                "dynamicRegistration": true
            },
            "inlineValue": {
                "dynamicRegistration": true
            },
            "inlayHint": {
                "dynamicRegistration": true,
                "resolveSupport": {
                    "properties": [
                        "tooltip",
                        "textEdits",
                        "label.tooltip",
                        "label.location",
                        "label.command"
                    ]
                }
            },
            "diagnostic": {
                "dynamicRegistration": true,
                "relatedDocumentSupport": false
            }
        },
        "window": {
            "showMessage": {
                "messageActionItem": {
                    "additionalPropertiesSupport": true
                }
            },
            "showDocument": {
                "support": true
            },
            "workDoneProgress": true
        },
        "general": {
            "staleRequestSupport": {
                "cancel": true,
                "retryOnContentModified": [
                    "textDocument/semanticTokens/full",
                    "textDocument/semanticTokens/range",
                    "textDocument/semanticTokens/full/delta"
                ]
            },
            "regularExpressions": {
                "engine": "ECMAScript",
                "version": "ES2020"
            },
            "markdown": {
                "parser": "marked",
                "version": "1.1.0"
            },
            "positionEncodings": [
                "utf-16"
            ]
        },
        "notebookDocument": {
            "synchronization": {
                "dynamicRegistration": true,
                "executionSummarySupport": true
            }
        }
    },
    "initializationOptions": {
        "settings": {
            "xml": {
                "java": {
                    "home": "C:\\Program Files\\Semeru\\jre-21.0.2.13-openj9"
                },
                "server": {
                    "vmargs": "-Xmx64M",
                    "workDir": "~/.lemminx",
                    "preferBinary": false,
                    "silenceExtensionWarning": false,
                    "binary": {
                        "path": "",
                        "args": "",
                        "trustedHashes": []
                    }
                },
                "trace": {
                    "server": "verbose"
                },
                "logs": {
                    "client": true,
                    "file": "c:\\Users\\l.giammattei\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.vscode-xml\\lemminx.log"
                },
                "downloadExternalResources": {
                    "enabled": true
                },
                "catalogs": [],
                "fileAssociations": [],
                "foldings": {
                    "includeClosingTagInFold": false
                },
                "format": {
                    "enabled": true,
                    "emptyElements": "ignore",
                    "enforceQuoteStyle": "ignore",
                    "legacy": false,
                    "grammarAwareFormatting": true,
                    "joinCDATALines": false,
                    "joinCommentLines": false,
                    "joinContentLines": false,
                    "maxLineWidth": 100,
                    "preserveAttributeLineBreaks": true,
                    "preserveEmptyContent": false,
                    "preservedNewlines": 2,
                    "preserveSpace": [
                        "xsl:text",
                        "xsl:comment",
                        "xsl:processing-instruction",
                        "literallayout",
                        "programlisting",
                        "screen",
                        "synopsis",
                        "pre",
                        "xd:pre"
                    ],
                    "spaceBeforeEmptyCloseTag": true,
                    "xsiSchemaLocationSplit": "onPair",
                    "splitAttributes": "preserve",
                    "splitAttributesIndentSize": 2,
                    "closingBracketNewLine": false,
                    "trimFinalNewlines": false,
                    "trimTrailingWhitespace": false,
                    "insertFinalNewline": false
                },
                "completion": {
                    "autoCloseTags": true,
                    "autoCloseRemovesContent": true
                },
                "codeLens": {
                    "enabled": false
                },
                "preferences": {
                    "quoteStyle": "double",
                    "showSchemaDocumentationType": "all"
                },
                "validation": {
                    "enabled": true,
                    "namespaces": {
                        "enabled": "always"
                    },
                    "schema": {
                        "enabled": "always"
                    },
                    "disallowDocTypeDecl": false,
                    "resolveExternalEntities": false,
                    "xInclude": {
                        "enabled": false
                    },
                    "noGrammar": "hint",
                    "filters": [
                        {
                            "pattern": "**.exsd",
                            "noGrammar": "ignore",
                            "schema": {
                                "enabled": "never"
                            }
                        },
                        {
                            "pattern": "**{.project,.classpath,plugin.xml,feature.xml,category.xml,.target,.product}",
                            "noGrammar": "ignore"
                        }
                    ]
                },
                "symbols": {
                    "enabled": true,
                    "excluded": [],
                    "maxItemsComputed": 5000,
                    "showReferencedGrammars": true,
                    "filters": []
                },
                "references": [],
                "colors": [],
                "filePathSupport": {
                    "mappings": []
                },
                "extension": {
                    "jars": []
                },
                "useCache": true,
                "linkedEditingEnabled": false,
                "telemetry": {
                    "enabled": false
                }
            }
        },
        "extendedClientCapabilities": {
            "codeLens": {
                "codeLensKind": {
                    "valueSet": [
                        "references",
                        "association",
                        "open.uri"
                    ]
                }
            },
            "actionableNotificationSupport": true,
            "openSettingsCommandSupport": true,
            "bindingWizardSupport": true
        }
    },
    "trace": "verbose",
    "workspaceFolders": null
}


[Trace - 2:53:30 PM] Received notification 'window/logMessage'.
Params: {
    "type": 3,
    "message": "nov 04, 2024 02:53:30 org.eclipse.lemminx.XMLLanguageServer initialize()\r\nMessage: Initializing XML Language server\r\nLemMinX Server info:\r\n - Version : 0.28.0\r\n - Java : C:\\Program Files\\Semeru\\jre-21.0.2.13-openj9\r\n - VM Version : 21.0.2\r\n - Git 9c3a0f1 - [maven-release-plugin] prepare release 0.28.0"
}


[Info  - 2:53:30 PM] nov 04, 2024 02:53:30 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.28.0
 - Java : C:\Program Files\Semeru\jre-21.0.2.13-openj9
 - VM Version : 21.0.2
 - Git 9c3a0f1 - [maven-release-plugin] prepare release 0.28.0
[Trace - 2:53:30 PM] Received response 'initialize - (0)' in 1642ms.
Result: {
    "capabilities": {
        "textDocumentSync": 2,
        "hoverProvider": false,
        "definitionProvider": false,
        "typeDefinitionProvider": false,
        "referencesProvider": false,
        "documentHighlightProvider": false,
        "documentSymbolProvider": false,
        "documentFormattingProvider": false,
        "documentRangeFormattingProvider": false,
        "colorProvider": false,
        "foldingRangeProvider": false,
        "workspace": {
            "workspaceFolders": {
                "supported": true,
                "changeNotifications": true
            }
        },
        "selectionRangeProvider": false,
        "linkedEditingRangeProvider": false
    }
}


[Trace - 2:53:30 PM] Sending notification 'initialized'.
Params: {}


[Trace - 2:53:30 PM] Sending notification 'workspace/didChangeConfiguration'.
Params: {
    "settings": {
        "xml": {
            "java": {
                "home": "C:\\Program Files\\Semeru\\jre-21.0.2.13-openj9"
            },
            "server": {
                "vmargs": "-Xmx64M",
                "workDir": "~/.lemminx",
                "preferBinary": false,
                "silenceExtensionWarning": false,
                "binary": {
                    "path": "",
                    "args": "",
                    "trustedHashes": []
                }
            },
            "trace": {
                "server": "verbose"
            },
            "logs": {
                "client": true,
                "file": "c:\\Users\\l.giammattei\\AppData\\Roaming\\Code\\User\\globalStorage\\redhat.vscode-xml\\lemminx.log"
            },
            "downloadExternalResources": {
                "enabled": true
            },
            "catalogs": [],
            "fileAssociations": [],
            "foldings": {
                "includeClosingTagInFold": false
            },
            "format": {
                "enabled": true,
                "emptyElements": "ignore",
                "enforceQuoteStyle": "ignore",
                "legacy": false,
                "grammarAwareFormatting": true,
                "joinCDATALines": false,
                "joinCommentLines": false,
                "joinContentLines": false,
                "maxLineWidth": 100,
                "preserveAttributeLineBreaks": true,
                "preserveEmptyContent": false,
                "preservedNewlines": 2,
                "preserveSpace": [
                    "xsl:text",
                    "xsl:comment",
                    "xsl:processing-instruction",
                    "literallayout",
                    "programlisting",
                    "screen",
                    "synopsis",
                    "pre",
                    "xd:pre"
                ],
                "spaceBeforeEmptyCloseTag": true,
                "xsiSchemaLocationSplit": "onPair",
                "splitAttributes": "preserve",
                "splitAttributesIndentSize": 2,
                "closingBracketNewLine": false,
                "trimFinalNewlines": false,
                "trimTrailingWhitespace": false,
                "insertFinalNewline": false
            },
            "completion": {
                "autoCloseTags": true,
                "autoCloseRemovesContent": true
            },
            "codeLens": {
                "enabled": false
            },
            "preferences": {
                "quoteStyle": "double",
                "showSchemaDocumentationType": "all"
            },
            "validation": {
                "enabled": true,
                "namespaces": {
                    "enabled": "always"
                },
                "schema": {
                    "enabled": "always"
                },
                "disallowDocTypeDecl": false,
                "resolveExternalEntities": false,
                "xInclude": {
                    "enabled": false
                },
                "noGrammar": "hint",
                "filters": [
                    {
                        "pattern": "**.exsd",
                        "noGrammar": "ignore",
                        "schema": {
                            "enabled": "never"
                        }
                    },
                    {
                        "pattern": "**{.project,.classpath,plugin.xml,feature.xml,category.xml,.target,.product}",
                        "noGrammar": "ignore"
                    }
                ]
            },
            "symbols": {
                "enabled": true,
                "excluded": [],
                "maxItemsComputed": 5000,
                "showReferencedGrammars": true,
                "filters": []
            },
            "references": [],
            "colors": [],
            "filePathSupport": {
                "mappings": []
            },
            "extension": {
                "jars": []
            },
            "useCache": true,
            "linkedEditingEnabled": false,
            "telemetry": {
                "enabled": false
            }
        }
    }
}


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (1)'.
Params: {
    "registrations": [
        {
            "id": "eeba8d71-c69f-4c41-b1bf-fc3d5b81a8e9",
            "method": "textDocument/codeAction",
            "registerOptions": {
                "resolveProvider": true
            }
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (1)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (2)'.
Params: {
    "registrations": [
        {
            "id": "797fe0d3-d221-4bc3-a0ea-968607b0af2d",
            "method": "textDocument/completion",
            "registerOptions": {
                "resolveProvider": true,
                "triggerCharacters": [
                    ".",
                    ":",
                    "<",
                    "\"",
                    "=",
                    "/",
                    "\\",
                    "?",
                    "'",
                    "&",
                    "#"
                ]
            }
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (2)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (3)'.
Params: {
    "registrations": [
        {
            "id": "5e537948-451d-4fdc-9fbd-84b42313aba6",
            "method": "textDocument/documentHighlight"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (3)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (4)'.
Params: {
    "registrations": [
        {
            "id": "dd64c3f1-9c59-47e1-a5b3-bf161507f830",
            "method": "textDocument/foldingRange"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (4)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (5)'.
Params: {
    "registrations": [
        {
            "id": "890d937e-3b4a-49a7-ba18-52f2f9d08dd6",
            "method": "textDocument/hover"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (5)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (6)'.
Params: {
    "registrations": [
        {
            "id": "e6697801-b942-4edc-8516-601c61febcaa",
            "method": "textDocument/documentLink",
            "registerOptions": {
                "resolveProvider": true
            }
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (6)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (7)'.
Params: {
    "registrations": [
        {
            "id": "2d6eb54f-44c5-4c2b-9c60-3fbfe926849b",
            "method": "textDocument/documentColor",
            "registerOptions": {}
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (7)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (8)'.
Params: {
    "registrations": [
        {
            "id": "15fb010c-0e43-4e21-9c96-243643c2bd4c",
            "method": "textDocument/rename",
            "registerOptions": {
                "prepareProvider": true
            }
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (8)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (9)'.
Params: {
    "registrations": [
        {
            "id": "eede62fa-0f78-4182-b92c-1f50bce108c1",
            "method": "textDocument/definition"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (9)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (10)'.
Params: {
    "registrations": [
        {
            "id": "d9a20ae1-1320-4f85-b075-da2faab4e3d7",
            "method": "textDocument/typeDefinition"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (10)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (11)'.
Params: {
    "registrations": [
        {
            "id": "1683b37c-a975-42ba-b57f-f93bd51dd2ae",
            "method": "textDocument/references"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (11)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (12)'.
Params: {
    "registrations": [
        {
            "id": "da7930fe-f99c-484f-864e-3f4d10edfc23",
            "method": "textDocument/linkedEditingRange"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (12)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (13)'.
Params: {
    "registrations": [
        {
            "id": "0ca3de97-3dbf-4552-876c-8251c60d6e38",
            "method": "workspace/didChangeWatchedFiles",
            "registerOptions": {
                "watchers": [
                    {
                        "globPattern": "**/*.xsd"
                    },
                    {
                        "globPattern": "**/*.dtd"
                    },
                    {
                        "globPattern": "**/*.rng"
                    },
                    {
                        "globPattern": "**/*.rnc"
                    }
                ]
            }
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (13)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (14)'.
Params: {
    "registrations": [
        {
            "id": "876f41cb-e104-4642-991a-a2cb67ddca55",
            "method": "textDocument/formatting"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (14)'. Processing request took 1ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (15)'.
Params: {
    "registrations": [
        {
            "id": "cc77b22b-50b2-469a-9a59-fcaf4d4a9635",
            "method": "textDocument/rangeFormatting"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (15)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (16)'.
Params: {
    "registrations": [
        {
            "id": "2b6ca176-fd9b-4b81-95d7-9e8790eb060d",
            "method": "textDocument/selectionRange"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (16)'. Processing request took 0ms
No result returned.


[Trace - 2:53:30 PM] Received request 'client/registerCapability - (17)'.
Params: {
    "registrations": [
        {
            "id": "4247dff8-c2a0-45f9-9db3-51ed0aa77813",
            "method": "textDocument/documentSymbol"
        }
    ]
}


[Trace - 2:53:30 PM] Sending response 'client/registerCapability - (17)'. Processing request took 1ms
No result returned.

**Comment by lgiammattei** [comment]
> You can also try setting `"xml.server.preferBinary": true` in your settings.json

I also tried this one but the problem remains, here is the output from XML support

[output.json](https://github.com/user-attachments/files/17619168/output.json)

**Comment by angelozerr** [comment]
According your trace, you can use Java, so please remove xml.server.preferBinary": true because it seems your OS cannot support binary:

```
The current machine does not support all of the following CPU features that are required by the image: [CX8, CMOV, FXSR, MMX, SSE, SSE2, SSE3, SSSE3, SSE4_1, SSE4_2, POPCNT, LZCNT, AVX, AVX2, BMI1, BMI2, FMA].

Please rebuild the executable with an appropriate setting of the -march option.[Error - 2:57:11 PM] Connection to server got closed. Server will not be restarted.
[Error - 2:57:11 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:57:11 PM] XML Support client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 2:57:11 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

If you type an invalid XML syntax, do you see some error?

**Comment by lgiammattei** [comment]
I removed "xml.server.preferBinary": true" then I opened an already existing xml file and modified some closing tags I did not get any error

**Comment by angelozerr** [comment]
Close and reopen your vscode after this change settings  and share your trace with your broken XML file.

**Comment by lgiammattei** [comment]
Here is what i found, i am working on xml files stored in a shared folder on our lan, if I copy the file local on my PC then open it the format comand works well and does his job, if I open the file from the shared folder the format command does not work and give me back the error about xml formatter not installed.
Here is the output from the XML support for both shared and local file that happens to be the same file
[xml_file_local.json](https://github.com/user-attachments/files/17620185/xml_file_local.json)
[xml_file_shared.json](https://github.com/user-attachments/files/17620184/xml_file_shared.json)

**Comment by lgiammattei** [comment]
@angelozerr here is the output for xml shared file, i did it again now 
[xml_output_shared_file.json](https://github.com/user-attachments/files/17630122/xml_output_shared_file.json)

**Comment by lgiammattei** [comment]
@angelozerr here is the output for xml local file
[xml_output_local_file.json](https://github.com/user-attachments/files/17630199/xml_output_local_file.json)

**Comment by lgiammattei** [comment]
In the shared file output I don't see any reference to the opened file, but the file was opened in my editor 
![Image](https://github.com/user-attachments/assets/109f175c-68e0-4666-b300-7c05fd0a194f)

[xml_output_shared_file_2.json](https://github.com/user-attachments/files/17630330/xml_output_shared_file_2.json)

**Comment by lgiammattei** [comment]
TIA @angelozerr for your help

**Comment by angelozerr** [comment]
Indeed there is no trace of didOpen with your shared LSP trace.

> Here is what i found, i am working on xml files stored in a shared folder on our lan

@fbricon @rgrunber @datho7561 do you know if it is a limitation from vscode? or perhaps shared file uses a scheme different from file?

@lgiammattei you are using `*.cbi` file extension, but when I see file extensions at https://github.com/microsoft/vscode/blob/0d8b5d3f4fb3560348b9a77f1cd56f54f9ae95b8/extensions/xml/package.json#L16 I don't see this file extension. Have you customized that?

Could you try to rename file with*.xml instead of *.cbi in your share lan and check if it is working?

**Comment by angelozerr** [comment]
Ok thanks for your feedback. For the moment  I have no idea why shared file doesn't work.

If you see on the bottom right of your vscode and you open shared file, do you see XML as language?

**Comment by lgiammattei** [comment]
yes ![Image](https://github.com/user-attachments/assets/f8ff10aa-16f9-4562-be6f-838da462f005)

**Comment by lgiammattei** [comment]
Done and I have support for HTML like tag autocompletion with closing tag and indentation

**Comment by angelozerr** [comment]
Ok thanks.

Now could you enable HTML trace settings by adding in your settings.json `"html.trace.server": "verbose"` and share the LSP trace. I would like to see the didOpen uri used by LAN.

**Comment by lgiammattei** [comment]
you mean this?

[Trace - 3:05:55 PM] Sending notification 'textDocument/didOpen'.
Params: {
    "textDocument": {
        "uri": "streamfile:/CBI/BAD_MAIL/test.html?readonly%3Dfalse%26position%3D",
        "languageId": "html",
        "version": 1,
        "text": "<!DOCTYPE html>\r\n<html>\r\n<body>\r\n\r\n<h1>My First Heading</h1>\r\n\r\n<p>My first paragraph.</p>\r\n\r\n</body>\r\n</html>\r\n"
    }
}

**Comment by lgiammattei** [comment]
Btw here is the complete trace, I confirm that autocompletion with closing tag and indentation works well
[html_output_shared_file.json](https://github.com/user-attachments/files/17633878/html_output_shared_file.json)

**Comment by angelozerr** [comment]
Thanks so much!

I think the root case is about the scheme `streamline` 

`streamfile:/CBI/BAD_MAIL/test.html?readonly%3Dfalse%26position%3D`

Today vscode-xml uses file scheme. In vscode html they don't declare any sheme.

**Comment by lgiammattei** [comment]
Thanks to you @angelozerr 
Btw what is file scheme? You mean XSD?

**Comment by datho7561** [comment]
I can't find any information anywhere about the `streamfile:` scheme. (It's not on [Wikpedia](https://en.wikipedia.org/wiki/List_of_URI_schemes)). My understanding is that shared folders on Windows use the `file:` scheme. Something is up. I guess if VS Code provides the file contents, most language servers shouldn't need to directly access the content.

**Comment by angelozerr** [comment]
@datho7561 vscode html  doesn't declare file as scheme in their document selector. In our case we declare file and untitled as scheme. Perhaps we should remove them?

**Comment by angelozerr** [comment]
> Btw what is file scheme? You mean XSD?

No I mean schelme (file, untitled, http,  etc) from URI but not schema

**Comment by angelozerr** [comment]
> . I think this is why we restricted it to `file` and `untitled`.

Very good explanation!

Have you some idea how to fix this issue?

**Comment by datho7561** [comment]
> Have you some idea how to fix this issue?

If the scheme is not `file`, we should avoid trying to access the file or accessing files relative to the file.

**Comment by angelozerr** [comment]
> If the scheme is not file, we should avoid trying to access the file or accessing files relative to the file.

If I understand your comment:

 * remove sheme from vscode-xml
 * takes care of on LemMinx XML language server that scheme is file (or http) for XSD, DTD , RNG included in a XML file

right?

**Comment by angelozerr** [comment]
or perhaps a simple fix is to add streamfile in the document selector?

**Comment by fbricon** [comment]
no streamfile is not a standard scheme. Removing the scheme requirement will cover more ground.

**Comment by angelozerr** [comment]
OK we could start to remove scheme on vscode xml side and for lemminx side we could do that when we will find some issues.

@datho7561 @fbricon are you OK with that?

**Comment by datho7561** [comment]
Sure

**Comment by angelozerr** [comment]
@datho7561 please review https://github.com/redhat-developer/vscode-xml/pull/1034

**Comment by angelozerr** [comment]
@lgiammattei could you please install pre-release https://github.com/redhat-developer/vscode-xml?tab=readme-ov-file#contributing and give us feedback if it works for you.

Thanks.

**Comment by angelozerr** [comment]
> [@angelozerr](https://github.com/angelozerr) done and now it works like a charm

Great! Thanks for your feedback. Hope you will enjoy with vscode-xml.
