### ISSUE TITLE
Potential leak of handles and memory

### ISSUE THREAD

**Issue by tovine** [redhat-developer/vscode-xml#108]
It seems like something in the way you (or one of your dependencies) use java causes it to over time leak file handles, which in turn makes windows expand the virtual memory page table and eat all available RAM...

Please see these two comments on this issue for more details:
https://github.com/Microsoft/vscode/issues/50280#issuecomment-458678352
https://github.com/Microsoft/vscode/issues/50280#issuecomment-461024431

**Comment by angelozerr** [comment]
Please give us usecase to reproduce the problem. Thanks

**Comment by tovine** [comment]
0. Open Windows Task Manager and make sure the "Handles" column in the "Details" tab is visible (right-click the headings, click "Select columns" and find it in the list).
1. Open a XML file in VSCode
2. In Task Manager, find VSCode, expand it and find the java.exe (in my case "OpenJDK Platform binary")
3. Right click it and select "Go to details"
4. Sort the list by "Handles" and watch java.exe make its way up towards the top

The number of handles seems to be slowly and steadily increasing; in my case it seems to be about 2-3 handles every few seconds, but leave it overnight or for a few days and it is likely to reach the 100k's range...

**Comment by snjeza** [comment]
Related issue - https://github.com/redhat-developer/vscode-java/issues/789

**Comment by snjeza** [comment]
I can still reproduce the issue with JDK 11.
