### ISSUE TITLE
how to use the android layout xsd for completion?

### ISSUE THREAD

**Issue by fatfatson** [redhat-developer/vscode-xml#114]
I want to write the android layout xml file in vscode, with this plugin and the `xsd` file from [repo](https://github.com/atsushieno/xamarin-android-shema-generator/tree/master/generated),

but there are two xsd files, I don't how to config the association between them, could you please give a sample? (with element type and attribute completion)

if `systemId` set to the `android-layout.xsd`,  element could be completed but attribute doesn't;
 if using the `android-attribute.xsd`, none of them work.

**Comment by angelozerr** [comment]
@fatfatson could you attach please a zip with your test please.

**Comment by angelozerr** [comment]
None answer. I close this issue. @fatfatson if you wish reopen the issue please do that bu by attaching your zip sample (with XML file)
