### ISSUE TITLE
Bad folder created on Windows

### ISSUE THREAD

**Issue by apupier** [redhat-developer/vscode-xml#125]
I have a folder named "UsersAurelien Pupier" containing .lsp4xml folder which has been created at the root of my project.

![image](https://user-images.githubusercontent.com/1105127/55728949-7aa5a580-5a15-11e9-9c91-ec380cf540c9.png)

**Comment by NikolasKomonen** [comment]
@apupier Are you running the project as a Workspace, or have you just opened the project folder?

**Comment by apupier** [comment]
I have opened the project folder

**Comment by apupier** [comment]
in output -> XMl Support, there are this kind of message:

Message: Downloading http://camel.apache.org/schema/spring/camel-spring.xsd to C:UsersAurelien Pupier\.lsp4xml\cache\http\camel.apache.org\schema\spring\camel-spring.xsd...

**Comment by NikolasKomonen** [comment]
I think I've found the issue 

> C:UsersAurelien Pupier\

should be

> C:Users\Aurelien Pupier\

I think this is a Windows issue. I'll keep you up to date.

**Comment by apupier** [comment]
it should even be 

> C:\Users\Aurelien Pupier\

**Comment by fbricon** [comment]
@NikolasKomonen we should release a fix ASAP

**Comment by fbricon** [comment]
@apupier in the meantime, you can try setting the cache directory in your vscode user settings
```json
"xml.server.workDir": "C:\\Users\\Aurelien Pupier\\.lsp4xml"
```
See if it works.

**Comment by apupier** [comment]
> @apupier in the meantime, you can try setting the cache directory in your vscode user settings
> 
> ```json
> "xml.server.workDir": "C:\\Users\\Aurelien Pupier\\.lsp4xml"
> ```
> 
> See if it works.

workaround is working:

```
[Info  - 6:34:21 PM] Apr 08, 2019 06:34:21 org.eclipse.lsp4xml.uriresolver.CacheResourcesManager lambda$downloadResource$0()
Message: Downloaded http://camel.apache.org/schema/spring/camel-spring.xsd to C:\Users\Aurelien Pupier\.lsp4xml\cache\http\camel.apache.org\schema\spring\camel-spring.xsd in 530ms
```

**Comment by NikolasKomonen** [comment]
@apupier If you have time could you test out the fix

Here is an updated vsix.

http://s000.tinyupload.com/?file_id=67069650176669735126
