### ISSUE TITLE
Latest releases do not have `vsix` files

### ISSUE THREAD

**Issue by ibuziuk** [redhat-developer/vscode-xml#127]
A Github release should contain not only source code but also vsix file. 
Initial one has it - https://github.com/redhat-developer/vscode-xml/releases/tag/v0.1.0
Latest does not - https://github.com/redhat-developer/vscode-xml/releases/tag/0.5.1

**Comment by ibuziuk** [comment]
@fbricon @gorkem will it be possible to add vsix to releases in order to workaround che 7 GA VS Code marketplace rate limit error - eclipse/che#12840

**Comment by fbricon** [comment]
Binaries have been attached to all the releases: https://github.com/redhat-developer/vscode-xml/releases
