### ISSUE TITLE
Auto Rename Tag

### ISSUE THREAD

**Issue by bmix** [redhat-developer/vscode-xml#130]
I just realized, with the help of [@angelozerr](https://github.com/angelozerr) at [lsp4xml/#362](https://github.com/angelozerr/lsp4xml/issues/362), that synced renaming and deletion of two tags, that belong together, may best be done via some simple text manipulation on the client side. I now have installed a little extension into VSCode, that does just that (minus paired delete, sadly), but it may well fit also into your project, so to keep things together.

**Comment by fbricon** [comment]
@angelozerr @xorye @NikolasKomonen that feature is now available for HTML tags: https://github.com/microsoft/vscode/issues/47069. Would be nice to extend it to XML as well.

**Comment by angelozerr** [comment]
Thanks @fbricon for this great news! It seems we should support 

 * a custom request `MatchingTagPositionRequest` on LSP4XML (server side) 
 * that we should consume on vscode-xml (on client side).

 See commit at https://github.com/microsoft/vscode/commit/0d25d0a79823802d0c5df42db4d4d40b099c14d5

**Comment by octref** [comment]
@angelozerr The bugs you pointed are already fixed. To implement this feature for XML, you can support `MatchingTagPositionRequest` on the server and reference the implementation in our HTML server.

**Comment by angelozerr** [comment]
> The bugs you pointed are already fixed. 

Thanks for the information!

> To implement this feature for XML, you can support MatchingTagPositionRequest on the server and reference the implementation in our HTML server.

What do you mean with `reference the implementation in our HTML server` ?

@fbricon I think we should really implement this very cool feature.

**Comment by octref** [comment]
@angelozerr https://github.com/microsoft/vscode/blob/master/extensions/html-language-features/client/src/mirrorCursor.ts

There's nothing in LSP that correspond to adding a cursor. So if you want to implement this, the best you can do is to use VS Code's API like the html language client is currently doing.

Please note that `MatchingTagPositionRequest` is not an official name.

**Comment by angelozerr** [comment]
> Please note that `MatchingTagPositionRequest `is not an official name.

You mean that this request type could belong to the LSP specification ?

**Comment by octref** [comment]
I was saying the opposite: it’s NOT lsp, just a custom request now.

**Comment by angelozerr** [comment]
> I was saying the opposite: it’s NOT lsp, 

Yes sure I understood that, but I love this feature and I hope really this request type will be a LSP specification. In this case we could have this feature in any LSP client (my wish is to have this support inside Eclipse IDE with LSP4E /cc @mickaelistria)

**Comment by mickaelistria** [comment]
the Language Server already has ability to send TextEdit to the client to apply on client-side. So this can be an option, when turned on, that sending a text change inside a tag sends an applyEdit notification for the other tag in the client.
I don't think we need some extra thing to make it work on client side.

**Comment by fbricon** [comment]
Feature doesn't work (see #211 )

**Comment by octref** [comment]
I can't repro the problem in HTML though. Are you doing anything XML specific?

**Comment by xorye** [comment]
One feature that was specific to vscode-xml was that we added the ability to toggle the `xml.mirrorCursorOnMatchingTag` feature with Ctrl/Cmd + shift + f2.

A new listener was added to detect changes to `xml.mirrorCursorOnMatchingTag` and called the [`onDidChangeTextEditorSelection()`](https://github.com/microsoft/vscode/blob/eb0ca2626beba3de0d2e6c0220e2c55d34cefc61/extensions/html-language-features/client/src/mirrorCursor.ts#L52) function in order to update the cursor immediately on toggle.

I'm guessing that we had problems because we didn't have
```
if (event.textEditor.document?.languageId !== 'xml' ) {
     return;
}
```
in our `onDidChangeTextEditorSelection()` function.

**Comment by bmix** [comment]
There is also some discussion going on here: [VSCode: Improve mirror cursor implementation with Synced Regions #88424](https://github.com/microsoft/vscode/issues/88424)

**Comment by angelozerr** [comment]
Thanks @bmix for this great information!

**Comment by angelozerr** [comment]
@xorye we should manage synced region in LemMinx side and consume it. See HTML Language server commit https://github.com/microsoft/vscode/commit/01e01b13f88064374ebc5aa789cb0ee76d03a17c but I suggest you see for each files the master code (if there are some fixes)

**Comment by angelozerr** [comment]
Fixed with LSP Lineked Editing, see https://github.com/redhat-developer/vscode-xml/blob/master/docs/Features/XMLFeatures.md#linked-editing
