### ISSUE TITLE
Unknown Configuration setting

### ISSUE THREAD

**Issue by Stragis** [redhat-developer/vscode-xml#135]
![image](https://user-images.githubusercontent.com/834519/57738533-bfe87300-7664-11e9-8bc7-cc5702221bb3.png)

I get a message unknown config setting when I have java.home in my settings.json.

**Comment by NikolasKomonen** [comment]
Hi,

Right now we haven't explicitly defined it since the Java extension is the one that declares it. But from what I see in your picture it should work.

@fbricon any thoughts on this?

**Comment by fbricon** [comment]
There's nothing much to do here, once we have xml.java.home available (#145), we'll just need to adjust the documentation in the readme.

**Comment by fbricon** [comment]
Closing as `xml.java.home` is now the prefered preference (see #145). `java.home`, defined by vscode-java is still supported though.
