### ISSUE TITLE
Typing '/' inside attribute value deletes element's contents.

### ISSUE THREAD

**Issue by smilediver** [redhat-developer/vscode-xml#138]
Example XML:

```
        <animation id="show">
            <delay time="0.6"/>
        </animation>
```

Typing `/` character after `h` inside `"show"` deletes element's contents, and you get XML like this:

```
        <animation id="sh/>
```

Extension version: 0.5.1

**Comment by NikolasKomonen** [comment]
This issue is already fixed!
https://github.com/redhat-developer/vscode-xml/issues/126
It will be available in the next release.

**Comment by smilediver** [comment]
Nice! Thank you. :)

**Comment by fbricon** [comment]
@smilediver please try the latest vscode-xml visx file from http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D

See https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix for installation instructions.

**Comment by smilediver** [comment]
Tried `vscode-xml-0.6.0-3147.vsix | 21-May-2019 15:45 | 5.7M`, the issue seems fixed. 👍
