### ISSUE TITLE
unexpected indentation after empty element + attribute

### ISSUE THREAD

**Issue by itn3000** [redhat-developer/vscode-xml#159]
# Environment 

* win8.1 x64
* vscode: 1.35.1
* redhat.vscode-xml: 0.7.0

# Steps to reproduce

1. write empty body element and add attribute, like `<A B=""/>`
2. enter the end of element

# Expected result

same indentation to element like here(`_` is cursor)
```xml
<A B=""/>
_
```

# Actual result

one indentation is added like here(`_` is cursor)
```xml
<A B=""/>
    _
```

Additionally, without attribute, this is not reproduced, and formatting with `Shift`+`Alt`+f, indentation will be adjusted.

**Comment by angelozerr** [comment]
Indeed I can reproduce the problem but I don't don't know what is the problem?

 * I tried to disable the vscode-xml extension and problem disappear. 
 * the lsp4xml doesn't manage this kind of features
 * I suspect problem comes from client side in vscode-xml but I don't know where is the problem?

@xorye could you see this issue please when you will have time?

**Comment by fbricon** [comment]
Must be an issue in the increaseIndentPattern: 

https://github.com/redhat-developer/vscode-xml/blob/master/src/extension.ts#L221
