### ISSUE TITLE
Implement Autoclosing of tags

### ISSUE THREAD

**Issue by NikolasKomonen** [redhat-developer/vscode-xml#16]
In relation to https://github.com/angelozerr/lsp4xml/issues/82.

See how it's implemented on the client-side for HTML
* https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/htmlMain.ts#L19

* https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/htmlMain.ts#L75

* https://github.com/Microsoft/vscode/blob/f707828426bd87e88c17d2da34f2ceed0019d8bd/extensions/html-language-features/client/src/tagClosing.ts

**Comment by fbricon** [comment]
Fixed with #39
