### ISSUE TITLE
Active editor cannot provide outline infomation

### ISSUE THREAD

**Issue by Cisnocxie** [redhat-developer/vscode-xml#166]
I usually edit XML at a active editor to just see its structure and paste it to other places.

**Comment by fbricon** [comment]
Which version of redhat.vscode-xml do you have? You might want to disable other potentially conflicting xml extensions.

**Comment by fbricon** [comment]
Have you saved your file?

**Comment by Cisnocxie** [comment]
No, don't save.
Moreover, it is that I want to enable this extension features on a active eidtor(unsave file) when I change its language to XML.

**Comment by fbricon** [comment]
This was fixed by #156. You can install a CI build from https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D, before the 0.8.0 release at the end of the month.

**Comment by leiluxp** [comment]
I can´t fix this error in visual studio code: the active editor can not provide outline information. can you help me? thanks

**Comment by KhimairaCrypto** [comment]
I am using plugin v2.17.0  and latest terraform on my M1 (rosetta) and have similar error: "The active editor can not provide information about installed modules.."
