### ISSUE TITLE
CData block auto-complete

### ISSUE THREAD

**Issue by EduFrazao** [redhat-developer/vscode-xml#168]
Hi folks. Its possible to enable CData blocks autocomplete? Or there is no such feature?

**Comment by angelozerr** [comment]
You mean that completion provides

`<![CDATA[    ]>`

Is that?

**Comment by EduFrazao** [comment]
@angelozerr Yes, its exactly that feature. Thank you very mutch for this fast implementation!

**Comment by angelozerr** [comment]
@EduFrazao It's not finished, I'm implementing and I hope it will be available for 0.8..0.

**Comment by fbricon** [comment]
Fixed with https://github.com/angelozerr/lsp4xml/pull/524

![CommentCDataDemo2](https://user-images.githubusercontent.com/1932211/61666243-478ed580-acd7-11e9-8fb5-fba3320424f0.gif)

**Comment by EduFrazao** [comment]
Very nice!
Thank you very mutch for your effort guys!
