### ISSUE TITLE
Cache completion based on XML Schema/DTD

### ISSUE THREAD

**Issue by arkceajin** [redhat-developer/vscode-xml#172]
settings.json:
```
{
    "xml.java.home": "C:\\Program Files\\java-1.8.0-openjdk-1.8.0.212-3.b04.redhat.windows.x86_64",
    "xml.catalogs": ["file:///C:/Users/s-jiu/Desktop/AP-R19-03/MethodologyAndManifests/AUTOSAR_MMOD_XMLSchema/AUTOSAR_00047.xsd"],
    "xml.fileAssociations": [{
        "systemId": "file:///C:/Users/s-jiu/Desktop/AP-R19-03/MethodologyAndManifests/AUTOSAR_MMOD_XMLSchema/AUTOSAR_00047.xsd",
        "pattern": "*.arxml"
    }]
}
```
arxml:

```
<?xml version="1.0" encoding="UTF-8"?>
<AUTOSAR xmlns="http://autosar.org/schema/r4.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00047.xsd">
 ...
</AUTOSAR>
```
How to set the `xsi:schemaLocation` and `"systemId"` to making the `xsd` relate to the `arxml`?

**Comment by angelozerr** [comment]
You are using fileAssociation and XML catalog both. You must choose your binding kind.

 - xml.catalog must use a XML catalog file. In your case it link to xsd, it should be a XML catalog file. See https://www.oasis-open.org/committees/download.php/14809/xml-catalogs.html
 - xml.fileAssociations doesn't require a schemaLocation. 

I suggest you that you attach in this issue a zip of your vscode project.

**Comment by arkceajin** [comment]
> I suggest you that you attach in this issue a zip of your vscode project.
The project only contain a `arxml` which I going to create by using the `xsd`. 
xsd: https://github.com/autosaros/Standards/blob/master/Adaptive%20Platform/19.03/MethodologyAndManifests/AUTOSAR_MMOD_XMLSchema/AUTOSAR_00047.xsd

I tried create the xml and put in the same folder with xsd.
```
<?xml version="1.0"?>
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <uri name="http://autosar.org/schema/r4.0 AUTOSAR_00047.xsd" uri="file://./AUTOSAR_00047.xsd" />
</catalog>
```
But still not working...

**Comment by fbricon** [comment]
arxml and xsd files in the same folder, it works for me, but it's very slow, as the xsd is over 7MB. I increased the memory attributed to lsp4xml to 256MB in settings.json:
```
"xml.server.vmargs": "-noverify -Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication -Dlog.level=off",
```

<img width="804" alt="Screen Shot 2019-07-19 at 12 16 03 PM" src="https://user-images.githubusercontent.com/148698/61528425-05d40580-aa1f-11e9-8345-b2086febee45.png">

**Comment by angelozerr** [comment]
> but it's very slow

If I remember, today when XSD file is on the local, it is parsed every time:

 * when validation is done
 * when completion is done.

It should be improved by caching the XSD.

**Comment by arkceajin** [comment]
@fbricon Thanks, using the setting and without `xml.catalogs` simply put XML and XSD in the same folder could work well. So the problem is just the loading was too slow...

**Comment by angelozerr** [comment]
> So the problem is just the loading was too slow...

You mean that completion based on XML Schema to show in completion  INTRODUCTION, FORMULA, etc is slow?

**Comment by arkceajin** [comment]
@angelozerr  Yes, after specific `"xml.server.vmargs": "-noverify -Xmx256m -XX:+UseG1GC -XX:+UseStringDeduplication -Dlog.level=off",` the completion popup almost immediately.

**Comment by angelozerr** [comment]
@arkceajin just to clarify this issue:

 * when you set `"xml.server.vmargs" it works for you. Completion opens INTRODUCTION, FORMULA. Is it slow again? 
 * when you don't set `"xml.server.vmargs", you see nothing.

Is that?

**Comment by arkceajin** [comment]
Not nothing but sometime popup `Loading` or something popup dialog don't contains the completions as below:
![err](https://user-images.githubusercontent.com/8335699/61861592-3d531e00-af07-11e9-942f-55ceb4329566.png)

**Comment by angelozerr** [comment]
Thanks @adelasofia for your feedback. I'm working on this issue https://github.com/angelozerr/lsp4xml/issues/547

**Comment by angelozerr** [comment]
@arkceajin I fixed this issue in https://github.com/angelozerr/lsp4xml/issues/547 Now completion should be slow the first time and quick after. This feature is availabel for 0.9.0
