### ISSUE TITLE
Support xi:include

### ISSUE THREAD

**Issue by ebramirez** [redhat-developer/vscode-xml#175]
First, it looks like inline namespaces definition does not work.

In a docbook documento, the tag `<xi:include xmlns:xi="http://www.w3.org/2001/XInclude">`, the `xi:include` element is defined in the `XInclude.xsd` but is not recogniced:

![Screenshot from 2019-07-25 11-58-46](https://user-images.githubusercontent.com/42619854/61865915-732adf00-aed4-11e9-85a1-a19b1ecbe839.png)

Optionally, it would be great that the plugin took into account the include directive and parsed and the included document.

**Comment by fbricon** [comment]
Can you please attach a sample document reproducing this issue?

**Comment by ebramirez** [comment]
Here are the two files, and also as an [attachment](https://github.com/redhat-developer/vscode-xml/files/3438021/xi_include.tar.gz):

`include.xml`

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE chapter PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<chapter id="chapter_id">
  <title>Sample title</title>

  <para>Sample content</para>

  <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="reference.xml"/>
</chapter>
```


`reference.xml`

```xml
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE section PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">
<section id="section_id">
  <title>Sample title</title>

  <para>Sample content</para>
</section>
```

For the second part of my request, I have realized that it only makes sense when building the docbook, because the local references which do not have to make sense before the building; so this is only about the `<xi:include>` tag not being recognized as valid.

**Comment by Oobiewan** [comment]
Hi,
I am also missing support for xi:include. Especially to parse the xml that is included with xi:include and resolve references to it. E.g., the following should not give a validation error if **devd_building_artifacts_windows.xml** contains an element with `id="sectionWindowsArtifactBuild"`.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE section PUBLIC "-//OASIS//DTD DocBook XML V4.4//EN" "http://www.docbook.org/xml/4.4/docbookx.dtd" [
    <!ENTITY % xinclude SYSTEM "http://www.docbook.org/xml/4.4/xinclude.mod">
    %xinclude; ]>

<section id="chapterInstallingSystem">
    <title>Installing system</title>
    <xi:include href="devd_building_artifacts_windows.xml" xmlns:xi="http://www.w3.org/2001/XInclude" />
    <section><title>Section title</title>
    <para>Build the artifacts as described in <xref linkend="sectionWindowsArtifactBuild" /> </para>
</section>
```

**Comment by angelozerr** [comment]
> Is there a chance that this functionality will be implemented?

I don't know if it's easy to support xi:include.

**Comment by angelozerr** [comment]
@ebramirez if you define `xinclude.mod` like this:

```xml
<!ELEMENT xi:include (xi:fallback?) >
<!ATTLIST xi:include
    xmlns:xi   CDATA       #FIXED    "http://www.w3.org/2001/XInclude"
    href       CDATA       #REQUIRED
    parse      (xml|text)  "xml"
    encoding   CDATA       #IMPLIED >

<!ELEMENT xi:fallback ANY>
<!ATTLIST xi:fallback
    xmlns:xi   CDATA   #FIXED   "http://www.w3.org/2001/XInclude" >

<!ENTITY % local.chapter.class "| xi:include">

<!-- inside chapter or section elements -->
<!ENTITY % local.divcomponent.mix "| xi:include">
<!-- inside para, programlisting, literallayout, etc. -->
<!ENTITY % local.para.char.mix "| xi:include">
<!-- inside bookinfo, chapterinfo, etc. -->
<!ENTITY % local.info.class "| xi:include">
```

And you reference this file like this:

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE chapter PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd"  [
<!ENTITY % xinclude SYSTEM "xinclude.mod">
%xinclude;
]>
<chapter id="chapter_id">
	<title>Sample title</title>

	<para>Sample content</para>

	<xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="referencem.xml" />
</chapter>
```

it should work better, no.

It seems Oxygen suggest to do like this.
