### ISSUE TITLE
Magento 2 support

### ISSUE THREAD

**Issue by benjamenhogben** [redhat-developer/vscode-xml#176]
Hi all,

I'm trying to get this excellent plugin to work with Magento 2 xml files

I've tried generating the [misc.xml](https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-urn.html) file and adding it as a catalog in settings.json:
```json
{
  "xml.catalogs": ["misc.xml"]
}
```

```xml
<?xml version="1.0" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd">
	<module name="Example_ExamplePlugin" setup_version="1.0.0">
		<sequence>
			<module name="Magento_Catalog"/>
		</sequence>
	</module>
</config>
```

This is an example misc.xml file that is generated by the urn:generate command in the docs:
```xml
<?xml version="1.0"?>
<project version="4">
  <component version="2" name="ProjectRootManager"/>
  <component name="ProjectResources">
    <resource url="urn:magento:framework:ObjectManager/etc/config.xsd" location="/var/www/html/vendor/magento/framework/ObjectManager/etc/config.xsd"/>
```

The errors I'm getting in the editor are: 
```xml
<config>
```
`cvc-elt.1.a: Cannot find the declaration of element 'config'.xml(cvc-elt.1.a)`

and
```xml
xsi:noNamespaceSchemaLocation="urn:magento:framework:Module/etc/module.xsd"
```
`schema_reference.4: Failed to read schema document 'urn:magento:framework:Module/etc/module.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.`

Just wondering if anyone has managed to get it working and what the trick was? I've got it working with other platforms but not Magento 2

**Comment by angelozerr** [comment]
Your misc.xml  is not a XML Catalog.

I suggets you that you download the vscode project in this issue https://github.com/redhat-developer/vscode-xml/issues/87 and you see how to write a XML catalog.

**Comment by benjamenhogben** [comment]
Ahh I see - I'm kind of an amateur when it comes to XML. I usually just read the docs.

Would I need to write an XML catalog for the entire Magento 2 codebase? Or is there a subset of features Magento 2 uses that the plugin doesn't support?

**Comment by angelozerr** [comment]
To be honnest with you, I don't know Magento. It seems https://devdocs.magento.com/guides/v2.3/config-guide/cli/config-cli-subcommands-urn.html says that only PhpStorm support it, I suppose PhpStorm have developed something to support Magento.

Developping specific feature for specific framework is not in our priority, but if we have a lot of users requests about magento support, perhaps we could change that.

Any feedback are welcome if you write a XML catalog which is a standard mean to bind a uri (ex: magento urn) with XML Schema/DTD.

**Comment by viperet** [comment]
@benjamenhogben I developed VSCode extension, it can convert Magento 2 XML catalog into proper format accepted by this extension automatically. Try it - https://marketplace.visualstudio.com/items?itemName=viperet.vscode-magento-wizard

**Comment by angelozerr** [comment]
@viperet it's a really cool news! Thanks for this information.

I close this issue since Magento can be supported by XML catalog.

Please create another issues if you find another problems with Magento.

@viperet if you need some features to improve writing catalog or other things don't hesitate to create issues.
