### ISSUE TITLE
Is it possible to disable cdata autocompletion when typing period?

### ISSUE THREAD

**Issue by rmahroua** [redhat-developer/vscode-xml#179]
Hey,
I noticed that the "period" character triggers the `cdata` (`<![CDATA]>`)

Is there a way to prevent the period from triggering that? I would like to type `TAB` after a period to either exit a tag or inserting a tab, but not adding `cdata`:

<img width="897" alt="Screenshot 2019-08-26 13 40 30" src="https://user-images.githubusercontent.com/29074292/63721924-168a4f00-c807-11e9-8edb-733a7b68901e.png">

Unless this indicates that my XML schema is invalid?
Thanks

**Comment by angelozerr** [comment]
I understand the problem. 

@fbricon do you think we need to provide a settings to disable cdata and comment snippets?

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/issues/640
