### ISSUE TITLE
Typing in XML file causes EtagRequired error for surrounding scope

### ISSUE THREAD

**Issue by Eptis** [redhat-developer/vscode-xml#181]
Not sure if this is related to [this issue](https://github.com/redhat-developer/vscode-xml/issues/149), but I have the following issue when changing an XML file:

say I have the following XML:
```
<entitities>
</entities>
```

When I change it to:
```
<entitities>
        <entity id="someId">
            <attribute id="someOtherId"/>
        </entity>
</entitities>
```

I get the following error after `</entity>`:
> The element type "entities" must be terminated by the matching end-tag  "`</entities>`".xml(ETagRequired)

After deleting the `<entity>` element alltogether the error remains on the now empty line.

Restarting VScode removes this error and the file is valid again.

Is there any other information I can provide to help find the cause of this issue?

When retyping the `<entity>` element this sometimes also results in faulty completion like:
```
<entity id="flags">
            </tribute>
```

**Comment by Eptis** [comment]
I disabled all extensions except this one and it no longer occurs so its probably a different extension causing this ¯\_(ツ)_/¯

Thanks for the help!

**Comment by angelozerr** [comment]
@Eptis if you can find which extension causes this problem, it should be very cool.

**Comment by Eptis** [comment]
Will have a investigate over the weekend!
