### ISSUE TITLE
xml.fileAssociations property does not work with DTD files

### ISSUE THREAD

**Issue by amasino** [redhat-developer/vscode-xml#184]
Adding a file association in settings.json using a DTD like the following:

[{"systemId": "http://w3.atsec/cctool/dtd/my-grammar.dtd",
        "pattern": "ase_*.xml"}]

does not work. 

The extension successfully matches the xml file (I set "xml.validation.noGrammar": "error" and there is no error when opening the file) but neither is the DTD existence verified nor the grammar is checked.

**Comment by angelozerr** [comment]
Indeed the xml file associations doesn't work with DTD only with XSD. It's a limitation of Xerces, I created a bug for that https://issues.apache.org/jira/browse/XERCESJ-1711?filter=-2
