### ISSUE TITLE
Navigation and intellisense for xs:include-ed types

### ISSUE THREAD

**Issue by ArthurHNL** [redhat-developer/vscode-xml#188]
Consider the following XML Schemas:

SchemaA.xsd
```xml
<?xsml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<xs:include schemaLocation="SchemaB.xsd"/>

<xs:complexType name="Bar">
    <xs:sequence>
        <xs:element name="FooBar" type="xs:string"/>
        <xs:element ref="AType" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="Root">
    <xs:sequence>
        <xs:element name="Bar" type="Bar" minOccurs="1" maxOccurs="unbounded" />
    </xs:sequence>
</xs:complexType>

</xs:schema>
```

SchemaB.xsd:
```xml
<?xsml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="AType">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="XMLElement" type="xs:string" />
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>
```

Schema A includes Schema B and references the "AType" type from Schema B in the complex type named "Bar" (in Schema A). This is validated, for example when I make a typo, an error is shown.  However, IntelliSense does not suggest "AType" as value for the "Ref" attribute and when control-clicking on "AType" in Schema A, VSCode does not navigate to the definition of "AType" in Schema B.

**Comment by angelozerr** [comment]
Indeed it's a known limitation. See https://github.com/angelozerr/lsp4xml/issues/484

**Comment by fbricon** [comment]
Does in work in other IDEs?

**Comment by ArthurHNL** [comment]
@fbricon I have never tried it in another IDE but since it is a limitation of the underlying XML server I do not think it would work in another IDE.

**Comment by fbricon** [comment]
No, I was asking if that feature is available in other IDEs, not based on lsp4xml

**Comment by ArthurHNL** [comment]
@fbricon 
- Visual Studio 2019 does not have this feature, in fact the non-visual XML support of Visual Studio 2019 is pretty limited.
- JetBrains Rider does have this feature which means IntelliJ probably has it as well but I do not have IntelliJ installed so I can not confirm.

I have no other IDEs installed.

**Comment by angelozerr** [comment]
Thanks @ArthurHNL for your feedback. We need implement angelozerr/lsp4xml#484 to fixes navigation and completion with your case.

**Comment by angelozerr** [comment]
@ArthurHNL I'm working on this issue

**Comment by angelozerr** [comment]
A PR was created in https://github.com/angelozerr/lsp4xml/pull/579

See the following demo:

![XSIncludeDefAndCompletionDemo](https://user-images.githubusercontent.com/1932211/67145595-fca73e80-f282-11e9-995d-6f052b22598f.gif)

We should fix too the `Go to type definition` which gives the capability to go to the type definition of the xs:element from the XML file which is bound to the XML file.

![image](https://user-images.githubusercontent.com/1932211/67145638-4bed6f00-f283-11e9-8544-edd7e011bb7f.png)

I create the issue at https://github.com/angelozerr/lsp4xml/issues/581

**Comment by angelozerr** [comment]
This issue (completion + definition) was fixed with https://github.com/angelozerr/lsp4xml/pull/579

**Comment by ArthurHNL** [comment]
Thanks a lot!
