### ISSUE TITLE
cannot find element when validating with .NET generated xsd

### ISSUE THREAD

**Issue by kirni** [redhat-developer/vscode-xml#192]
Not sure if this is an issue of .NET or this plugin.

In my .NET C# application I am serializing classes with the *DataContractSerializer*.

When I manually modify those serialized files I also would like to validate them, use autocomplete etc. Therefore I also export the xsd for each class with *XsdDataContractExporter*

For some reason this is not working for the root element:
![image](https://user-images.githubusercontent.com/12346829/67026658-8b438080-f108-11e9-8840-9a880c6e4693.png)

I keep on getting the error: *cvc-elt.1.a: Cannot find the declaration of element 'Speaker'.*

Autocomplete however is no issue:
![image](https://user-images.githubusercontent.com/12346829/67027599-1b35fa00-f10a-11e9-900f-eb478c98a6c9.png)

All the other elements are fine.

I have attached the schema *SpeakerSchema.xsd* and the xml file *testSpeaker.speaker* as zip

[testSpeaker.zip](https://github.com/redhat-developer/vscode-xml/files/3740240/testSpeaker.zip)

**Comment by angelozerr** [comment]
Thanks @NikolasKomonen for your study. If you don't want declare schemaLocation in your XML you could configure a XML catalog too which reference your XML Schema with the proper namespace.

**Comment by kirni** [comment]
Hi @NikolasKomonen and @angelozerr  thank you for your prompt responses.

I tried adding the *xsi:SchemaLocation* but then I got another issue:
![image](https://user-images.githubusercontent.com/12346829/67090052-694e0a80-f1a9-11e9-98c4-379bbe3cf45e.png)

I guess there is a mess in my current setup or something.

However setting up a XML catalog worked like a charm. 

Thank you guys, I greatly appreciate your help!

**Comment by angelozerr** [comment]
If you wish to use `xmlns:i="http://www.w3.org/2001/XMLSchema-instance"` instead of standard `xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"`, you should write `i:schemaLocation="http://schemas.datacontract.org/2004/07/backend.confPlanner SpeakerSchema.xsd"` in other words:

```xml
<?xml version="1.0" encoding="utf-8" ?>
<Speaker
    xmlns:i="http://www.w3.org/2001/XMLSchema-instance"
    i:schemaLocation="http://schemas.datacontract.org/2004/07/backend.confPlanner SpeakerSchema.xsd"
    xmlns="http://schemas.datacontract.org/2004/07/backend.confPlanner">
  <availability>
    <blacklist>
      <DateRange>
        <End>2019-11-07T10:10:10.01</End>
        <Start>2019-10-13T10:10:10.01</Start>
      </DateRange>
    </blacklist>
  </availability>
  <id>Max Mustermann</id>
  <noBrakeRequired>false</noBrakeRequired>

</Speaker>
```

> However setting up a XML catalog worked like a charm.

It's a good news that XML catalog works for you. It will avoid adding at the end the schema location.

> Thank you guys, I greatly appreciate your help!

You are welcome!

**Comment by kirni** [comment]
I just tried this and it also works. Thank you for the additional information!
