### ISSUE TITLE
Formatting of newlines at EOF

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-xml#196]
Given the following xml:

````
<root>
    <child>value</child>
</root>


````

There are 2 issues when formatting:
* first, and most importantly: there's no way to keep a newline at EOF
* second, formatting is not idempotent: the first time it removes only 1 of the 2 trailing newlines, the second time it removes the remaining trailing newline

**Comment by angelozerr** [comment]
Indeed WE should have a new settings for that. An interesting features to explore is to try get this settings from editorconfig https://github.com/editorconfig/editorconfig/wiki/Newline-at-End-of-File-Support if thé XML new settings is not defined

**Comment by angelozerr** [comment]
3.15 LSP specification provides the `insertFinalNewline` formattings option that we should use to implement this issue. See https://microsoft.github.io/language-server-protocol/specifications/specification-3-15/#textDocument_formatting

**Comment by angelozerr** [comment]
Once https://github.com/eclipse/lemminx/issues/628 will be done, we will able to LSP4J `FormattingOptions#isInsertFinalNewline()`

**Comment by alexschrod** [comment]
Maybe I'm missing something, but I don't see any setting for preserving/ensuring there's a newline at EOF, and the formatter definitely removes any I add myself. Seeing this issue and it being resolved made me think it was a foregone issue, but clearly it's not? I'm using version 0.23.

**Comment by angelozerr** [comment]
https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#filesinsertfinalnewline should work. If it doesn't work, please create a new issue with your usecase.
