### ISSUE TITLE
xml.server.workDir with chinese path doesn't work

### ISSUE THREAD

**Issue by 1035311527** [redhat-developer/vscode-xml#201]
Does this plugin have the function like code completion.If so,how can i active the function.

**Comment by angelozerr** [comment]
Indeed completion from existing XML elements, based on XSD, DTD should work.

As vscode-xml consumes the XML Language Server lsp4xml written in Java, you need to install Java and configure the path to Java. Please read https://github.com/redhat-developer/vscode-xml#requirements

If after this configuration, it doesn't work please attach your XML documents, XML Schema, DTD in order we investigate the problem.

If after that it doesn't work, please atta

**Comment by 1035311527** [comment]
After configuration i can see the completion.There is one more question,can this complete the xml tag like idea or eclipse does. like that:
<img width="282" alt="pic" src="https://user-images.githubusercontent.com/24894908/69314689-c1c46c00-0c6f-11ea-917a-b041cd5a7c62.png">

**Comment by angelozerr** [comment]
In your sample, you have a completion item with dependency and if you apply it, it should generate

`<dependency><.dependency>`

what do you want more? Perhaps a snippet which generates dependency with version, etc?

Please describe more what you want, thanks.

**Comment by 1035311527** [comment]
For example , there is '<scope>' tag under dependency tag.But if i type  '<' in dependency tag i hope there would be scope in the list.
like this
![S91122-22454823](https://user-images.githubusercontent.com/24894908/69435186-089e8880-0d7a-11ea-97fe-50a133104d10.png)

**Comment by 1035311527** [comment]
I mean it is able to tell me the allowable tag from xsd file.And these tags will appear in the list.

**Comment by angelozerr** [comment]
> I mean it is able to tell me the allowable tag from xsd file.And these tags will appear in the list.

It should work like this:

![DependencyDemo](https://user-images.githubusercontent.com/1932211/69436359-87c39a80-0d41-11ea-9194-d41639c80baa.gif)

The completion provides tag elements coming from the XML Schema and according the XML content. For instance you can see in the demo that once `artifactId` is inserted, the completion doesn't provide it (acoording the XML Schema constraints).

Is it working like this for you? If no please share your XML file. If yes, what did you expect?

**Comment by 1035311527** [comment]
Yeah,just like this.But there is no tag in the list.Shoud i download the xsd file in order to make the completion work?

**Comment by angelozerr** [comment]
If your XML file (I suppose pom.xml) is bound to XML Schema with `xsi;shemaLocation` it should download it in a cache folder `.lsp4xml`.

I suggest you:

 * to share your XML file
 * if you have defined  `xsi;shemaLocation`, have you some error like download error?

**Comment by 1035311527** [comment]
It seems like there is already cache file in the cache folder.It can tell me the content in the tag.Like the version or something else.But i don't know why threre is no tag tips in the list.I guess maybe because i have something wrong in my configuration?
![QQ浏览器截图20191123195243](https://user-images.githubusercontent.com/24894908/69478275-9b4b3000-0e2b-11ea-803e-e15e7744f528.png)
![QQ浏览器截图20191123195744](https://user-images.githubusercontent.com/24894908/69478276-9c7c5d00-0e2b-11ea-9a74-782bcb9266ef.png)
![QQ浏览器截图20191123195900](https://user-images.githubusercontent.com/24894908/69478294-b87ffe80-0e2b-11ea-8335-548407a55822.png)

**Comment by fbricon** [comment]
Try disabling the Maven extension, see if it might cause some conflicts

**Comment by angelozerr** [comment]
> Try disabling the Maven extension, see if it might cause some conflicts

In my case I have vscode-maven and vscode-xml installed and it works great.

> It seems like there is already cache file in the cache folder.It can tell me the content in the tag.Like the version or something else.But i don't know why threre is no tag tips in the list.

The version completion is managed by vscode-maven not by vscode-xml.

If you open completion after dependencies, you should see 4 completions items:

![image](https://user-images.githubusercontent.com/1932211/69479944-5e6b4300-0e03-11ea-9df1-ec89b6f2b0cb.png)

 * the first dependency comes from the XML Schema managed by vscode-xml
 * the second dependency comes from vscode-maven (it's a snippet)

It seems that you have in your case only the second dependency (from vscode-maven). 

If you create a new XML file like this:

```xml
<root>
   <a>
```

Do you see some errors? if no it means that there is a trouble with vscode-xml.

You should see logs in the Output / XML support when you open completion for instance:

![image](https://user-images.githubusercontent.com/1932211/69480040-244e7100-0e04-11ea-888e-33e86fb66d64.png)

Can you see those logs?

**Comment by 1035311527** [comment]
Error?like this? yes.And here is the logs.
![深度截图_选择区域_20191124130607](https://user-images.githubusercontent.com/24894908/69489978-671f5000-0ebb-11ea-97e1-55166cd08532.png)
![深度截图_选择区域_20191124130719](https://user-images.githubusercontent.com/24894908/69489979-67b7e680-0ebb-11ea-898b-65928162af58.png)

**Comment by angelozerr** [comment]
Ok thanks it means that XML language server is working.

Could you share please your XML file?

Have you some errors in your XML when you try to insert an XML like <bad-tag /> in your XML ?

When you try to open completion you should see logs, could you share it?

**Comment by 1035311527** [comment]
[xml.txt](https://github.com/redhat-developer/vscode-xml/files/3883350/xml.txt)
This text is the xml file create by vscode-maven.And the error.Yes ,if i dont insert the content it will warn me there is error.And there is no particular message in logs.
![QQ截图20191124164711](https://user-images.githubusercontent.com/24894908/69492218-78c42000-0eda-11ea-9e7a-9e8a974424b9.png)
![QQ截图20191124164948](https://user-images.githubusercontent.com/24894908/69492219-795cb680-0eda-11ea-881c-feb9160499b0.png)
And it seems like there is a part of tags but not all of them like yours.
![QQ截图20191124165103](https://user-images.githubusercontent.com/24894908/69492236-c771ba00-0eda-11ea-8e07-93acde46c618.png)
I have also try other  XML file with different  Schema and there is no difference.

**Comment by angelozerr** [comment]
It seems you have completion items. When you have a key as icon it comes from vscode-xml completion. 

In my demo i open completion inside dependencies tag (not inside plugins tag). Is it working for you?

**Comment by 1035311527** [comment]
Seems like not working.Will that because there are some conflicts with other plugin or this plugin depend on other plugin?

**Comment by 1035311527** [comment]
This is my setting file of vscode,Is there any mistake? "D:\Java" is my java home path.

**Comment by angelozerr** [comment]
I think your settings should be good since validation is working.

I have tried your XML file and everything works well. When I open completion before <modelVersion, I have that:

![image](https://user-images.githubusercontent.com/1932211/69496296-f1be7a00-0ed0-11ea-9ea8-f0d76268a50f.png) 

Do you have the same completion result? If no, could you see the Output and check you have completion request/response like this:

![image](https://user-images.githubusercontent.com/1932211/69496345-904adb00-0ed1-11ea-88eb-cdc2389bb1a6.png)

**Comment by 1035311527** [comment]
No,there is nothing but the initialize information in output.

**Comment by angelozerr** [comment]
> No,there is nothing but the initialize information in output.

Enable LSP server by adding this settings:

```xml
"xml.trace.server": "verbose"
```

**Comment by 1035311527** [comment]
Yes,there is.
![QQ浏览器截图20191125165559](https://user-images.githubusercontent.com/24894908/69526691-ba6dcd00-0fa5-11ea-80c3-5fdbc3c1aa7d.png)

I am a little confuse there is content tips,but dont have the tag tips.
![QQ浏览器截图20191125165824](https://user-images.githubusercontent.com/24894908/69526678-b641af80-0fa5-11ea-896b-7d98c517218d.png)

**Comment by angelozerr** [comment]
> Yes,there is.

And what about request response completion? Have you an empty result for completion response?

> I am a little confuse there is content tips,but dont have the tag tips.

It's completion from vscode-maven and not from vscode-xml which manages only completion based on XML Schema. This groupId completion is specific to maven which is managed by vscode-maven.

**Comment by 1035311527** [comment]
Seems like there is too many response.I am not sure which one you are taling about.But most of the responses is empty in result.
![QQ浏览器截图20191125193929](https://user-images.githubusercontent.com/24894908/69537799-d41a0f00-0fbb-11ea-85c8-fb75c7869335.png)

**Comment by angelozerr** [comment]
I mean `Received response 'textDocument/completion`.

Could you share your trace please.

**Comment by 1035311527** [comment]
There are three responces after i type '<' in dependencies tag.And there is no match result.
![QQ浏览器截图20191126183702](https://user-images.githubusercontent.com/24894908/69622383-cdeb6780-107b-11ea-861e-662a9b07ff11.png)
![QQ浏览器截图20191126183359](https://user-images.githubusercontent.com/24894908/69622421-dd6ab080-107b-11ea-9a89-c9d9df05cfa2.png)
![QQ浏览器截图20191126183412](https://user-images.githubusercontent.com/24894908/69622426-de9bdd80-107b-11ea-8d02-958362182e2e.png)

**Comment by angelozerr** [comment]
It should work, I don't understand why you have this problem?

I have seen from your settings that you have Spring Boot Extension. Could you disable it please and retry completion.

When you hover the `modelVersion `tag, you should see the documentation with an hyperlink to the XML Schema:

![image](https://user-images.githubusercontent.com/1932211/69635880-a84b6780-1055-11ea-9f02-57e83697a0ab.png)

Have you that?

**Comment by 1035311527** [comment]
Not work,there is nothing when i hover the tag.

**Comment by 1035311527** [comment]
I will try to disble other plugin and see if it is wroking

**Comment by 1035311527** [comment]
Seems like even i disable all the plugins it still not working.

**Comment by 1035311527** [comment]
There is response after i type some chars of the tag.But the question is the result tags wouldn't add to the list.Hopefully it can be fixed.
![QQ截图20191210214658](https://user-images.githubusercontent.com/24894908/70535308-d1acdd00-1b97-11ea-9f63-38f139ae74ab.png)

**Comment by angelozerr** [comment]
To be honest with you, I have no idea why you have this problem? The hover and completion works with the same component (ContentModelManager) so it's explain why hover and completion based on maven xsd doesn't work.

Could you try :

 * configure a `xml.server.workDir` with a folder (like `C:/lsp4xml`) and open pom.xml. You should have  maven xsd file in `C:\lsp4xml\cache\http\maven.apache.org\xsd` is it working for you?

In case if it not work, could you download at hand the maven xsd and copy it tin the  C:\lsp4xml\cache\http\maven.apache.org\xsd` and retry hover and completion

**Comment by 1035311527** [comment]
Seems like it works after i change the path of the cache file.Maybe because the default path?
<img width="555" alt="QQ浏览器截图20191211170626" src="https://user-images.githubusercontent.com/24894908/70607053-b8a83880-1c38-11ea-9193-4f91f3e746f5.png">

**Comment by angelozerr** [comment]
I'm glad it works for you. I think it's a right problem (by default it stores the cache in .lsp4xml from you OS user dir). If you use this default folder and you activate logs with `xml.logs.client` do you see some error trace?

**Comment by 1035311527** [comment]
Actually i think that is because my computer user name is Chinese words.And i guess that is where the problem is.

**Comment by fbricon** [comment]
@1035311527 can you paste here the path to your home/user directory?

**Comment by 1035311527** [comment]
> @1035311527 can you paste here the path to your home/user directory?

Im using windows.And my user directory is "C:\Users\萌新"

**Comment by fbricon** [comment]
I tried setting "xml.server.workDir": "~/萌新/.lemminx" on my Mac and it worked.

@1035311527 is this still an issue with the latest vscode-xml release?

**Comment by 1035311527** [comment]
> I tried setting "xml.server.workDir": "~/萌新/.lemminx" on my Mac and it worked.
> 
> @1035311527 is this still an issue with the latest vscode-xml release?

Yes it works

**Comment by fbricon** [comment]
If it works, then let's close this one
