### ISSUE TITLE
Troubleshooting help

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/vscode-xml#21]
I would like to try out this extension. I tried it on this small example project  https://raw.githubusercontent.com/microclimate-devops/xml-language-server/master/client-vscode/xml-client/readme-resources/examples.zip from another XML extension, but I cannot get any of the features to work.

How do I debug this? I don't see an output channel for the extension, is there any way to enable logging?

**Comment by rtosman** [comment]
There should be an output console for it. I can see it. Doesn't help much
though, since there are just a bunch of java exceptions

**Comment by felixfbecker** [comment]
I got it to work now, must have been a misconfiguration with vscode. But you are right, there are exceptions. Will file those on the language server.
