### ISSUE TITLE
Cursor move around

### ISSUE THREAD

**Issue by ciaranchen** [redhat-developer/vscode-xml#211]
When I selected a text range, the anchor move around. I disable all other extensions, but the question still exists.

I thought the question is in `src/mirrorCursor.ts`. the `window.onDidChangeTextEditorSelection` was called multiple times while I selected a text range.  It's parallel. 

Then in event handler, it calls `exitMirrorMode` which change selections. 

So when I selected a range of text quickly, anchor will go back to the charator I selected before. And if I click on other position, the anchor will move around the whole page.

Sorry for my poor English. I have tried. 

![屏幕录制2019-12-14下午12 25 38](https://user-images.githubusercontent.com/19751193/70845402-2fd40b80-1e89-11ea-84a4-c496d6a5eb63.gif)

**Comment by fbricon** [comment]
@ciaranchen try toggling the cursor mirror mode with Ctrl+Shift+F2 (or Cmd+Shift+F2 on mac)

@NikolasKomonen @xorye when mirror mode is disabled, the event handler should be removed so as to avoid that.

**Comment by fbricon** [comment]
This is really bad
![Dec-14-2019 11-05-25](https://user-images.githubusercontent.com/148698/70847193-d9070b80-1e61-11ea-904e-ee732ecf10ce.gif)

**Comment by daveb-501commons** [comment]
Happening for me as well
https://github.com/microsoft/vscode/issues/86966#issuecomment-565684099
https://github.com/angelozerr/lsp4xml/issues/601

**Comment by fbricon** [comment]
0.10.1 released, the mirror cursor editing has been temporarily removed

**Comment by angelozerr** [comment]
Thanks @fbricon !
