### ISSUE TITLE
Contributing completion and definitions from another extension

### ISSUE THREAD

**Issue by viperet** [redhat-developer/vscode-xml#212]
Is there a way to contribute the completion of the attribute value from another VSCode extension? I know there is a mention of such possibility using Java code (mentioned in the readme), but VSCode extensions are written using TypeScript, not Java. Maybe you can think about a way to allow easy interface for other extensions to provide completions and/or definitions for attribute values?

**Comment by angelozerr** [comment]
Today, all features (completion, hover, validation, definition, codelens, codeaction, etc) are Java SPI and are extendable (ex: XML completion based on XML Schema is a Java SPI).

I suggest you read https://github.com/redhat-developer/vscode-xml#custom-xml-extensions you will see how to implement custom extension in Java SPI and how to register it in vscode extension.

The basic idea is to write your extension with Java SPI and register it your Java SPI in a vscode extension with package.json.

If this feature is not enough for you, please explain more your usecase. I have some ideas how to improve again the extension support but I would like to have more usecases.

Please see https://github.com/angelozerr/lsp4xml/issues/596 too

**Comment by viperet** [comment]
Thanks for a fast response! Yes, I know about the possibility to extend using Java SPI, but in my use case I have Magento 2 extention, with is written in TypeScript with a bit of PHP, it indexes extensions and themes registered in Magento, and provides userfull code generation features for developer and I also wanted to provide completion for class names and templates in the XML layouts. To extend vscode-xml using Java is not a very convenient for me, because I need to pass knowledge about registered extensions from JS into Java somehow and keep that data up to date. That introduces a lot of unneeded complexity. So I thought about some proxy, written in Java that extends all features of vscode-xml but sends all requests to TypeScript extensions using JSON RPC.

**Comment by angelozerr** [comment]
@viperet I love this usecase!

Today there is no way to implement your requirement, but I would like to work on this support in angelozerr/lsp4xml#596

There are 2 strategies to implement your requirement:

# vscode completion

Implement a vscode completion which consumes a custom LSP services registered in XML Language Server (LSP4XML). This custom LSP service (written in Java)  could be called `Position getClassAttributeValuePosition(int offset)` which could return the position of class name attribute value and return null if completion was not trigered inside attribute value class name. In case if it returns a position, you could consume your TypeScript Magento 2 extention to return a completion for class names by using the position given from getClassAttributeValuePosition.

# LSP4XML completion

Implements a Java completion participant which check if completion is on class attribute value and in this case it consumes the LanguageClient from TypeScript which should returns all class names.

What do you think about thoses ideas @viperet ?

**Comment by viperet** [comment]
@angelozerr I thought about simple interface:

extension in VSCode exports public API, like
```function getXMLAttributeCompletion(xmlFile: Uri, attributeType: string, attribueValue: string): string[]```

vscode-xml discovers extensions exporting such function and calls them when the user edits attribute value, passing XML file URI, attribute type name (from XSD) and value currently entered by the user for that attribute. And extension would return an array of possible completions.

**Comment by angelozerr** [comment]
@viperet I think it's too specific for your need and string[] is not enough (it needs documentation, for instance). 

I would prefer providing a mean to communicate with LSP4XML and developer like you should develop the glue between Java and TypeScript. In this case you will manage your own method signature according your need.

After that if we see that getXMLAttributeCompletion is used in a lot of projects we could provide an extension which provides this glue.

**Comment by angelozerr** [comment]
@viperet after thinking about your usecase, I think `vscode completion` mean is the best way (I mean This custom LSP service (written in Java) could be called Position getClassAttributeValuePosition(String uri, int offset)) because with your solution, it means that one moment all TypeScipt information to build completions on Java side will be posted to the XML Lanaguage Server which is not performant.

Your usecase interested me, if you are aware to experiment this solution, please tell me.

**Comment by viperet** [comment]
@angelozerr very interested in adding XML attribute values completion for Magento in my extension. But my Java knowledge is very limited (created J2ME calendar app 10+ years ago and that's all). If I can help somehow from the VSCode/Typescript side - let me know.

**Comment by angelozerr** [comment]
@viperet the main work should be done in TypeScript side by using vscode.  I would like to follow the same idea than vscode-maven which manages completion on TypeScript side and call the Java Language Server to compute their maven dependencies coming from Java Language Server.

See https://github.com/microsoft/vscode-maven/blob/9eddbd912b9e5e97f0bc3e458bec8ed652e0d0e1/src/completion/completionProvider.ts#L32

In your case, you want to know if you are in a xml class attribute or not. You can do like vscode-maven with full TypeScript (see getCurrentNode) https://github.com/microsoft/vscode-maven/blob/9eddbd912b9e5e97f0bc3e458bec8ed652e0d0e1/src/completion/completionProvider.ts#L35 but it means that it reparse the XML file each time you open the completion.

You could do that and not using LSP4XML...

But my idea is to use LSP4XML which manages a cache of DOM Document on XML Language Server side. The idea is to implement the getCurrentNode but on XML Language server side.

I think you could implement your completion with full TypeScript like explained below and when you are ready I could help you to implement getCurrentNode with LSP4XML.

**Comment by viperet** [comment]
@angelozerr thanks! Already started to implement completions using vscode-maven as an example.

**Comment by angelozerr** [comment]
vscode-xml provides now a vscode command `xml.workspace.executeCommand` which executes a custom command on XML Language Server side (the command must be written in Java). See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Extensions.md#commands

@viperet if you wish to consume XML commands and you need feedback, please reopen this issue.
