### ISSUE TITLE
XML Validation fails with 0.10.* versions

### ISSUE THREAD

**Issue by dkolepp** [redhat-developer/vscode-xml#214]
My XML documents started showing errors for every XML tag, with the 0.10.* versions:
![image](https://user-images.githubusercontent.com/10145457/71194059-3e3f7000-2259-11ea-8a64-c4ca2c2b8bb1.png)
![image](https://user-images.githubusercontent.com/10145457/71194116-5adba800-2259-11ea-9612-2ccabe0c5059.png)

When I downgraded to 0.9.1:
![image](https://user-images.githubusercontent.com/10145457/71193932-fae50180-2258-11ea-9996-edc5b99259d7.png)

the errors disappear:

![image](https://user-images.githubusercontent.com/10145457/71193897-e7d23180-2258-11ea-837a-29851bd7f827.png)

**Comment by fbricon** [comment]
Can you attach a sample document?

**Comment by dkolepp** [comment]
sure - the below document has the same issue.  Works fine with 0.9.1, but not any of the 0.10.* versions.

```
<?xml version='1.0' encoding='UTF-8'?>
<!DOCTYPE section PUBLIC "-//OASIS//DTD DocBook XML V4.5//EN" "http://www.oasis-open.org/docbook/xml/4.5/docbookx.dtd">

<section>
  <title>Test</title>
  <para>
    This is a test.
  </para>
</section>
```

**Comment by angelozerr** [comment]
Since 0.10.* versions we disable by default resolve external entities since security feedback. To enable it, add in your settings:

````xml
"xml.validation.resolveExternalEntities": true
```

if it doesn't work, close your vscode and reopen it.

**Comment by dkolepp** [comment]
I did need to select this option:

![image](https://user-images.githubusercontent.com/10145457/71201858-ead51e00-2268-11ea-90a5-b1737c18f319.png)

After I did this, a restart of VS Code was required, but I no longer had validation issues.  Thanks for the quick response!

**Comment by dkolepp** [comment]
Is it possible to give users a better idea that this is the problem?  Detect that an external entity is available, but is **purposefully** not being parsed/used - and that may be the cause of the errors?  Food for thought...
