### ISSUE TITLE
xml.fileAssociations cannot load xsd

### ISSUE THREAD

**Issue by arkceajin** [redhat-developer/vscode-xml#215]
[AUTOSAR_00048.zip](https://github.com/redhat-developer/vscode-xml/files/4029276/AUTOSAR_00048.zip)

Setting: 
```
    "xml.fileAssociations": [
        {
            "systemId": "c:\\Users\\s-jiu\\Desktop\\最新AUTOSAR\\R19-11\\MethodologyAndManifests\\AUTOSAR_00048.xsd",
            "pattern": "*.arxml"
        }
    ],
```
XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<AUTOSAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://autosar.org/schema/r4.0" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00048.xsd">
	<AR-PACKAGES>

	</AR-PACKAGES>
</AUTOSAR>
```
Error:
![image](https://user-images.githubusercontent.com/8335699/71874501-6e49a700-3165-11ea-921d-74efff070d2f.png)
![image](https://user-images.githubusercontent.com/8335699/71874523-799cd280-3165-11ea-9dca-02e444c4a792.png)

The xsd file can load by `xsi:schemaLocation` when I put the xsd in same folder of xml file.
but I expect xml.fileAssociations work as an universal setting, all xml which matches the specified in `pattern`, uses the xsd specified in `systemId` instead of `xsi:schemaLocation`, especially when file path in `xsi:schemaLocation` cannot be loaded.

**Comment by angelozerr** [comment]
@arkceajin not sure it's the problem but your system id contains a chinese character `c:\\Users\\s-jiu\\Desktop\\最新AUTOSAR\\R19-11\\MethodologyAndManifests\\AUTOSAR_00048.xsd` and perhaps it's the problem?

It seems that there were a problem (not the same) but with chinese character in https://github.com/redhat-developer/vscode-xml/issues/201#issuecomment-568249674

Could you try to set your XSD outside the folder which have Chinese character please? 

If it works, we will investigate why Chinese character doesn't work. Thanks!

**Comment by arkceajin** [comment]
@angelozerr Hi 
> Could you try to set your XSD outside the folder which have Chinese character please?

I tried to put xsd another folder without Chinese character, and the problem did fixed. Now work like a charm. Thanks.

**Comment by arkceajin** [comment]
> @angelozerr Hi
> 
> > Could you try to set your XSD outside the folder which have Chinese character please?
> 
> I tried to put XSD in another folder without Chinese character, and the problem did fixed. Now work like a charm. Thanks.

Hi, @angelozerr 
Sorry! the last comment was wrong, using path without the Chinese characters still do not work. I forgot to remove the XSD within the XML folder.

**Comment by angelozerr** [comment]
@arkceajin after reading in more detail your sample, you must not use xml.fileAssociations but use XML catalogs:

 * xml.fileAssociations is used when you wish to bind some XML files to a XSD Schema bit without using xsi:schemaLocation
 * xml.catalogs gives the capability to write a XML catalog. You can see for instance an example at http://www.sagehill.net/docbookxsl/WriteCatalog.html#MapURLtoFile 

We have already a [discussion about that](https://github.com/redhat-developer/vscode-xml/issues/172#issuecomment-513046056). If you have a problem with XML catalog, please attach a zip with your vscode project

**Comment by arkceajin** [comment]
@angelozerr Hi, Finally everything got worked. Thanks.

BTW, Suggest gives a warning when the path in the catalog is wrong.  This was the reason I didn't get worked.

And why don't let `xml.fileAssociations` takes higher priority than `xml.catalogs`? Because I think it is an external feature of the schema to XML mapping.

**Comment by angelozerr** [comment]
> BTW, Suggest gives a warning when the path in the catalog is wrong. This was the reason I didn't get worked.

I agree, please create a new issue with that.

> And why don't let xml.fileAssociations takes higher priority than xml.catalogs? Because I think it is an external feature of the schema to XML mapping.

Indeed xml.fileAssociations is not a XML spec part,although XML catalogs belongs to XML spec.

I close the issue since you have resolved your problem.
