### ISSUE TITLE
Warning when the xml.catalogs path cannot be found

### ISSUE THREAD

**Issue by arkceajin** [redhat-developer/vscode-xml#217]
When setting an unexisting path in xml.catalogs.
```
"xml.catalogs": ["c:\\AUTOSAR\\asdasdAUTOSAR_00048.xml"] <- wrong 
"xml.catalogs": ["c:\\AUTOSAR\\AUTOSAR_00048.xml"] <- right
```
XML:
```
<?xml version="1.0" encoding="UTF-8"?>
<AUTOSAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://autosar.org/schema/r4.0" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00048.xsd">
</AUTOSAR>
```
Now gives these
![image](https://user-images.githubusercontent.com/8335699/72028210-07db9a80-32c5-11ea-8460-fbcbbef546bf.png)
![image](https://user-images.githubusercontent.com/8335699/72028242-23df3c00-32c5-11ea-9c85-a2ef4c4bbfa4.png)
Suggest gives the speicfic warning that schema document cannot find is caused by the wrong path of catalog.

**Comment by angelozerr** [comment]
I fear that it's not possible to do that since it's a vscode settings and there are no API to manage validation for this settings.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/757
