### ISSUE TITLE
xsd:enumeration autocomplete don't work for text node

### ISSUE THREAD

**Issue by arkceajin** [redhat-developer/vscode-xml#218]
xsd: https://github.com/redhat-developer/vscode-xml/files/4029276/AUTOSAR_00048.zip
xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<AUTOSAR xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://autosar.org/schema/r4.0" xsi:schemaLocation="http://autosar.org/schema/r4.0 AUTOSAR_00048.xsd">
	<AR-PACKAGES>
		<AR-PACKAGE>
			<SHORT-NAME>aubist</SHORT-NAME>
			<AR-PACKAGES>
				<AR-PACKAGE>
					<SHORT-NAME>ara</SHORT-NAME>
					<ELEMENTS>
						<SOFTWARE-PACKAGE>
							<SHORT-NAME>test</SHORT-NAME>
							<ACTION-TYPE></ACTION-TYPE>
						</SOFTWARE-PACKAGE>
					</ELEMENTS>
				</AR-PACKAGE>
			</AR-PACKAGES>
		</AR-PACKAGE>
	</AR-PACKAGES>
</AUTOSAR>
```
For tag `<ACTION-TYPE>` suppose allow these values
 - INSTALL
 - REMOVE
 - UPDATE 

But now gives nothing, suggest show the autocomplete as above.
![image](https://user-images.githubusercontent.com/8335699/72032228-17adab80-32d2-11ea-93eb-24628984ddc9.png)

**Comment by angelozerr** [comment]
Completion based on xsd:enumeration works for attribute value but not for text node. We should implement it.

**Comment by angelozerr** [comment]
This issue is not very hard, I will implement it soon.

**Comment by angelozerr** [comment]
I create a PR to support this issue at https://github.com/eclipse/lemminx/pull/632 (it's soon finished), here a demo:

![XSDEnumerationOnText](https://user-images.githubusercontent.com/1932211/79137100-5f047600-7db2-11ea-9f4f-183f955e278c.gif)

**Comment by arkceajin** [comment]
thanks, it looks great.
