### ISSUE TITLE
Formatter expand/collapse/ignore empty XML tags

### ISSUE THREAD

**Issue by alanlivio** [redhat-developer/vscode-xml#219]
is It possible to configure the vscode-XML formatter to collapse empty XML tags?
Exemple. from:

```xml
<example></example>
```
to:

```xml
<example/>
```

It is done by other vscode extension but individually:
  https://marketplace.visualstudio.com/items?itemName=wongjiahau.collapsed-expand-empty-tag

**Comment by angelozerr** [comment]
Indeed we should provide this format settings but we should take care if XML is bound to a XML Schema /DTD which defines non empty element.

**Comment by angelozerr** [comment]
@alanlivio I'm working on this issue, see the current status:

![FormatEmptyElements](https://user-images.githubusercontent.com/1932211/79634954-0f38fc80-816e-11ea-94df-c3054048033d.gif)

**Comment by angelozerr** [comment]
It seems https://github.com/wongjiahau/VSCode-CollapseExpandEmptyTag#known-issues have some limitation, vscode-xml will have not this limitation:

![FormatEmptyElements2](https://user-images.githubusercontent.com/1932211/79635185-bec29e80-816f-11ea-8aa3-46024442b784.gif)

**Comment by fbricon** [comment]
New `xml.format.emptyElements` preference has been added with expand/collapse/ignore options

**Comment by alanlivio** [comment]
Thanks @angelozerr and @fbricon .
Best regards.
