### ISSUE TITLE
No IntelliSense on .xsd files

### ISSUE THREAD

**Issue by felixfbecker** [redhat-developer/vscode-xml#22]
Originally reported here: https://github.com/angelozerr/lsp4xml/issues/111

I am trying to get autocompletion while authoring an XSD.
For this, I declared the XSD as an instance of the XSD meta schema:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xs:schema attributeFormDefault="unqualified"
           elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
           xsi:schemaLocation="http://www.w3.org/2001/XMLSchema
                               http://www.w3.org/2001/XMLSchema.xsd">

</xs:schema>
```

However, I am not getting any autocompletion or hovers.

If I rename the file to have a `.xml` extension, it works as expected.

It would be great if the extension didn't depend on specific file extensions, but just checked if the file started with a `<?xml` declaration, because there are many files that are XML but don't use a .xml extension, e.g. `.xsd`, `.ps1xml` or `.csproj`.

Output channel log:

```
Sep 10, 2018 2:18:30 PM org.eclipse.lsp4xml.XMLLanguageServer initialize
INFO: Initializing LSP4XML server
```

(no errors)

Version: `vscode-xml-0.1.0-199.vsix`

**Comment by angelozerr** [comment]
Please add too `xsl` but it will requires the xsl extension https://github.com/angelozerr/lsp4xml/tree/master/extensions/org.eclipse.lsp4xml.xsl (if we don't want to declare the XSL Schema and just using the xsl version declared in the root)

**Comment by fbricon** [comment]
xsd documents are mapped to xml support. You can see traffic exchanged between vscode and the server when setting `xml.trace.server:"verbose"` in settings.json. So there's something fishy here.

**Comment by felixfbecker** [comment]
So is this a language server issue after all?

**Comment by fbricon** [comment]
ooh it seems I got completion support after a while. Maybe downloading the remote resources takes too long?

**Comment by angelozerr** [comment]
> Still the server should probably make sure the completion items are unique in the returned list.

Should be fixed.

> I don't get any hover on <xs:annotation> though. The hover request is properly sent to the server, so something's not working there.

```xml
<xs:element name="schema" id="schema">
<xs:annotation>
<xs:documentation source="http://www.w3.org/TR/xmlschema-1/#element-schema"/>
</xs:annotation>
<xs:complexType>
```
WTP XML Editor don't use this xs:annotation in this case:

![image](https://user-images.githubusercontent.com/1932211/45328270-7f77a900-b55b-11e8-84be-2d1cf7dfe3e6.png)

So which documentation should we shown in this case?

**Comment by angelozerr** [comment]
> ooh it seems I got completion support after a while. Maybe downloading the remote resources takes too long?

WTP fixes this speed problem by providing an XML catalog with the 2 XML Schema :

```
<uri
		name="http://www.w3.org/2001/XMLSchema"
		uri="platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/XMLSchema.xsd" />
<system
		systemId="http://www.w3.org/2001/xml.xsd"
		uri="platform:/plugin/org.eclipse.xsd/cache/www.w3.org/2001/xml.xsd"/>	
```
See https://github.com/eclipse/webtools.sourceediting/blob/master/xml/bundles/org.eclipse.wst.xsd.core/plugin.xml#L86

I think the first time it download the 2 XML Schema and set thoses XML Schema files inside platform:/plugin/org.eclipse.xsd/cache folder, the second time it can use the XML Schema downloaded. It should be cool to have this cached features too.

**Comment by fbricon** [comment]
Intellisense now works for xsds. Hover not so much.

**Comment by fbricon** [comment]
Actually, it requires server caching to be enabled in vscode. @NikolasKomonen can you fix #67?

**Comment by angelozerr** [comment]
> Actually, it requires server caching to be enabled in vscode.

No need that since, server enable cache by default.

**Comment by angelozerr** [comment]
> Hover not so much.

Whzt do you mean?

**Comment by fbricon** [comment]
@angelozerr see https://github.com/angelozerr/lsp4xml/issues/192. 
I'll close this issue for now as it focuses on completion support, which is now fully operational.
