### ISSUE TITLE
Is it possible to get a vsix release for 0.10.0/0.10.1?

### ISSUE THREAD

**Issue by JPinkney** [redhat-developer/vscode-xml#224]
Hi! Just wondering if its possible to add a vsix for 0.10.0 and 0.10.1 so that we can use the releases in Che plugin registry ;)

**Comment by fbricon** [comment]
There:
- https://github.com/redhat-developer/vscode-xml/releases/tag/0.10.1
- https://github.com/redhat-developer/vscode-xml/releases/tag/0.10.0
