### ISSUE TITLE
Automatically closing tags in multi-cursor mode only closes one tag

### ISSUE THREAD

**Issue by ckoppelman** [redhat-developer/vscode-xml#225]
## Description

In multi-cursor mode, the autocompletion only completes one XML Tag.

## Steps to reproduce

1. Set `"xml.completion.autoCloseTags": true`.
2. Type the following (pipes indicate multiple cursor locations):

```
    <lib|
    <lib|
    <lib|
    <lib|
```

3. Type `>`

### Expected
I expect the document to look like this:

```
    <lib>|</lib>
    <lib>|</lib>
    <lib>|</lib>
    <lib>|</lib>
```

### Actual 

Instead, the document looks like this:

```
    <lib>|</lib>
    <lib>|
    <lib>|
    <lib>|
```

**Comment by belaw** [comment]
If you use multi-cursor a lot, this is a deal breaker

**Comment by angelozerr** [comment]
> If you use multi-cursor a lot, this is a deal breaker

Sorry I just discovered this issue now :) I'm fixing.
