### ISSUE TITLE
XSD download fails in recent versions

### ISSUE THREAD

**Issue by SebastianPfliegel** [redhat-developer/vscode-xml#226]
I noticed that this extension no longer downloads external schemas for me. I'm behind a corporate proxy.

This is part of my settings.json:
`"xml.server.vmargs": "-Dhttp.proxyHost=PROXYHOST -Dhttp.proxyPort=3128 -Dhttps.proxyHost=PROXYHOST -Dhttps.proxyPort=3128"`

The last working extension version is `0.9.1` (downgrading does the trick for me). `0.10.0` and `0.10.1` are broken for me.

This is the error I get:
```
{
	"resource": "/c:/Users/pfliegel.sebastian/Projects/MDS/src/main/db/tables/changelog_20200220.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"severity": 8,
	"message": "Error while downloading 'http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.8.xsd' to C:\\Users\\pfliegel.sebastian\\.lsp4xml\\cache\\http\\www.liquibase.org\\xml\\ns\\dbchangelog\\dbchangelog-3.8.xsd.",
	"source": "XML",
	"startLineNumber": 3,
	"startColumn": 2,
	"endLineNumber": 3,
	"endColumn": 19
}
```

This issue is similar to #134, but I assume only the proxy settings were missing (as only more recent versions are affected by this bug).

**Comment by angelozerr** [comment]
@fbricon have you an idea about that?

**Comment by ilyakanevsky** [comment]
I have the same problem with the actual `0.10.1` version.

**Comment by SebastianPfliegel** [comment]
@ilyakanevsky downgrading to 0.9.1 fixes the problem for you, too?

**Comment by fbricon** [comment]
did you set your proxy settings in the user's settings.json or the current directory?

**Comment by SebastianPfliegel** [comment]
Hey @fbricon, I modified the user´s `settings.json`.

**Comment by fbricon** [comment]
Ok so it's not https://github.com/redhat-developer/vscode-xml/commit/dc03e74ebbc4e3b72401781f97e3fcdd1c0f1fc8#diff-d106f0e1914f2f6cbf79404a7f0c42b4 then. Maybe @snjeza can help troubleshooting proxy issues

**Comment by ilyakanevsky** [comment]
My settings:
`"xml.java.home": "C:\\Program Files\\Java\\jre1.8.0_231",`
`"xml.server.vmargs": "-Djava.net.useSystemProxies=false -Dhttp.proxyHost=127.0.0.1 -Dhttp.proxyPort=3130 -Dhttps.proxyHost=127.0.0.1 -Dhttps.proxyPort=3130",`

Now I use https://github.com/genotrance/px for proxy between applications and the real proxy. So I can see connections (initiated by each application) in the log.

> @ilyakanevsky downgrading to 0.9.1 fixes the problem for you, too?

I've just tried and answer is "Yes".

(But it downloads file %USERPROFILE%\.lsp4xml\cache\http\www.w3.org\2001\XMLSchema incorrectly, and after that cannot download some resources for rddl folder:
`Error while downloading 'http://www.w3.org/2001/rddl/xhtml-inlstruct-1.mod' to %USERPROFILE%\.lsp4xml\cache\http\www.w3.org\2001\rddl\xhtml-inlstruct-1.mod.`
`Error while downloading 'http://www.w3.org/2001/rddl/xhtml-blkphras-1.mod' to %USERPROFILE%\.lsp4xml\cache\http\www.w3.org\2001\rddl\xhtml-blkphras-1.mod.`
`Error while downloading 'http://www.w3.org/2001/rddl/xhtml-hypertext-1.mod' to %USERPROFILE%\.lsp4xml\cache\http\www.w3.org\2001\rddl\xhtml-hypertext-1.mod.`
)

If I use `0.10.0` or most recent [vscode-xml-0.11.0-4168.vsix](https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D), **there are no connections at all**! This is definitely a bug.

**Comment by ilyakanevsky** [comment]
> Ok so it's not [dc03e74#diff-d106f0e1914f2f6cbf79404a7f0c42b4](https://github.com/redhat-developer/vscode-xml/commit/dc03e74ebbc4e3b72401781f97e3fcdd1c0f1fc8#diff-d106f0e1914f2f6cbf79404a7f0c42b4) then.
I guess it is. Maybe the root of a problem is here: `IS_WORKSPACE_VMARGS_XML_ALLOWED`.

@snjeza, we need your help.

**Comment by SebastianPfliegel** [comment]
I tested the most recent CI build (https://download.jboss.org/jbosstools/vscode-xml/staging/vscode-xml-0.11.0-4173.vsix)

I can confirm that it is working again. Thanks!

**Comment by angelozerr** [comment]
> I can confirm that it is working again. Thanks!

Great! Thanks @SebastianPfliegel for your feedback.

Thanks @snjeza for your fix!

**Comment by ilyakanevsky** [comment]
> I can confirm that it is working again. Thanks!
I confirm too. Thanks for quick fix.

> But it downloads file %USERPROFILE%.lsp4xml\cache\http\www.w3.org\2001\XMLSchema incorrectly
This problem is still here. Fix: download manually http://www.w3.org/2001/XMLSchema**.xsd** and save it as %USERPROFILE%.lsp4xml\cache\http\www.w3.org\2001\XMLSchema (without extension).

**Comment by SebastianPfliegel** [comment]
@ilyakanevsky the extension uses a new directory:
`%USERPROFILE%\.lemminx\cache\`

**Comment by angelozerr** [comment]
> But it downloads file %USERPROFILE%.lsp4xml\cache\http\www.w3.org\2001\XMLSchema incorrectly,

We try and guess the best path where XML Schema/DTD must be downloaded to improve drasticly the performance in https://github.com/eclipse/lemminx/blob/9a4ef41513283d057581b743107e03115dae8434/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/utils/FilesUtils.java#L98

If anybody have some idea how fix that, any idea are welcome!

But you can customize this folder (if you have this kind problem) with the `xml.server.workDir`. I suggest you to do that.

> @ilyakanevsky the extension uses a new directory: %USERPROFILE%\.lemminx\cache\

Indeed my lsp4xml project has been moved to Eclipse.org and the new name is ....

Let's go for `LemMinX`! 

Hope you will like it.

**Comment by ilyakanevsky** [comment]
> @ilyakanevsky the extension uses a new directory:
> `%USERPROFILE%\.lemminx\cache\`
Yes, I've seen it.

> But you can customize this folder (if you have this kind problem) with the `xml.server.workDir`. I suggest you to do that.
Yes, I've done it:
`"xml.server.workDir": "~/.lsp4xml",`

**Comment by ilyakanevsky** [comment]
>We try and guess the best path where XML Schema/DTD must be downloaded

The problem I told above isn't about the path on the disk. It's about the URL. Correct URL for namespace `http://www.w3.org/2001/XMLSchema` is not http://www.w3.org/2001/XMLSchema but http://www.w3.org/2001/XMLSchema.xsd. It isn't related to current issue. Also it isn't a bug of plugin. But it will be great if plugin will have a fix for it and make a hidden redirect from http://www.w3.org/2001/XMLSchema to http://www.w3.org/2001/XMLSchema.xsd, transparent for user.
P.S. For other popular namespaces their names are the correct URLs. E.g.:
- XSD for namespace wsdl `http://schemas.xmlsoap.org/wsdl/` is located at http://schemas.xmlsoap.org/wsdl/;
- XSD for namespace soap `http://www.w3.org/2003/05/soap-envelope` is located at http://www.w3.org/2003/05/soap-envelope.
