### ISSUE TITLE
No end-tag completion on empty character

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#23]
Given:
```xml
<foo>
    <bar>
     // press ctrl-space here
</foo>
```

There's no completion until I press `<`. While I understand autocompletion is triggered on `<`, explicit completion requests (`ctrl+space`), should also return results from anywhere in the document. In this case, it should return `</bar>`.
The current behavior is very frustrating.

This may be a server-side issue (or not). cc @angelozerr

**Comment by angelozerr** [comment]
@fbricon it's a choice that I have done, because it's exactly the same behaviour of HTML Language Server.

BUT you can see if yout type html (without '<'), it provides completion. This completion comes from emmet. 

I would like to have the same behaviour than HTML Language Server, but it requires to improve emmet support to be based on XML Schema https://github.com/angelozerr/lsp4xml/issues/68

Hope you will be agree with my choice.

**Comment by fbricon** [comment]
@angelozerr sorry but I largely prefer the Eclipse behaviour which does:
1 - propose to close opened tag
2 - list all possible tags (i.e existing siblings)

![xml-complete](https://user-images.githubusercontent.com/148698/45300226-c45bfb00-b4db-11e8-8f12-d19dab2da315.gif)


While 2 is nice to have, it may be complicated to implement as it'd conflict with some xsd/dtd constraints.

**Comment by angelozerr** [comment]
@fbricon I agree with you, but when emmet will be available we will have the same features than Eclipse.

> While 2 is nice to have, it may be complicated to implement as it'd conflict with some xsd/dtd constraints.

No, I have already though about that. Emmet extension uses the XMLDocument and we know the XML Schema or DTD which is used. After that we just only generate a JS structure from the XML Schema or DTD (by using ContentModelManager) waited by emmet.

If you wish I can work on this issue?

**Comment by fbricon** [comment]
those completions on empty char should not be dependent on emmet support as they're unrelated

**Comment by angelozerr** [comment]
> those completions on empty char should not be dependent on emmet support as they're unrelated

HTML Language Server does that to avoid having duplicated compeltion items (from emmet and from emty character), but if you wish to have this feature, please create an issue for lsp4xml. Thanks!

**Comment by fbricon** [comment]
So this one is now partially complete. Completion on empty space works for adding new tag now, but not for closing.

**Comment by angelozerr** [comment]
> Completion on empty space works for adding new tag now, but not for closing.

I'm working on this issue...

**Comment by angelozerr** [comment]
@fbricon please give me feedback, it should be fixed in https://github.com/angelozerr/lsp4xml/issues/112
