### ISSUE TITLE
DTD inclusion does not work

### ISSUE THREAD

**Issue by ph777** [redhat-developer/vscode-xml#231]
Hello,

thanks for you extension which is very useful for us. We use its support for understanding DTD definition which is helpful when composing XML documents.

However, we've come across a problem with DTD inclusion. If a DTD file references another DTD file, all declarations from the referenced DTD are like invisible to VSCode, therefore it marks errors on elements/attributes/entities defined there. 

The inclusion seems correct, which was verified by:

```bash
xmllint --loaddtd --noent --valid file.xml
```

XML file references a DTD file `extended.dtd`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root-element SYSTEM "./extended.dtd" []>
<root-element><!-- defined in base.dtd, but marked with MSG_ELEMENT_NOT_DECLARED error -->
&foo; <!-- defined in base.dtd, but this is marked with EntityNotDeclared -->
&ok; <!-- defined in extended.dtd, without error -->
...
</root-element>
```

File `extended.dtd` references a DTD file `base.dtd`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!ENTITY % base SYSTEM "./base.dtd">
%base;
<!-- adds some elements and entities -->
<!ENTITY ok "OK">
```

File `base.dtd` is a DTD that declares the structural elements like `root-element` and entities like `foo`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT root-element (#PCDATA)>
<!ENTITY foo "bar">
```

We'd expect `<root-element>` and `&foo;` to be recognized as declared element/entity. But they are marked with error instead.

Are we doing something wrong? Is there a workaround or can it be fixed? 

Thanks.

**Comment by ph777** [comment]
There is a workaround as follows. Still I think the behaviour described above is an error.

Include `base.dtd` and `extended.dtd` in your XML file.

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root-element SYSTEM "./base.dtd" [
<!ENTITY % extended SYSTEM "./extended.dtd">
%extended;
]>
<root-element>
&foo;
&ok;
...
</root-element>
```

File `extended.dtd` does *NOT* reference a DTD file `base.dtd`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!-- adds some elements and entities -->
<!ENTITY ok "OK">
```

File `base.dtd` is without change:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT root-element (#PCDATA)>
<!ENTITY foo "bar">
```

Hope it helps someone.

**Comment by angelozerr** [comment]
Have you tried with this settings?

`xml.validation.resolveExternalEntities: true`

**Comment by ph777** [comment]
Thanks for the tip. This works like a charm.
