### ISSUE TITLE
XML entities and intellisense

### ISSUE THREAD

**Issue by ph777** [redhat-developer/vscode-xml#232]
It would be nice if entities declared in XML or imported from a DTD were offered by intellisense after writing writing ampersand character in XML attributes or in PCDATA sections. 

Writing `&f` could offer all entities starting with `f`. After one is selected it could also close the entity reference with a semicolon.

Would it be possible? Thanks.

**Comment by angelozerr** [comment]
It the same issue than https://github.com/eclipse/lemminx/issues/520

**Comment by ph777** [comment]
Sorry, I didn't notice that one.
