### ISSUE TITLE
Enumeration documentation is not displayed

### ISSUE THREAD

**Issue by MAHTasklet** [redhat-developer/vscode-xml#233]
This is a great plug-in thanks for that.

I have a minor issue, that annotation/documentation is not displayed for xs:enumeration items, either when hovering over items in the selection list or when hovering the value after selecting.
In the example below only the documentation from the xs:simpleType is displayed.
I have also noticed, that if the top level element (xs:simpleType) does not have documentation, then the documentation for the last enumeration is used.

I have tested in Visual Studio that the documentation is written correctly, and displayed when hovering.

Let me know, if I need to do something different, or test a fix.

Sorry about the formatting, I have not been able to make it look better.
```xml
<xs:simpleType name="PrimaryInputMethodType">
  <xs:annotation>
    <xs:documentation>The primary input method for the step. The step will use the Control as default but can be modified to e.g. ask the user to scan</xs:documentation>
  </xs:annotation>
  <xs:restriction base="xs:string">
    <xs:enumeration value="Control" >
      <xs:annotation>
        <xs:documentation>The normal control will be shown.</xs:documentation>
      </xs:annotation>
    </xs:enumeration>
    <xs:enumeration value="Scan" >
      <xs:annotation>
        <xs:documentation>The primary input will be scan and the step element can act accordingly e.g. the InputLineType.Text will show a SCAN icon with the possibility to manually enter the value.</xs:documentation>
      </xs:annotation>
    </xs:enumeration>
    <xs:enumeration value="ScanOnly" >
      <xs:annotation>
        <xs:documentation>
          The 'ScanOnly' differs from the 'Scan' in the way that the user cannot enter a value manually. The SCAN icon is displayed but it will not show the edit field.
          This is only applicable for InputLineType.Text.
        </xs:documentation>
      </xs:annotation>
    </xs:enumeration>
  </xs:restriction>
</xs:simpleType>
```

Best regards
Morten

**Comment by angelozerr** [comment]
> This is a great plug-in thanks for that.

Glad it pleases you!

Could you give us a XML sample and full XML Schema which causes the problem, it will help us to understand quickly the missing feature and we will able to use your usecase for writing tests.

**Comment by MAHTasklet** [comment]
Yes.
Let me create one and post it here.

**Comment by MAHTasklet** [comment]
Here goes:
Notice that when using the extension and hovering over the type attribute or any of the values, the last documentation is displayed. In Visual Studio hovering over the type attribute displays the documentation added for the type, and hovering over the different values displays their documentation.

Hope this helps. If not, let me know.

[SchemaTest.zip](https://github.com/redhat-developer/vscode-xml/files/4375359/SchemaTest.zip)

**Comment by angelozerr** [comment]
@MAHTasklet thanks for your zip. I try to understand the problem, if I hover `AX365 `

![image](https://user-images.githubusercontent.com/1932211/77429311-c180dc80-6dd9-11ea-9a08-746361f254cd.png)

but it should display `Used when connecting to Dynamics AX 365 for Finance and Operations.`

Is this problem that you mention?

**Comment by MAHTasklet** [comment]
Yes.
That is the problem. Also, if you hover over the type= attribute, then the same documentation you mention is displayed which should be "The type of Backend ERP system."

**Comment by angelozerr** [comment]
> In Visual Studio hovering over the type attribute displays the documentation added for the type, and hovering over the different values displays their documentation.

Could you add a screenshot please.

**Comment by MAHTasklet** [comment]
The mouse is not visible but hovering the type= part underlined here.
![image](https://user-images.githubusercontent.com/36441243/77432585-8fbe4480-6dde-11ea-8c90-cded3bd339e0.png)

**Comment by angelozerr** [comment]
Ok and when you hover the NAV value, you see the document of the NAV (or merged documentation of the type and NAV documentation?)

**Comment by MAHTasklet** [comment]
No. It's the same value if I hover anything. regarding the type= attribute. That includes the actual attribute name (type=) or any entered values (AX, NAV, D365FO). Oddly enough, mine does display a different value that what you display, namely "Used when connecting to Dynamics AX 365 for Finance and Operations". However, always that value.

I just discovered that if I close VS Code, then whatever part of the type="<enumeration>" that is hovered, is the value that will always be displayed when hovering, even type attributes on different elements.

**Comment by MAHTasklet** [comment]
To recreate:
Close VS Code
Open VS Code
Hover the D365FO element.
Notice that the correct value is displayed.
Now hover the AX element.
Notice that the documentation for the D365FO is displayed.
Now hover the type= element.
Notice that the documentation for the D365FO is displayed.

Now repeat all steps, and choose another starting point e.g. hovering the type= attribute, and notice that whatever you hover documentation of the initial element is always displayed.

**Comment by angelozerr** [comment]
Ok if I understand correctly the problem, it's a cache problem. It seems hover is working the first time (if you hover the type attribute the first time, it works, if you hover AX value the first time it works, etc), but problem occurs for the second hover which is different from the first.

Is it that, or is there another problem?

I can reproduce the problem and I'm creating a PR for that.

**Comment by angelozerr** [comment]
@MAHTasklet here the result of https://github.com/eclipse/lemminx/pull/623

![XMLHoverDemo](https://user-images.githubusercontent.com/1932211/77454775-492a1380-6df9-11ea-9d80-36f26f02e844.gif)

Is it OK for you?

**Comment by MAHTasklet** [comment]
That looks awesome.
Thank you very much for the quick fix.
