### ISSUE TITLE
XML entities declared in a DTD are marked undeclared after XML file change

### ISSUE THREAD

**Issue by ph777** [redhat-developer/vscode-xml#234]
I have a DTD file `base.dtd` that declares an XML entity `external`:

```xml
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT root-element (#PCDATA)>
<!ENTITY external "EXTERNALLY DECLARED ENTITY">
```

I have an XML file `file.xml` that references the DTD file and declares an XML entity `local`. To make the case clear it also uses an undeclared entity `undeclared`.

```xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE root-element SYSTEM "./base.dtd" [
<!ENTITY local "LOCALLY DECLARED ENTITY">
]>
<root-element>
&local;
&external;
&undeclared;
</root-element>
```

Now, if I open `file.xml` in VSCode, the DTD is recognized and the `&undeclared;` is correctly marked with an `EntityNotDeclared` error.

However, once I modify `file.xml`, e.g. by putting a new line or space anywhere (any safe place that does not break well-formdness of XML, e.g. after `<root-element>` opening tag), the `&external;` entity gets marked with an `EntityNotDeclared` error, which is NOT correct.

Is it possible to fix it? This error is really annoying in large XML files with a lot of externally declared XML entities. Once you modify your XML it gets red all over and you easily miss your real errors in XML. Or is this a lemminx problem?

Thanks

**Comment by ph777** [comment]
I need to either reload VSCode or save `file.xml`, close it and reopen again to have externally declared XML entities evaluated correctly.

**Comment by angelozerr** [comment]
DTD entity validation is indeed not very stable, we need to improve it. I need to investigate the problem.

**Comment by ph777** [comment]
Thanks, that would be great!

**Comment by angelozerr** [comment]
Thanks @ph777 for your detailed explanation.

I can reproduce it and the bug is not trivial. It comes from the custom LemMinx cache of DTD which is used to avoid parsing referenced DTD grammar each time you type something in the XML editor.

But I have some ideas to fix this problem. I will ping you as soon as I will find a fix.

**Comment by ph777** [comment]
Great news! It sounds promising.

Dne čt 26. bře 2020 10:43 uživatel Angelo <notifications@github.com> napsal:

**Comment by angelozerr** [comment]
@ph777 I create a PR to fix this issue https://github.com/eclipse/lemminx/pull/636, here a demo:

![EntityDemo](https://user-images.githubusercontent.com/1932211/79610001-fd1c7700-80f7-11ea-8587-ace081235d0a.gif)

**Comment by ph777** [comment]
Great news! Thanks!

When can we expect the 0.12.0 version to be released?

**Comment by angelozerr** [comment]
> When can we expect the 0.12.0 version to be released?

Perhaps in 3 weeks. But you can install the current version vsix at
https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D

It should be good if you could do that to give us feedback before the release. Thanks.
