### ISSUE TITLE
Extension not detected as a formatter ?

### ISSUE THREAD

**Issue by pc-robelbois** [redhat-developer/vscode-xml#239]
Hi
App installed and VScode restarted, however the addon does not seems to be available to format XML files.

![image](https://user-images.githubusercontent.com/50719398/79620903-75d7ff00-8109-11ea-8907-141ab39d823f.png)
![image](https://user-images.githubusercontent.com/50719398/79620911-7d97a380-8109-11ea-800f-71e740aa5b8c.png)

Could you please advice ?

**Comment by angelozerr** [comment]
Have you checked https://github.com/redhat-developer/vscode-xml#requirements

**Comment by pc-robelbois** [comment]
@angelozerr This was indeed a configuration issue, I had it solved following instructions at #690 .
