### ISSUE TITLE
Improve formatting of Processing Instructions

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-xml#240]
The formatter formats an XML declaration as follows:
````xml
<?xml version="1.0" encoding="UTF-8" ?>
````

But tools such as Maven generate XML files with an XML declaration as follows (i.e. without a trailing space before the closing tag):
````xml
<?xml version="1.0" encoding="UTF-8"?>
````

This is particularly annoying, because the XML declaration is constantly changed: to version B each time Maven rewrites the XML file (e.g. when doing a release), and then again to version A when the formatter formats the file.

So I think the best option is to format XML declarations as follows:
* if there's already trailing whitespace before the closing tag, collapse it to a single space character
* else, don't add any whitespace

**Comment by angelozerr** [comment]
I'm fine with this suggestion. @fbricon what do you think?

**Comment by fbricon** [comment]
how about `xml.format.spaceAfterAttribute` or `xml.format.spaceAfterLastAttribute`?

**Comment by angelozerr** [comment]
After discussion, we should never generate a space before the end of processing instruction. If some user will need that, we will introduce a new settings for that like @fbricon suggested. But for the moment keep simply and don't generate this extra space.

**Comment by anthonyvdotbe** [comment]
Sounds good to me, thanks.

**Comment by angelozerr** [comment]
Fixed with https://github.com/eclipse/lemminx/pull/670
