### ISSUE TITLE
Document symbols limit warning keeps popping up on each change

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#243]
Set "xml.symbols.maxItemsComputed": 3, for instance, open a pom.xml, on every keystroke, the limit warning pops up:
<img width="543" alt="Screen Shot 2020-04-21 at 11 14 54 AM" src="https://user-images.githubusercontent.com/148698/79848454-62ef5400-83c1-11ea-8f6f-3bb5f46e437e.png">

**Comment by angelozerr** [comment]
Indeed it misses the JSON part https://github.com/microsoft/vscode/blob/9f709d170b06e991502153f281ec3c012add2e42/extensions/json-language-features/server/src/jsonServerMain.ts#L204 which manages a cache of warning.
