### ISSUE TITLE
How to validate a XML file against a xsd?

### ISSUE THREAD

**Issue by gannebamm** [redhat-developer/vscode-xml#245]
I would like to trigger XSD validation but am unable to find a way to do so. Could someone please explain the procedure to me?
Thanks

**Comment by angelozerr** [comment]
I don't know what is your skill with XML and XML Schema (sorry if you know what I will try to explain you), but the basic idea is to write a XML file and a XSD file and associates the XML file with XSD. With vscode-xml you can associate a XML  file with:

 * file association (not standard)
 * schemaLocation or noNamespaceSchemaLocation
 * XML catalog (with schemaLocation ) if your XSD file is not relative to your XML file

I suggest for instance you start with https://www.w3schools.com/xml/schema_example.asp by using noNamespaceSchemaLocation

Good luck

**Comment by gannebamm** [comment]
Thanks. I had to properly define the xsi locations and now it works

**Comment by angelozerr** [comment]
@gabemontero I think last version of vscode-xml should help you https://developers.redhat.com/blog/2020/07/08/improved-xml-grammar-binding-and-more-in-red-hat-vs-code-xml-extension-0-13-0/

**Comment by gabemontero** [comment]
> @gabemontero I think last version of vscode-xml should help you https://developers.redhat.com/blog/2020/07/08/improved-xml-grammar-binding-and-more-in-red-hat-vs-code-xml-extension-0-13-0/

think you tagged the wrong person here @angelozerr

**Comment by angelozerr** [comment]
@gannebamm I think last version of vscode-xml should help you https://developers.redhat.com/blog/2020/07/08/improved-xml-grammar-binding-and-more-in-red-hat-vs-code-xml-extension-0-13-0/

> think you tagged the wrong person here @angelozerr

ooops sorry @gabemontero and thanks for your feedback.
