### ISSUE TITLE
Preserve line breaks when formatting

### ISSUE THREAD

**Issue by pc-robelbois** [redhat-developer/vscode-xml#247]
Hi

**Context**
A big XML file with long lines, line breaks are used to keep lines visually undestandable (and max 120 chars). Using the formatter, line breaks are removed resulting in extremely long lines (300 chars+). In the other hand, a line break per attribute is not a solution.

**Question**
How to prevent line breaks refactoring during formatting ? -> "Keep my line breaks"

Thanks

**Comment by angelozerr** [comment]
@pc-robelbois could you attach a simple XML file which causes your problem please.

**Comment by pc-robelbois** [comment]
@angelozerr Here is a minimal sample.


Before
```
<a>
    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" />

    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" />
    
    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" />
    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" 
        attribute="123456789" attribute="123456789" attribute="123456789" />
</a>
```

After formatting
```
<a>
    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" />

    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" />

    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" />
    <l1 attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" attribute="123456789" />
</a>
```

**Comment by fbricon** [comment]
@pc-robelbois what editor/IDE do you usually use to format your XML documents while preserving line breaks between attributes?

**Comment by pc-robelbois** [comment]
> @pc-robelbois what editor/IDE do you usually use to format your XML documents while preserving line breaks between attributes?

Previously, theses files were edited as raw text files (not formatter).

**Comment by fbricon** [comment]
@angelozerr FYI, here are the Intellij IDEA settings related to word wrapping in XML docs:
Adding a hard wrap limit might also help getting consistent formatting, in @pc-robelbois's case:
<img width="394" alt="Screen Shot 2020-04-24 at 1 06 16 PM" src="https://user-images.githubusercontent.com/148698/80206432-91bd3280-862c-11ea-9da9-ea6017a36587.png">

**Comment by angelozerr** [comment]
@fbricon HTML Language Server have 

`"html.format.wrapLineLength": 120,` 

I think it's a setting which could fix this issue? 

@fbricon @pc-robelbois what do you think ?

**Comment by pc-robelbois** [comment]
@angelozerr I do identify two different features. 

- I want to preserve the line breaks of existing lines. 
- I want to split the line so that max line length < X.

While both are imo required, my request is about the first one. Your proposal is about the second one.

**Comment by fbricon** [comment]
indeed, that why I said it might also help.

**Comment by fbricon** [comment]
Let's add "xml.format.preserveLineBreaks":true, that would apply for non empty lines.
For empty lines, there's already "xml.format.preservedNewlines": 0-4,

**Comment by xorye** [comment]
Hi @pc-robelbois, I made a PR for this issue: https://github.com/eclipse/lemminx/pull/772 that preserves the line breaks that exist beside attributes, instead of preserving all line breaks of all non-empty lines.

Here is a demo:
![demo](https://raw.githubusercontent.com/xorye/gifs/54112d60974b60ee78267e80c8e3b48ff1d938f9/pr/format_demo.gif?token=AE3CR5P42L3QNUTFSZMAQ3C65EXKI)

The idea was behind it is that in some cases, it may be beneficial to remove newlines while keeping some.

For example, in this case:
```
<li attr="value" attr="value"
    attr="value" attr="value"></li


>
```
it would be nice to have it formatted to:
```
<li attr="value" attr="value"
    attr="value" attr="value"></li>
```

and 
```
<li attr="value" attr="value"
    attr="value" attr
=

"value"></li>
```
formatted to
```
<li attr="value" attr="value"
    attr="value" attr="value"></li>
```

How does this sound?

**Comment by pc-robelbois** [comment]
> Hi @pc-robelbois, I made a PR for this issue: [eclipse/lemminx#772](https://github.com/eclipse/lemminx/pull/772) that preserves the line breaks that exist beside attributes, instead of preserving all line breaks of all non-empty lines.
> 
> Here is a demo:
> ![demo](https://raw.githubusercontent.com/xorye/gifs/54112d60974b60ee78267e80c8e3b48ff1d938f9/pr/format_demo.gif?token=AE3CR5P42L3QNUTFSZMAQ3C65EXKI)
> 
> The idea was behind it is that in some cases, it may be beneficial to remove newlines while keeping some.
> 
> For example, in this case:
> 
> ```
> <li attr="value" attr="value"
>     attr="value" attr="value"></li
> 
> 
> >
> ```
> 
> it would be nice to have it formatted to:
> 
> ```
> <li attr="value" attr="value"
>     attr="value" attr="value"></li>
> ```
> 
> and
> 
> ```
> <li attr="value" attr="value"
>     attr="value" attr
> =
> 
> "value"></li>
> ```
> 
> formatted to
> 
> ```
> <li attr="value" attr="value"
>     attr="value" attr="value"></li>
> ```
> 
> How does this sound?

This sounds amazing. Yes formatting line breaks in some cases such as described seems acceptable.

**Comment by xorye** [comment]
Great, thank you for the feedback.

I realize that the gif is a bit misleading since the attribute names are all aligned since the tab size is 4 spaces.

PR https://github.com/eclipse/lemminx/pull/772 will indent the attribute names depending on the element's indentation and will not align attribute names for the moment. I created a new issue for attribute aligning here: https://github.com/redhat-developer/vscode-xml/issues/272

**Comment by angelozerr** [comment]
Can we close this issue?

**Comment by fbricon** [comment]
Closing as we provided xml.format.preserveAttributeLineBreaks
