### ISSUE TITLE
Add LemMinx extensions via vscode user settings

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#251]
LemMinx is extensible to manage custom completion, validation, etc. https://github.com/eclipse/lemminx-maven is a good sample of extension which provides support for maven.

To use this extension, it requires to create a vscode extension (eg: https://github.com/angelozerr/vscode-xml-maven)

This issue is to provide a new xml settings like `xml.extension.jars` which is an array of String which defines paths from LemMinx JAR extensions. to use when classpath is created

**Comment by AObuchow** [comment]
+1, this is the VSCode equivalent of the [lemminxExtension](https://github.com/eclipse/wildwebdeveloper/blob/master/org.eclipse.wildwebdeveloper.xml/schema/lemminxExtension.exsd) in Wild Web Developer (although simpler for non-VSCode developers to use).

**Comment by AObuchow** [comment]
@angelozerr how hard do you think it would be for someone who has never wrote (but has read a lot of) TypeScript :) Maybe I should try to fix this bug in my spare time.

**Comment by angelozerr** [comment]
I think it's not a big deal. The idea is to

1. add a new method which read configuration :

`let classPathFromSettings = workspace.getConfiguration("xml.server").get("extensions");`

like 

https://github.com/redhat-developer/vscode-xml/blob/e01d3e0a1754de01c63a873a03b332a61158c3e6/src/settings.ts#L87

2. call this method in 

https://github.com/redhat-developer/vscode-xml/blob/e01d3e0a1754de01c63a873a03b332a61158c3e6/src/javaServerStarter.ts#L66

3. declare the settings in package.json like https://github.com/redhat-developer/vscode-xml/blob/e01d3e0a1754de01c63a873a03b332a61158c3e6/package.json#L270

@fbricon for the settings name I suggest `xml.server.extensions` which is an array of JAR, what do you think about that ?

**Comment by angelozerr** [comment]
@AObuchow is there any chance that you work on this issue? I think it could be a nice feature to test quickly the LemMinx maven support inside vscode.

**Comment by AObuchow** [comment]
Wow I was just thinking about this yesterday night, good timing @angelozerr ;)

I’ll see with my team how much of a priority this is. It might be that I’ll work on it in my spare time. I’m about to release my first Eclipse plugin on the marketplace (probably tomorrow) but after that I want to get this done :)
