### ISSUE TITLE
Don't return hover when there's no documentation

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#258]
Empty hover with only link to source looks weird.

<img width="232" alt="Screen Shot 2020-05-12 at 6 52 33 PM" src="https://user-images.githubusercontent.com/148698/81725446-21187180-9486-11ea-9f1f-1ca1f10a1ec2.png">

Might as well not return anything

**Comment by angelozerr** [comment]
Source information can be interesting I think, no?

**Comment by fbricon** [comment]
I feel that adds unnecessary bloat. I'd say hide it if no visible documentation to display. If someone requests we display links to sources when hovering, even without doc, then we can add a new preference.
