### ISSUE TITLE
Blog post for 0.12.0 release

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#268]
See

- https://github.com/eclipse/lemminx/milestone/15
- https://github.com/redhat-developer/vscode-xml/milestone/15

**Comment by xorye** [comment]
@datho7561 here are some previous blog posts that we've done:
https://quarkus.io/blog/vscode-quarkus-1.4.0/
https://quarkus.io/blog/vscode-quarkus-1.3.0/
https://developers.redhat.com/blog/2019/11/21/new-features-in-quarkus-tools-for-visual-studio-code-1-2-0/
https://developers.redhat.com/blog/2020/03/27/red-hat-xml-language-server-becomes-lemminx-bringing-new-release-and-updated-vs-code-xml-extension/

As for the video, I'll see if I could put together something with the clips we already have

**Comment by datho7561** [comment]
[The blog post](https://developers.redhat.com/blog/2020/07/02/improved-schema-binding-and-more-in-red-hat-xml-extension-for-vs-code-0-12-0-and-lemminx/) was posted today.

**Comment by angelozerr** [comment]
@BalduinLandolt please read https://developers.redhat.com/blog/2020/07/02/improved-schema-binding-and-more-in-red-hat-xml-extension-for-vs-code-0-12-0-and-lemminx/ and see the Note of the conclusion

**Comment by BalduinLandolt** [comment]
> 
> 
> @BalduinLandolt please read https://developers.redhat.com/blog/2020/07/02/improved-schema-binding-and-more-in-red-hat-xml-extension-for-vs-code-0-12-0-and-lemminx/ and see the Note of the conclusion

Cool, thanks for pointing that out to me and thanks for the credit! :)
