### ISSUE TITLE
Align XML attributes when formatting

### ISSUE THREAD

**Issue by xorye** [redhat-developer/vscode-xml#272]
It would be nice if there was an option to align the beginning of attribute names if the attributes exist in different lines when formatting. 

Currently by default, when formatting this XML:
```
<a attr="value"
   attr="value">
    <b></b>
</a>
```

The resulting XML is:
```
<a attr="value" attr="value">
    <b></b>
</a>
```

Ideally, after formatting, the initial XML should stay as is.

**Comment by xorye** [comment]
In this case:
```
<a attr="value"
           attr="value">
    <b></b>
</a>
```

Since the attributes are in separate lines, it should be aligned after formatting:
```
<a attr="value"
   attr="value">
    <b></b>
</a>
```

**Comment by BinToss** [comment]
This is EditorConfig Rule `xml_pi_attributes_indent` as specified by ReSharper.
Possible values are `single_indent`, `double_indent`, and `align_by_first_attribute`.

See https://www.jetbrains.com/help/resharper/EditorConfig_XML_XmlCodeStylePageSchema.html#resharper_xml_pi_attributes_indent

**Comment by angelozerr** [comment]
@JessicaJHee I think we can close this issue since the provided ne formatter, right?

**Comment by angelozerr** [comment]
@BinToss please read https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatsplitattributes

**Comment by BinToss** [comment]
The provided example indicates the spaces/indentation of the inner element(s) are formatted, but does not state it also affects tags' attributes.

If this format rule *does* affect attributes, then the documentation could be clarified.

**Comment by BinToss** [comment]
@angelozerr The documentation's example indicates the spaces/indentation of the inner element(s) are formatted, but does not state it also affects tags' attributes.

If this format rule *does* affect attributes, then the documentation could be clarified.

**Comment by JessicaJHee** [comment]
The `xml.format.splitAttributes` setting applies to attributes and not inner elements.
Currently, when this setting is set to true. the following is formatted from 
```
<project a="1" b="2" c="3"></project>
```

to:

```
<project
    a="1"
    b="2"
    c="3"></project>
```

To address the use case in this [comment](https://github.com/redhat-developer/vscode-xml/issues/272#issuecomment-641598793), we can update this settings with a new option: `preserve` (currently `xml.format.splitAttributes` = true), `split-new-line` (currently `xml.format.splitAttributes` = false), and `align-with-first-attr`.

The new setting would format to:

```
<project a="1"
         b="2"
         c="3"></project>
```

What do you think about this solution @BinToss?

**Comment by BinToss** [comment]
That looks perfect!
That solution may also resolve #631...of which this issue is probably a duplicate.

On the subject of editorconfig files and rules, it seems there's been community interest in this extension supporting them, but that's a different issue with a different solution. A quick search in Lemminx's Issues returned no results.
- #296
- #850
- #904

**Comment by angelozerr** [comment]
@BinToss for your information, @JessicaJHee have implemented the format settings of this issue. See doc at https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatsplitattributes

It would be nice if tomorrow you could install prrelease https://github.com/redhat-developer/vscode-xml#contributing and give us feedback. Thanks!

**Comment by angelozerr** [comment]
@BinToss the prerelease is avaiable, plus play with it and give us feedback. Thanks!

**Comment by BinToss** [comment]
Roger that. I should have time to try it out this weekend.

**Comment by BinToss** [comment]
Excellent work!

The only think people may complain about is when the formatter can't handle a file with "mixed" formatting—that is, they desire both `preserve` and `alignWithFirstAttr` in the same file. Or they may want `preserve` without affecting alignment.
However, I'd say this request is resolved.

**Comment by angelozerr** [comment]
Thanks @BinToss for your feedback.

Thanks so much again @JessicaJHee for your great work!
