### ISSUE TITLE
"xml.preferences.showSchemaDocumentationType": "none" still shows a popup on hover

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#276]
When setting `"xml.preferences.showSchemaDocumentationType": "none"`, there's still an empty hover with a link to the source, so we're back to https://github.com/redhat-developer/vscode-xml/issues/258:
<img width="364" alt="Screen Shot 2020-06-15 at 9 55 42 AM" src="https://user-images.githubusercontent.com/148698/84631961-85e44300-aeee-11ea-91a9-939f14b1172f.png">

**Comment by angelozerr** [comment]
That's strange, I cannot reproduce it. Could you share your pom.xml please.

**Comment by fbricon** [comment]
My bad, I was checking against a stale 0.12.0 build. Latest release works as expected.
