### ISSUE TITLE
Changelog for 0.13.0

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#281]

**Comment by datho7561** [comment]
I have drafted PRs for the change logs for LemMinX and vscode-xml:

 * [https://github.com/eclipse/lemminx/pull/810](https://github.com/eclipse/lemminx/pull/810)
 * [https://github.com/redhat-developer/vscode-xml/pull/282](https://github.com/redhat-developer/vscode-xml/pull/282)

Please let me know if I missed any features or bug fixes.
