### ISSUE TITLE
Reloading remote schema

### ISSUE THREAD

**Issue by Timtower** [redhat-developer/vscode-xml#284]
I am using hosted schema's (localhost python server) but I am having issues with reloading the schema's.

Is it possible to tell me how I can do that?
And if it is not possible yet: would it be possible to add such functionality?

**Comment by fbricon** [comment]
There's currently no way to re-download the schema from vscode-xml directly. You need to manually delete it under the ~/.lemminx/ directory

We could either expose a command to force a remote resource check, and/or check if schema's ETag changed, with a HEAD request, every time an xml doc is opened (or the server starts)

**Comment by Timtower** [comment]
That cache location is a big help already, gives me a manual way of forcing an update.

Forced check would be nice, self-updating even better (no idea how to handle that on my server but that is my issue)

Do you know what the cache time is for those files? Or do they get pulled once and never again?

**Comment by fbricon** [comment]
there's no eviction policy, so pulled only once

**Comment by Timtower** [comment]
That is good to know.
Time to write my own updater for them for now.

If there are improvements being made to this then I would highly appreciate that.

**Comment by angelozerr** [comment]
@TimMoran is your python server manages `get last modified`  of your XSD file?

**Comment by Timtower** [comment]
@angelozerr Wrong tag there.
And my python server does not do that yet, just always sends the file.
Made a custom extension to erase the cache and reload the window to counter this issue.

**Comment by angelozerr** [comment]
> Made a custom extension to erase the cache and reload the window to counter this issue.

Do you think you could contribute to vscode-xml with your feature?

**Comment by Timtower** [comment]
> > Made a custom extension to erase the cache and reload the window to counter this issue.
> 
> Do you think you could contribute to vscode-xml with your feature?

Maybe, right now it is just a full delete, regardless of content.
Need to clean that up first.

**Comment by angelozerr** [comment]
@Timtower I will work on this issue. The idea is to provide a command which revalidate the given XML file, which means:

 * detect XSD, DTD files referenced by the XML
 * redownload those XSD, DTD
 * retrigger the validation

**Comment by Timtower** [comment]
@angelozerr I had it just delete the entire cache. We often have updates for the entire server on ours side.

**Comment by angelozerr** [comment]
@Timtower I'm working on this issue, please see mode at https://github.com/redhat-developer/vscode-xml/pull/343#issuecomment-709120128

**Comment by angelozerr** [comment]
@Timtower if you install last vsix from https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D

you should have XML commands https://github.com/redhat-developer/vscode-xml/blob/master/docs/Commands.md to evict cache. Any feedback are welcome!

**Comment by Timtower** [comment]
Works great so far!

**Comment by angelozerr** [comment]
> Works great so far!

Thanks for your feedback, and glad it works for you.
