### ISSUE TITLE
Error prompt Invalid path for setting 'xml.catalogs'

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#289]
Since some time I get the error message 

    Invalid path for setting 'xml.catalogs': 'file:///Users/patrick/work/software/publisher/schema/catalog-schema-de.xml'

Why do I get this error message?

<img width="543" alt="message" src="https://user-images.githubusercontent.com/209434/87171838-8bf1f780-c2d3-11ea-81ee-4d56b42b46b3.png">

But everything seems to work ok. The setting `xml.catalogs` is as follows:

```
Xml: Catalogs
Array of XML Catalogs.
file:///Users/patrick/work/software/publisher/schema/catalog-schema-de.xml
```

<img width="916" alt="setting" src="https://user-images.githubusercontent.com/209434/87172036-df644580-c2d3-11ea-94d9-f5238acc8556.png">

The settings.json contains this line:

```json
   "xml.catalogs": [
        "file:///Users/patrick/work/software/publisher/schema/catalog-schema-de.xml"
    ],
```

The file exists and contains a catalog. 

```xml
cat /Users/patrick/work/software/publisher/schema/catalog-schema-de.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE catalog PUBLIC "-//OASIS//DTD XML Catalogs V1.1//EN" "http://www.oasis-open.org/committees/entity/release/1.1/catalog.dtd">
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
    <uri name="urn:speedata.de:2009/publisher/en" uri="layoutschema-de.xsd"/>
</catalog>
```

I believe I use version  `v0.13.0` of the XML Language Support by Red Hat

**Comment by angelozerr** [comment]
If you try to remove `file://` or `file:///` is it working better?

**Comment by pgundlach** [comment]
Yes, that fixes it. 

I thought I had it right because XML auto completion worked.

Thank you and sorry for the noise.

**Comment by angelozerr** [comment]
> Yes, that fixes it.

Ok thanks for the feedback.

> I thought I had it right because XML auto completion worked.

And you are right, it's a bug that we must fix.

Thank you and sorry for the noise.
