### ISSUE TITLE
How to set catalog prefer as public in vscode setting? 

### ISSUE THREAD

**Issue by mingxi** [redhat-developer/vscode-xml#295]
**Description**
Is possible to set catalog prefer as public from vscode setting?
It seems that vscode-xml always set catalog as system id.
As far as I know, I can set catalog using CatalogManager.properties in java code.
I did not find the corresponding setting(prefer=public) in vscode-xml.
The below code is CatalogManager.properties which used to validate xml in java code.
e.g.
```
catalogs=C:\\DITA-OT\\catalog-dita.xml
relative-catalogs=yes
#verbosity=99
prefer=public
static-catalog=yes
allow-oasis-xml-catalog-pi=yes
```

**Reference**
https://xerces.apache.org/xml-commons/components/apidocs/resolver/org/apache/xml/resolver/CatalogManager.html

**Comment by angelozerr** [comment]
This feature is indeed not supported. To support it, XML Language Server (lemMinx) must support it.


https://xerces.apache.org/xerces2-j/javadocs/xerces2/org/apache/xerces/util/XMLCatalogResolver.html#XMLCatalogResolver(java.lang.String[],%20boolean)
https://github.com/eclipse/lemminx/blob/b1407bb52ce3ff6cd350a98b9c5aa8ea3392df0e/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/extensions/contentmodel/uriresolver/XMLCatalogResolverExtension.java#L121

**Comment by mingxi** [comment]
@angelozerr Got it, thanks for your reply.

**Comment by fbricon** [comment]
> I wonder if we should change this settings with `xml.catalog.files` to have that:
> 
> ```json
> {
> 	"xml": {
> 		"catalog": {
> 			"preferPublic": true,
> 			"useLiteralSystemId": true, 
> 			"files": [
> 				"./catalog1.xml"
> 			]
> 		}
> 	}
> }
> ```
LGTM

> 
> I mean in vscode-xml:
> 
> * remove `xml.catalogs` settings

We prolly want to deprecate it first

**Comment by angelozerr** [comment]
Thanks @fbricon for your feedback.

@mingxi I have implemented this issue but I don't understand how prefer feature is working and I have not found some documentation which explains how it works.

Could you please add a simple usecase with prefer (public and system) by given a sample with catalog, dtd, and explain the usecase that you wish to manage. Thanks!

**Comment by mingxi** [comment]
@fbricon Thank you very much, I will test this feature asap.

**Comment by angelozerr** [comment]
> @fbricon @angelozerr Thank you very much, I will test this feature asap.

It's not available for the moment (my work is not merged). I would like to know play with my PR before merging my work, but I need to understand how prefer is working.

**Comment by mingxi** [comment]
> feature

Okay, I will sort it out and I will share the test cases

**Comment by mingxi** [comment]
@angelozerr 
Step:
1. You can download the latest DITA-OT from [https://github.com/dita-ot/dita-ot/releases/download/3.5.1/dita-ot-3.5.1.zip](url)
2. In my side, unzip it into C:\Users\mingxi\Downloads\dita-ot-3.5.1
3. Set xml.catalog.files as below:
   `{
	"xml": {
		"catalog": {
			"preferPublic": true,
			"useLiteralSystemId": true, 
			"files": [
				"C:\\Users\\mingxi\\Downloads\\dita-ot-3.5.1\\catalog-dita.xml"
			]
		}
	}
}`
4. Open C:\Users\mingxi\Downloads\dita-ot-3.5.1\docsrc\site.ditamap by VSCode and valid it.

**Comment by mingxi** [comment]
![image](https://user-images.githubusercontent.com/8706418/90512999-96849400-e191-11ea-9b5a-d12af8aaea5a.png)
![image](https://user-images.githubusercontent.com/8706418/90513084-b916ad00-e191-11ea-9759-4b0f645006d3.png)

**Comment by mingxi** [comment]
@angelozerr 

Thanks I will test it.
FYI
Below is my code to validate xml manually.

XmlTool.java
```java
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.StringReader;
import java.io.UnsupportedEncodingException;
import java.net.MalformedURLException;
import java.util.List;
import org.apache.xerces.util.XMLCatalogResolver;
import org.apache.xml.resolver.tools.CatalogResolver;
import org.dom4j.io.SAXReader;


public class XmlTool {

    private StringBuilder validateXML(String xml) {
        StringBuilder error = new StringBuilder();
        SAXReader saxReader = new SAXReader();
        // use catalog xml to map dtd
        CatalogResolver resolver = new CatalogResolver(true);
        XMLCatalogResolver xmlResolver = createXMLCatalogResolver(resolver);
        saxReader.setEntityResolver(xmlResolver);
        saxReader.setValidation(true);
        try {
            saxReader.read(new StringReader(xml));
        } catch (Exception e) {
            error.append(e.getMessage());
        }

        return error;
    }

    private static XMLCatalogResolver createXMLCatalogResolver(CatalogResolver resolver) {
        int index = 0;
        List files = resolver.getCatalog().getCatalogManager().getCatalogFiles();
        String catalogs[] = new String[files.size()];
        for (Object file : files) {
            try {
                String catalogPath = new File(file.toString()).toURL().toExternalForm();
                catalogs[index] = catalogPath;
            } catch (MalformedURLException e) {
                e.printStackTrace();;
            }
            index++;
        }
        XMLCatalogResolver xmlResolver = new XMLCatalogResolver();
        // xmlResolver.setPreferPublic(true);
        xmlResolver.setCatalogList(catalogs);

        return xmlResolver;
    }

    private static String readfile(String filePath) throws IOException {
		StringBuilder sbfFileContents = new StringBuilder();
		InputStream is = null;
		try {
			is = new FileInputStream(filePath);
			BufferedReader bReader = new BufferedReader(new InputStreamReader(
					is, "utf-8"));

			String line = null;
			while ((line = bReader.readLine()) != null) {
				sbfFileContents.append(line);
			}
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		} catch (UnsupportedEncodingException e) {
			e.printStackTrace();
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			if (null != is)
				is.close();
		}

		return sbfFileContents.toString();
	}

    public static void main(String argv[]) throws Exception {
            XmlTool test = new XmlTool();
            String xmlContent = XmlTool.readfile("C:\\Users\\mgao26\\Downloads\\dita-ot-3.5.1\\docsrc\\site.ditamap");
            StringBuilder error = test.validateXML(xmlContent);
            if (error.length() == 0) {
                System.out.println("Pass");
            } else {
                System.out.println(error);
            }
        }
}
```

CatalogManager.properties
```xml
catalogs=C:\\Users\\mgao26\\Downloads\\dita-ot-3.5.1\\catalog-dita.xml
relative-catalogs=yes
#verbosity=99
prefer=public
static-catalog=yes
allow-oasis-xml-catalog-pi=yes

```

**Comment by angelozerr** [comment]
Thanks @mingxi for your feedback, the problem doesn't come from XML catalog configuration (prefer, etc) but comes from several bugs when you use XML catalog:

 * validation doesn't work with XML catalog and DTD -> see https://github.com/eclipse/lemminx/issues/848
 * XML completion based on DTD doesn't work with XML catalog and DTD -> see https://github.com/eclipse/lemminx/issues/849
 * DTD hyperlink doesn't work with XML catalog and DTD -> see https://github.com/eclipse/lemminx/issues/850

I have fixed that in my local labtop, now I must create clean PR. As soon as I will have something to test I will ping you.

**Comment by angelozerr** [comment]
> I downloaded your commit and replaced the package.json in extension folder with your package.json

It's not enough, you need to compile XML Language Server (LemMinx), see https://github.com/redhat-developer/vscode-xml/blob/master/CONTRIBUTING.md

**Comment by angelozerr** [comment]
@mingxi could please:

 *  install last vsix from https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D
 * set in your settings.json `"xml.validation.resolveExternalEntities": true`

Validation, XML compltion, hover based on DTD should work:

![image](https://user-images.githubusercontent.com/1932211/91044646-e8a43a00-e615-11ea-8ef9-46a013e937ef.png)

Pease give me feedback, thanks!

**Comment by mingxi** [comment]
@angelozerr Thanks a lot, works fine for me.

![image](https://user-images.githubusercontent.com/8706418/91060442-8707be00-e65d-11ea-94f1-6d39f93c3063.png)

**Comment by mingxi** [comment]
@angelozerr You can close it now, thank you very much.

**Comment by angelozerr** [comment]
> @angelozerr You can close it now, thank you very much.

Glad it works for you! Don't hesitate to create another issues if you find some problem or you require some improvement.

If you need really support settings like prefer (public, system), please reopen the issue by giving a usecase.

I close this issue even if prefer settings is not supported since it was a bug which was fixed.
