### ISSUE TITLE
Auto completion stops once in a while - how to debug?

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#302]
This is non reproducable, so this is a “bad” bug report. But I would like to help to track it down.

Once in a while the autocompletion stops working (and also the syntax check). I cannot tell what triggers it. Is there any way for me to 

a) restart the server without restarting vs code?
b) set some kind of verbosity or similar to try to find out why this happens? I don't know much about java, but I am willing to help as much as I can to debug this.

I am working on the newest vs code and XML extension v0.13.0 on macOS 10.14.6

**Comment by angelozerr** [comment]
@pgundlach thanks for reporting this issue.

It gives the impression that XML Language Server is crashed. Are you working with big XML files ? 

If you add this settings, is it working better ?

`"xml.server.vmargs": "-noverify -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication",`

You can trace server  with `"xml.trace.server": "verbose",` and see traces in the Output terminal:

![image](https://user-images.githubusercontent.com/1932211/89397480-3103c280-d710-11ea-8cb8-e75cd0345f49.png)

**Comment by pgundlach** [comment]
I edit rather short files (20 lines for example). I have set the vmargs setting and the server tracing to verbose and I will report back when I see something strange (which might take a few days).

Thank you so far!

**Comment by pgundlach** [comment]
Everything works fine since I have set

    "xml.server.vmargs": "-noverify -Xmx1024M -XX:+UseG1GC -XX:+UseStringDeduplication"

I'll close this issue and re-open it when I have more info. Thank you once again.

**Comment by pgundlach** [comment]
Still working (great!). Just two statistics about the XML files I work with. The current source is usually not more than 50-100 lines, but the XSD Schema is 6000+ lines.
