### ISSUE TITLE
Feature request: Supost Xpath and xquery, XSLT

### ISSUE THREAD

**Issue by ejgutierrez74** [redhat-developer/vscode-xml#306]
Would be nice to make queries to xml document usning xpath and xquery... 
Also show different visual outputs from an xml document using xslt.

Thanks

**Comment by angelozerr** [comment]
@ejgutierrez74 please create an issue per features by giving more informations. I'm not sure that we will support XQuery for the moment. We have several users requirement (which will take time) like XSD1.1, RelaxNG, XSLT 3, etc. 

According user feedback,  we will work on the proper issue.

**Comment by ejgutierrez74** [comment]
thanks for your response.

My english is not very good, but i think is very self-explanatory, what do you mean for "please create an issue per features by giving more informations" ? I open a different issue for xpath and xquery ? 

id ask for xpath and xquery support in vscode-xml. When i teach this subject i only miss this two things..

**Comment by angelozerr** [comment]
> I open a different issue for xpath and xquery ?

Yes please. For XQuery I'm afraid that we will not work on this issue today.

For XPath, please create an issue to explain what you need (an idea is to open a vscode command, type a XPath expression and it open a dialog with all nodes which matches the xpath expression for the current XML file).
