### ISSUE TITLE
Unclear how to validate with Xsd

### ISSUE THREAD

**Issue by eddy147** [redhat-developer/vscode-xml#308]
Not a coding issue, but more a documentation one, I can not find in the README how to validate a XML file with a Xsd file. 

I have installed the plugin into vscode; I have an Xml file that I would like to validate with a Xsd file. According to the README this should be possible, but how? Ctrl+Shift+P XML Tools doesn't give any options regarding validation.

**Comment by angelozerr** [comment]
I suggest that you see https://developers.redhat.com/blog/2020/07/08/improved-xml-grammar-binding-and-more-in-red-hat-vs-code-xml-extension-0-13-0/ and you will see how to bind XML with XSD. In the demo it generates the XSD, but you can generate the XSD and remove to use your own XSD.

**Comment by angelozerr** [comment]
@eddy147 have you fixed your problem?

**Comment by eddy147** [comment]
hi @angelozerr Unfortunatelt I haven't. 
The doubts I am having are as follows:
- the extension wants to generate an XSD based on the XMl and then binds it. I already have an XSD, I don't eant to generate one. If I generate one, it's maybe generating from a faulty Xml. Is there no option to just load an XSD file?
- The XSD's I have to use consists of 2: the Jw317.xsd and it's parent, the basischema.xsd. 
I used to use Notepad++ back in the day where this works fine with, validate the XML on a chosen XSD, but I am working on Linux and I really want to do everything in VS code.

Thx for your help.

**Comment by angelozerr** [comment]
> the extension wants to generate an XSD based on the XMl and then binds it. I already have an XSD

Indeed but my suggestion is that you generate XSD, to learn how to bind a XML with XSD (the proper syntax with xsi:noNamespaceSchemaLocation, xml-model, etc). More after the generated synx to bind XML with XSD, you can replace the generated XSD with your XSD.

But I think we should write a section about binding XML with XSD/DTD in https://github.com/redhat-developer/vscode-xml/wiki

Otherwise I suggest that you attach your XML and XSD.

**Comment by angelozerr** [comment]
@eddy147 please read https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation

**Comment by angelozerr** [comment]
@eddy147 I close this issue since we have none answer from you.

I suggest that you read https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation

If you cannot validate your XML with your XSD, please attach a zip witho your XML and XSD and reopen the issue.
