### ISSUE TITLE
Completion & hover based on XSD with elementFormDefault="unqualified" doesn't work

### ISSUE THREAD

**Issue by ynohat** [redhat-developer/vscode-xml#311]
Hi!

I am attaching an example XML file (examples/itops.xml) along with supporting schemata and a catalog (that I have setup in VS Code).

Autocomplete works on the fields under the root tag, but not children. Everything seems valid (but I'm no guru). Eclipse WTP (2020-06) autocompletes, using the same catalog and files.

[rh-vscode.zip](https://github.com/redhat-developer/vscode-xml/files/5098821/rh-vscode.zip)

Note that there are several schemata imported, and they use elementFormDefault="unqualified" (a UX choice, that could be revisited if proven anti-standard).

Thanks a lot for an amazing extension!

**Comment by angelozerr** [comment]
> Autocomplete works on the fields under the root tag, but not children. 

For your usecase you mena after templates you hav enone completion (like Site), I supsect it's a problem with namespaceURI computing.

> Thanks a lot for an amazing extension!

Thanks!

**Comment by ynohat** [comment]
@angelozerr thanks! do you feel that there is a workaround I can implement?

**Comment by angelozerr** [comment]
@ynohat I fixed the problem in PR https://github.com/eclipse/lemminx/pull/855 Please wait for merging this PR and after that you will able to install vsix and try it.

**Comment by angelozerr** [comment]
Fixed by https://github.com/eclipse/lemminx/pull/855

**Comment by ynohat** [comment]
Hi @angelozerr, thanks again for your quick response to this! Is this now in the following vsix?

vscode-xml-0.14.0-10301.vsix | 26-Aug-2020 03:50 | 7.0M

**Comment by ynohat** [comment]
Just tested, and it seems to be working now 🥇

**Comment by angelozerr** [comment]
> Just tested, and it seems to be working now

Great! Thanks for your feedback.
