### ISSUE TITLE
TextMate grammar for *.dtd files

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#313]
I think it could be helpful to provide a TextMate grammar for `*.dtd` files. Syntax highlighting would make it a bit easier to read and edit these files.

It looks like nothing is being done to implement it upstream in VSCode: [VSCode related issue](https://github.com/microsoft/vscode/issues/55751). VSCode just reuses the Atom TextMate grammar for XML/DTD: [Atom issue](https://github.com/atom/language-xml/issues/89). The Atom TextMate grammar was extracted from the [TextMate XML plugin](https://github.com/textmate/xml.tmbundle). This grammar doesn't include syntax highlighting for DTD.

**Comment by angelozerr** [comment]
Indeed it should be really nice to improve syntax coloration for DTD and perhaps contribute to vscode?

**Comment by datho7561** [comment]
Yes. Now that I think about it, this would make more sense upstream in vscode.

**Comment by datho7561** [comment]
FYI https://github.com/chrisbra/vim-xml-runtime/blob/master/syntax/dtd.vim

**Comment by angelozerr** [comment]
After quick search I have found https://github.com/sebastienscout/atom-dtd-language/blob/master/grammars/dtd.cson but it is very basic.

I think we could start with that and improve it step by step. When we will have an advanced textmate for DTD we could try to contribute to vscode. See
