### ISSUE TITLE
Avoid Java requirement 

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#314]
In https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml&ssr=false#review-details we have so many reviews which speak about Java installation and user complains about that.

We need to find a solution to avoid installing Java by the user. There is  choices : 

 * solution 1 -> build a binary with grallvm and consume it on vscode-xml side. This binary will be downloaded when XML is opened :  (not when vscode-xml is installed).

 * solution 2 -> download with TypeScript the proper JDK, unzip it and start the XML Language Server by using the java from the unzipped file.

**Comment by mickaelistria** [comment]
I'd like to suggest solution 3 (which I didn't verify):
Using jlink and jpackager, make LemMinX also ship a self contained app (with necessary JRE libs and binary included), and let vscode-xml use it.

**Comment by datho7561** [comment]
The work is nearly done for packaging as a binary with GraalVM native-image: https://github.com/eclipse/lemminx/pull/860. Using this method, we can't use extensions like lemminx-maven through SPI.

From my understanding, using jlink and jpackage will require using Java 9 or newer. It might allow using extensions through SPI, depending on if all the libraries required for the extension are bundled. This would be a better solution if we can this use case to work.

**Comment by mickaelistria** [comment]
> The work is nearly done for packaging as a binary with GraalVM native-image: eclipse/lemminx#860. Using this method, we can't use extensions like lemminx-maven through SPI.

That's a pity, and would actually quickly become a blocker for some serious use-cases IMO.

> From my understanding, using jlink and jpackage will require using Java 9 or newer. I

Moving to newer Java versions is not a bad thing, especially if tt's embedded and users don't even have to care about it ;)

**Comment by angelozerr** [comment]
> That's a pity, and would actually quickly become a blocker for some serious use-cases IMO.

If your fear is that you will not be able to consume lemminx-maven, the binary mode is done by default only if we don't find a JRE. In the case when user have a JRE (ex : maven user), it will use the JRE and SPI will work. 

@datho7561 please correct me if I'm wrong.

**Comment by mickaelistria** [comment]
> , the binary mode is done by default only if we don't find a JRE. In the case when user have a JRE (ex : maven user), it will use the JRE and SPI will work.

That's an interesting approach then. At least it would allow extensions to work in some cases!
However, I admit I'm unsure about the idea of going binary over using (embedded) Java here. I once was warned that binary applications would perform worse when dealing with a massive amount of data for a long time; which seems to be the nominal state of a LS. Do we have proper estimations about how things scale on a realistic use-case?

**Comment by angelozerr** [comment]
> Do we have proper estimations about how things scale on a realistic use-case?

No, we will see if this idea is great according user feedback.

**Comment by datho7561** [comment]
Currently the zipped Linux native-image binary is 14 MB. Using [UPX](https://upx.github.io/) on the binary to reduce its size also results in a 14 MB binary. This is smaller that most of the minimal JREs listed here https://download.eclipse.org/justj/jres/11/downloads/latest/.

**Comment by datho7561** [comment]
As of 0.15.0 we now provide a mechanism to download and run a binary version of LemMinX.
