### ISSUE TITLE
xml.catalogs setting

### ISSUE THREAD

**Issue by fred-gagnon** [redhat-developer/vscode-xml#315]
In order to help users understand how to properly fill the xml.catalogs setting, I propose the following:

1. Add examples of how to set xml.catalogs in the extension settings page
and/or
2. Add examples of how to set xml.catalogs in the error popup that appears when a catalog path is invalid
3. In the extension settings page, when clicking on the `Add` button to add a new catalog, there should be a `Browse` button to allow the user to browse the file system and select the desired catalog rather than having to paste a string in the text box which is very error prone

**Comment by angelozerr** [comment]
> Add examples of how to set xml.catalogs in the extension settings page

Please read wiki:

 * for catalog with XSD -> https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation#XML-catalog-with-XSD
 * for catalog with DTD -> https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation#XML-catalog-with-DTD

> Add examples of how to set xml.catalogs in the error popup that appears when a catalog path is invalid

What do you mean with examples? You mean in the wiki page, show the error popup when catalog.xml file path is not valid? Could you explain more your idea please. Thanks!

> In the extension settings page, when clicking on the Add button to add a new catalog, there should be a Browse button

I'm not sure vscode provides this capability.

**Comment by fred-gagnon** [comment]
@angelozerr thanks for replying to my suggestion. 

First of all, thanks for pointing out the wiki link, I had not found it. I feel bad for that ! Looking at it, I see that it lacks an example of how to set an XML catalog when using `xsi:noNamespaceSchemaLocation`. It took me quite a while to figure out how to make this work, it might be good to add an example.

Now coming back to my suggestions, what I meant by "examples" is:
![Example1](https://user-images.githubusercontent.com/61014947/91733070-1853c480-eb77-11ea-93c6-cacc3efaa58b.png)

Or, instead of adding examples, maybe a direct link to the wiki would be good as well since it would prevent from maintaining documentation in two places.

Regarding the examples in the error popup, what I meant was:
![Example2](https://user-images.githubusercontent.com/61014947/91733558-adef5400-eb77-11ea-832a-931b8f45648f.png)

But since there is a button to bring you directly to the settings, if documentation is added as per my first screenshot, I guess adding examples in the error popup is not really worth it after all.

**Comment by angelozerr** [comment]
> First of all, thanks for pointing out the wiki link, I had not found it. I feel bad for that ! 

No no no, this wiki page has been written few days ago and we need to reference it in the README too.

>  Looking at it, I see that it lacks an example of how to set an XML catalog when using xsi:noNamespaceSchemaLocation. It took me quite a while to figure out how to make this work, it might be good to add an example.

Thanks for your feedback, we need to add this sample.

> The wiki also says: Please note that you can declare your catalog path with file:/// if you need . This is clearly outdated now.

Why is it outdated?

> Or, instead of adding examples, maybe a direct link to the wiki would be good as well since it would prevent from maintaining documentation in two places.

Indeed we will add e link to the wiki page. @fbricon I think we could add a link to the wiki page for interesting setting s(ex : catalog, format, etc).

@fred-gagnon anyway thanks for your great suggestion!

**Comment by fred-gagnon** [comment]
@angelozerr 

Why is it outdated? : Because doing `file:///C:\\folderA\\folderB\\MyCatalog.xml` doesn't work. Or if it should be used differently, then it needs to be better explained.

In the previous versions of the extension, my catalogs were declared as such: `file:///C:/folderA/folderB/MyCatalog.xml`

However, this no longer works as discussed here: https://gitter.im/redhat-developer/vscode-xml?utm_source=notification&utm_medium=email&utm_campaign=unread-notifications

**Comment by angelozerr** [comment]
@fred-gagnon just for your information, I'm working on the embed doc https://github.com/redhat-developer/vscode-xml/issues/326#issue-701686540

**Comment by angelozerr** [comment]
I close this issue since now we have an embed documentation which explains XML catalogs.

For helping to fill settings with Browse button, I create the issue https://github.com/redhat-developer/vscode-xml/issues/329
