### ISSUE TITLE
Add XML documentation for settings which have no documentation

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#328]
Once https://github.com/redhat-developer/vscode-xml/issues/326 will be merged, it should be nice to improve documentation by collecting settings (ex : xml.validation.resolveExternalEntities) which are not linked to documentation

**Comment by datho7561** [comment]
Undocumented settings (no link to internal docs) as of commit c90c732 (WIP collecting them all):
- [ ] XML code lens enabled
- [ ] XML completion  auto close tags
- [ ] XML file associations

**Comment by angelozerr** [comment]
For `XML code lens`, 

 * I will create a CodeLens.md for that because you have other codelens kind (ex : xs:element)
 * add a section about Code lens for xs:element -> see https://developers.redhat.com/blog/2019/07/24/whats-new-in-the-visual-studio-code-xml-extension/
 * add screenshot (or better a demo) for codelens to show references are clickable.
