### ISSUE TITLE
Go To Top button in embedded docs is orange when clicked

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#330]
Please see PR #327.

Open an embedded documentation page, and click on the back to top button. The back to top button now has an orange border:
![ButtonHighlightingMarkdownDocumentation](https://user-images.githubusercontent.com/22376627/93359224-59530680-f810-11ea-9897-1439a5c7b570.png)

This button should not have an orange border to be visually consistent with the rest of the vscode UI.

**Comment by fbricon** [comment]
Works fine on Mac

**Comment by datho7561** [comment]
Works fine on Linux. I think that this must have been something upstream that changed
