### ISSUE TITLE
Avoid duplication of documentation between extension and wiki

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#331]
See [PR #327](https://github.com/redhat-developer/vscode-xml/pull/327)

The markdown documentation for settings that is embedded in the extension is copied directly from the vscode-xml wiki pages. Come up with some mechanism to avoid maintaining two copies of the settings documentation.

**Comment by angelozerr** [comment]
It should be nice in the same PR to update or add links in the README.md  of vscode-xml settings section to the docs md files https://github.com/redhat-developer/vscode-xml#supported-vs-code-settings
