### ISSUE TITLE
Provide an example of adding a JAR to the classpath of LemMinX

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#338]
In https://github.com/redhat-developer/vscode-xml/pull/336 we will add the ability to add LemMinX extensions to the LemMinX classpath through a setting. Provide an example of adding a LemMinX extension to demonstrate how this works.

Specifically, provide an example in `Preferences.md`

**Comment by rgrunber** [comment]
https://github.com/redhat-developer/vscode-xml/blob/master/docs/Preferences.md#extension-jars -> https://github.com/redhat-developer/vscode-xml/blob/master/docs/Extensions.md#custom-xml-extensions and one of the examples mentions how to use `xml.extension.jars`.
