### ISSUE TITLE
Format comments which have no end comments should not generate end comments

### ISSUE THREAD

**Issue by clement-boret** [redhat-developer/vscode-xml#347]
vscode Version: 1.50.1
on macosx version 10.14.6

There is an error when performing "format modified lines": please see following gif to get the scenario.
![vscode issue gif](https://user-images.githubusercontent.com/10899818/97082080-41d51d80-1607-11eb-9ca4-71f4b10ddcc3.gif)

**Comment by angelozerr** [comment]
Thanks for reporting this issue.

This problem is easy to reproduce.

Given this XML:

```xml
<foo>
	<!-- 
</foo>
```

After formatting, it generates the end comment:

```
<foo>
	<!-- 
</foo>-->
```

Although it should not generate the `-->`. 

I'm working on this issue.
