### ISSUE TITLE
Max line length

### ISSUE THREAD

**Issue by NatoBoram** [redhat-developer/vscode-xml#350]
Some projects use an `.editorconfig` file to specify a maximum line length for most of their documents. It would be nice to have this setting attempted to be respected, or at least have an option to specify it, so it could be done automatically in a deterministic way.

Example : 

```xml
<activity android:name=".MainActivity" android:launchMode="singleTop" android:theme="@style/LaunchTheme" android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode" android:hardwareAccelerated="true" android:windowSoftInputMode="adjustResize">
```

```xml
<activity
  android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
  android:hardwareAccelerated="true" android:name=".MainActivity"
  android:launchMode="singleTop" android:theme="@style/LaunchTheme"
  android:windowSoftInputMode="adjustResize"
>
```

**Comment by angelozerr** [comment]
You speak about formatting, is that?

**Comment by NatoBoram** [comment]
Yes!

**Comment by angelozerr** [comment]
@NatoBoram please install prerelease https://github.com/redhat-developer/vscode-xml#contributing, you can configure with https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatmaxlinewidth

**Comment by raduten** [comment]
Hello - new to VSCode. Coming from eclipse. Where can I add xml.format.maxLineWidth ? Formatting.md? I have the pre-release versions of vs-code and redhat xml language support.

Thanks!

**Comment by fbricon** [comment]
@raduten  `xml.format.maxLineWidth` must be set in your [VS Code settings ](https://code.visualstudio.com/docs/getstarted/settings)

**Comment by raduten** [comment]
Thanks! Managed to do it. Needed to open settings.json using this command: Preferences: Open Settings (JSON) . Then add the new setting in the json file itself.
