### ISSUE TITLE
No completion on attributes with xs:union (XSD)

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#351]
I try to use autocompletion (which usually works fine for my XSD schema) on an attribute but that fails (no choices given).

This happens when the completion  not only allows a list of choices but also patterns such as ` <xs:pattern value="\{.+\}"/>` and `<xs:pattern value="--|bg|ca|cs|...|uk|zh"/>`

My schema is at

https://github.com/speedata/publisher/blob/develop/schema/layoutschema-en.xsd

the relevant lines at

https://github.com/speedata/publisher/blob/249a5e886bdd09301b78fc4047b62573272e5fbd/schema/layoutschema-en.xsd#L2572

This is my XML file where I try validation. The cursor is after `mainlanguage="`, I try to complete the attribute.

```
<Layout xmlns="urn:speedata.de:2009/publisher/en">
	<Options mainlanguage="" />

</Layout>
```

I'd expect (wish) that the XML mode suggests the enumerated items (see the oXygen example).

<img width="419" alt="lang" src="https://user-images.githubusercontent.com/209434/97417574-25d3c380-1908-11eb-9230-5dbf2e9d7d58.png">

(using XML extension v0.13.0)

**Comment by angelozerr** [comment]
The PR https://github.com/eclipse/lemminx/pull/923 should fix this issue. See the following demo:

![XSUNionPublisherDemo](https://user-images.githubusercontent.com/1932211/97721205-6fb7d780-1ac9-11eb-9537-3499f340ffe9.gif)

**Comment by pgundlach** [comment]
Thank you very much, this looks great!

**Comment by pgundlach** [comment]
Works fine in 0.14. Thank you very much!
