### ISSUE TITLE
Jenkins build passes even if server jar is missing

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#354]
Please see https://github.com/eclipse/che/issues/18247

It looks like the jar build failed, yet vscode-xml gets packaged and uploaded without the jar instead of the build failing.

**Comment by datho7561** [comment]
Looks like this issue was related to an external pipeline that was packaging the plugin for Che

**Comment by rgrunber** [comment]
Thanks for bringing this up. To give any help what we'd really need is the build logs of the .vsix at issue because from my quick look through the ones we publish, they all include the necessary LemMinx jar.
