### ISSUE TITLE
Question about xml.symbols.filters: limit the elements to display in outline?

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#371]
I have a question regarding the ”Outline“ view in vscode/XML 0.14

Is it possible to restrict the symbols to a subset of elements?

For example my XML file:

```xml
<Layout xmlns="urn:speedata.de:2009/publisher/en">
	<Record element="A">
		<PlaceObject>

		</PlaceObject>
	</Record>
	<Record element="B" mode="bla">
		<PlaceObject>
			<Textblock>
				<Paragraph>
					<Value></Value>
				</Paragraph>
			</Textblock>
		</PlaceObject> 
	</Record>
</Layout>
```

I'd like to restrict the outline to something like this (discard any child elements or filter all elements that is not "Record"):

<img width="357" alt="outline" src="https://user-images.githubusercontent.com/209434/98929080-ee097600-24da-11eb-8699-7cfac17c4a9a.png">

I have tried this:

```json
    "xml.symbols.filters": [
        {
            "pattern": "layout.xml",
            "expressions" :[
                {
                    "xpath": "not(local-name() = 'Record')",
                    "excluded": true
                },
                {
                  "xpath": "//Record/@*"
               },
            ]
        }
    ],
```

but I assume this is not what I need.

Perfect for me would be if I could use the "Go to symbol..." command (cmd-shift-o on macOS) to display as choices only

"Record A" and "Record B bla" 

(each attribute or a subset attached to the symbol)

(Feel free to close this issue without a comment, just a wish/feature request)

**Comment by angelozerr** [comment]
At first please read https://github.com/redhat-developer/vscode-xml/blob/master/docs/Symbols.md#xpath-expression XPath expression are basic.

> I'd like to restrict the outline to something like this (discard any child elements or filter all elements that is not "Record"):

No it's not possible, we  decided to provide xml symbols filters because by default attributes and text nodes are not displayed and fix https://github.com/redhat-developer/vscode-xml/issues/220

Hiding some part of outline is possible but it's not very advanced how you can see. We will see if this feature is requested by another user, but it seems that it's not a common use of the symbols filter but perhaps I'm wrong, we will see...

> Perfect for me would be if I could use the "Go to symbol..." command (cmd-shift-o on macOS) to display as choices only

"Record A" and "Record B bla"

I see the idea but it will require to support a renderer information to display attribute in the same lines than element. An another idea is to provide a new vscode command to search elements by XPath?

**Comment by fbricon** [comment]
You can at least only display node starting with some string. Just type it in the Outline view, like:
<img width="340" alt="Screenshot 2020-11-12 at 16 25 56" src="https://user-images.githubusercontent.com/148698/98959770-e611fc00-2503-11eb-9340-4f727b9728e6.png">

**Comment by pgundlach** [comment]
@angelozerr Thank you for the feedback. I think I will close this issue. I'd really like to see this in vscode/xml but I think it is a good idea to wait if someone else (ore more than one person) will come up with the same request.

@fbricon The filtering works, but having this on symbols has the advantage of selecting the relevant element on "Go to symbol..." which is great if you have a programming language written in XML (XSLT for example). (My application is also a programming language so that is where my feature request comes from).

Thank you as always for your time and the excellent XML mode!

**Comment by angelozerr** [comment]
> I'd really like to see this in vscode/xml but I think it is a good idea to wait if someone else (ore more than one person) will come up with the same request.

Indeed I prefer waiting for having several request to try to find a commons solution instead of developing specific case. Users feedback are very important for us. Thanks for sharing your idea!

It's not very elegant but you can try that:

```json
"xml.symbols.filters": [
      {
         "pattern": "layout.xml",
         "expressions" :[
            // Include layout root element
            {
               "xpath": "//Layout"
            },
            // Include record element
            {
               "xpath": "//Record"
            },
            // Include attributes of record
            {
               "xpath": "//Record/@*"
            },
            // Exclude all other elements
            {
               "xpath": "//",
               "excluded": true
            }
         ]
      }
```

> Thank you as always for your time and the excellent XML mode!

Glad you like it!
