### ISSUE TITLE
Don't add trailing space to processing instructions

### ISSUE THREAD

**Issue by anthonyvdotbe** [redhat-developer/vscode-xml#372]
In https://github.com/redhat-developer/vscode-xml/issues/240#issuecomment-618430575 it was decided that:
> we should never generate a space before the end of processing instruction

However, I just noticed that this was only resolved for the XML prolog, and not for any other processing instructions. For example `<?m2e ignore?>` in a `pom.xml` still formats with a trailing space: `<?m2e ignore ?>`. To resolve this issue, I guess it should be sufficient to delete [this line](https://github.com/eclipse/lemminx/blob/51b6d6b11704ae4b31d1d667e96fc1c4108c4a09/org.eclipse.lemminx/src/main/java/org/eclipse/lemminx/utils/XMLBuilder.java#L343).

**Comment by angelozerr** [comment]
@anthonyvdotbe you are right, could you create a PR for that by adjusting tests please.

**Comment by anthonyvdotbe** [comment]
@angelozerr I created the PR

**Comment by angelozerr** [comment]
Fixed by https://github.com/eclipse/lemminx/pull/934
