### ISSUE TITLE
extension does not correctly detect java home correctly without environment variable set

### ISSUE THREAD

**Issue by xoviat** [redhat-developer/vscode-xml#374]
This is more of an annoyance rather than a showstopper. However, having to update JAVA_HOME is annoying because my JAVA is updated automatically. Here's what I know:

- Upon installing the extension, I received a message that JAVA_HOME was not detected.
- Investigating further, vscode-xml appears to use node-find-java version 0.2 to find JAVA home, when JAVA home is not set. This behavior is correct from my POV:

https://github.com/redhat-developer/vscode-xml/blob/f5e2cdc6d2677f703be7ef6ff09bc192644c73c9/src/requirements.ts#L69-L76

- Investigating further, it appears to look in JavaSoft for JAVA_HOME (this is version 0.2, which is in the requirements):

https://github.com/jsdevel/node-find-java-home/blob/1f3dc4e5186dd434859ff6fffb0679feb1e47848/index.js#L61-L65

```
    if(options.allowJre){
      possibleKeyPaths = possibleKeyPaths.concat([
      "SOFTWARE\\JavaSoft\\Java Runtime Environment",
      ]);
    }
```

Here is the structure of my registry:

![image](https://user-images.githubusercontent.com/49173759/100117085-129a1200-2e3a-11eb-9d59-50a6985dc045.png)

Yet, I still received this error message:

![image](https://user-images.githubusercontent.com/49173759/100117788-c8656080-2e3a-11eb-9569-276576eca770.png)

Adding this directly to user settings appears to resolve the problem:

![image](https://user-images.githubusercontent.com/49173759/100117632-9fdd6680-2e3a-11eb-90ea-d6303633c17a.png)

The question is why this error happened, given that the extension should have found JAVA_HOME by itself. I am not currently set-up to debug vscode extensions, but I may tackle this if I have time.

**Comment by angelozerr** [comment]
> I am not currently set-up to debug vscode extensions, but I may tackle this if I have time.

It should be really nice! Thanks!
