### ISSUE TITLE
xml catalog definition should be built-in

### ISSUE THREAD

**Issue by GitMensch** [redhat-developer/vscode-xml#375]
This is related to #361 - when the xml catalog is defined as `<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">` the plugin says

~~~
{
	"resource": "/x:/test/catalog.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "cvc-elt.1.a",
	"severity": 8,
	"message": "cvc-elt.1.a: Cannot find the declaration of element 'catalog'.",
	"source": "xml",
	"startLineNumber": 2,
	"startColumn": 2,
	"endLineNumber": 2,
	"endColumn": 9
}
{
	"resource": "/x:test/catalog.xml",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": "schema_reference.4",
	"severity": 4,
	"message": "schema_reference.4: Failed to read schema document 'https://www.oasis-open.org/committees/entity/release/1.1/catalog.xsd', because 1) could not find the document; 2) the document could not be read; 3) the root element of the document is not <xsd:schema>.",
	"source": "xml",
	"startLineNumber": 2,
	"startColumn": 62,
	"endLineNumber": 2,
	"endColumn": 62
}
~~~

This may be related to internet access on that machine. Still: can you try to have this working, possibly with an internally shipped version of the schema file for xml catalogs?

**Comment by angelozerr** [comment]
@GitMensch I agree with you since we do that xml.xsd for instance, but it's an issue for LemMinx. Could you create an issue on LemMinx please. I could explain you how to do that if you would be interested to provide a PR.

**Comment by GitMensch** [comment]
> I could explain you how to do that if you would be interested to provide a PR.

Sure, I'm a bit short on time currently but with a helping hand would do that.

**Comment by angelozerr** [comment]
> Sure, I'm a bit short on time currently but with a helping hand would do that.

Great! Let's create the issue and I will give you some directives. Please not that you must sign a CLA to contribute to LemMinx which belongs to Eclipse organization.

**Comment by GitMensch** [comment]
@angelozerr Thanks for the fix and that you did the extra work yourself (I found no time in the last days to get to something "new").
So obvious we'd now need the updated lemminx integrated here and a release of this extension (last one is listed June, so it maybe is reasonable in any case). There is no 0.13.0 milestone therefore I ask here: any pointers about that yet?

**Comment by datho7561** [comment]
@GitMensch we have released more recently than july (please see https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml). It looks like it wasn't tagged, though.

**Comment by GitMensch** [comment]
I was confused by that, too. https://github.com/redhat-developer/vscode-xml/tags shows 0.14.
A tag is (for GitHub) only a tag, a defined named point in the history. To create a release one always needs to make it a release afterwards (possible with release rights, for example with the web-interface; could also be done by a bot/github action, which could also upload to vs marketplace / open-vsx-registry on the fly) and creating a release also allows to attach more files than the 1:1 source snapshpot (adding the vsix is really useful).

So: the last release is now nearly a month old and the 0.15 milestone _is_ the milestone for the next version. it luckily only contains 3 items (including this one), all closed, so it looks like an update from lemminx and a new release may be in sight,

**Comment by angelozerr** [comment]
> @angelozerr Thanks for the fix and that you did the extra work yourself (I found no time in the last days to get to something "new").

No problem @GitMensch! As we plan to do a new release soon (with a new exciting feature with binary support to avoid installing Java runtime and I hope really that it will stop our bad reviews about Java https://marketplace.visualstudio.com/items?itemName=redhat.vscode-xml&ssr=false#review-details (all issues with 1 star = Java requirement)), I would like to fix all easy issues.

> I found no time in the last days to get to something "new"

I understand that, no problem.

> So obvious we'd now need the updated lemminx integrated here and a release of this extension (last one is listed June, so it maybe is reasonable in any case). There is no 0.13.0 milestone therefore I ask here: any pointers about that yet?

You should have the last vsix at https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D each time we push something in LemMinx or vscode-xml repository.
