### ISSUE TITLE
Closing tag indentation not preserved if tag's inner text is plaintext

### ISSUE THREAD

**Issue by BDSuther** [redhat-developer/vscode-xml#377]
I run into this particular issue frequently when authoring MSBuild props/targets/proj files. A common pattern is defining a property group which contains several target names for use with a DependsOnTargets attribute value.

```
<Project>
…
  <PropertyGroup>
    <TargetDependsOn>
      $(TargetDependsOn);
      TargetSetup;
    </TargetDependsOn>
  </PropertyGroup>
…
</Project>
```

This will get formatted as 

```
<Project>
…
  <PropertyGroup>
    <TargetDependsOn>
      $(TargetDependsOn);
      TargetSetup;
</TargetDependsOn>
  </PropertyGroup>
…
</Project>
```

The closing tag loses **all** indentation and has zero whitespace before the closing tag;. When the inner text of the tag is another XML tag, the indentation is properly preserved.

**Comment by angelozerr** [comment]
Indeed it's a bug, thank's for reporting this issue.

**Comment by angelozerr** [comment]
This issue should be fixed with our new formatter. Please install vscode-xml 0.23.0.
