### ISSUE TITLE
Disable editor.autoClosingBrackets to allow xml.autoClosingTags to work

### ISSUE THREAD

**Issue by NikolasKomonen** [redhat-developer/vscode-xml#38]
Follow,

https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L374

https://github.com/redhat-developer/vscode-java/blob/master/src/extension.ts#L351

to notify the user to disable the setting

**Comment by fbricon** [comment]
you need to make sure `editor.autoClosingBrackets` is disabled for [xml] only, not for all (dunno how to do that)

**Comment by NikolasKomonen** [comment]
Will be done by 

```
"configuration": {
    ...
},
"configurationDefaults": {
      "[xml]": {
        "editor.autoClosingBrackets": false
      }
}
```
