### ISSUE TITLE
Unknown xml attribute 'value' for tag 'xs:enumeration'

### ISSUE THREAD

**Issue by JensMertelmeyer** [redhat-developer/vscode-xml#382]
Consider the following file:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:simpleType name="MyEnum" final="restriction">
		<xs:restriction base="xs:string">
			<xs:enumeration value="uno" />
			<xs:enumeration value="dos" />
			<xs:enumeration value="tres" />
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
```

Version v0.14.0 emits the following problems:

> Unknown xml attribute 'value' for tag 'xs:enumeration' [5,34]
> Unknown xml attribute 'value' for tag 'xs:enumeration' [6,34]
> Unknown xml attribute 'value' for tag 'xs:enumeration' [7,34]

According to https://www.w3schools.com/xml/schema_facets.asp, the above schema is correct. I don't really understand what the "unknown xml attribute" is trying to tell me 😶

**Comment by angelozerr** [comment]
It works for me.

In the outline, could you check you have the same referenced grammar info than me (Binding with embedded xml.xsd):

![image](https://user-images.githubusercontent.com/1932211/102098596-b5d1bc00-3e27-11eb-826f-822df758420b.png)

**Comment by JensMertelmeyer** [comment]
Sorry, I don't quite understand.
For me, it is enough to paste the above code into the editor and set the language mode to XML and I get the following output:
![image](https://user-images.githubusercontent.com/1827784/102340979-7924d280-3f97-11eb-913c-c8bce9ef34af.png)

The outline view displays the following:
![image](https://user-images.githubusercontent.com/1827784/102341077-9eb1dc00-3f97-11eb-9f6c-46ba2b006c53.png)

Is there any kind of log file I can provide?

**Comment by angelozerr** [comment]
I wonder if this error comes from vscode-xml? Because you should have different error if attribute is not allowed:

![image](https://user-images.githubusercontent.com/1932211/102349446-a2e3f680-3fa3-11eb-9a6b-1fed279bf7f7.png)

Could you uninstall the vscode-xml and check if you have the error again please?

**Comment by JensMertelmeyer** [comment]
It really came from [another extension](https://marketplace.visualstudio.com/items?itemName=rogalmic.vscode-xml-complete) which somehow snuck in. I'm sorry.

**Comment by angelozerr** [comment]
@JensMertelmeyer thanks for your feedback. I'm just curious which features vscode-xml-completer provides you compare to vscode-xml?

**Comment by JensMertelmeyer** [comment]
@angelozerr , There was not much thought involved. I was looking for something that would help me writing an XSD schema for some example xml snippets. I was not even aware I still had this other plug-in enabled as Visual Studio Code silently synced it from another machine 😣.

Thanks for asking and have a nice day.

**Comment by angelozerr** [comment]
Thanks @JensMertelmeyer for your feedback. Don't hesitate to create issues if you need some features which are not supported compare to another XML extensions.
