### ISSUE TITLE
Error in XML document in docs

### ISSUE THREAD

**Issue by bricksdont** [redhat-developer/vscode-xml#394]
In the docs about XSD validation, one of the XML documents shown is not actually valid with respect to the schema:

https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xsischemalocation

The corresponding schema has a "targetNamespace" attribute, which means it expects all elements in the XML document to be in that namespace. The XML in the docs does not have a namespace:

```xml
<foo
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://foo foo.xsd">
  <bar />
</foo>
```

The document should actually have a default namespace, like so:

```xml
<foo xmlns="http://foo"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://foo foo.xsd">
  <bar />
</foo>
```

**Comment by angelozerr** [comment]
Thanks @bricksdont for your feedback.

Is there any chance to have a PR?

**Comment by angelozerr** [comment]
Fixed with https://github.com/redhat-developer/vscode-xml/pull/396
