### ISSUE TITLE
Bind XSD, DTD with CodeLens

### ISSUE THREAD

**Issue by bricksdont** [redhat-developer/vscode-xml#395]
A very useful feature for an XML IDE would be a button or action to associate an XML document that is currently open in VS Code with a schema file.

After clicking a button, a file dialog would open which would allow to select an XSD file from the file system. Then, your XML extension would insert into the XML document the correct attributes or processing instructions needed to make this association.

The reason why that would be useful is that there are several ways to associate an XML document with an XSD file:

https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#validation-with-xsd-grammar

all of them cumbersome, and hard to remember. Especially because you also have to pay close attention and be aware that it makes a difference whether the XML document to be associated has a namespace or not.

Oxygen has functionality like this and I find it very useful.

**Comment by angelozerr** [comment]
Just for information, today we have a code action on the root element (if XML is not bound to a XSD/DTD) which 

 * generate the XSD / DTD 
 * generate the association (xsi:schemaLocation, xml-model, etc)

But I agree this code action doesn't provide the capability to bind the XML with an existing XSD, DTD.

I think the best mean should be to provide two vscode command 

 * `validate with XSD` 
 * `validate with DTD`
 
available for the current XML file. When this command is executed:

* step1 : it should provide the binding strategy according the grammar type (ex : xsi:schemaLocation if the validation with XSD is executed.
* step2 : it should open a file dialog to select the XSD or DTD file.

After the selected XSD, DTD file, it should generate the proper association according the binding strategy choose in the step 1.

**Comment by bricksdont** [comment]
Thanks for your quick answer!

I think that "validate with XSD|DTD" would lead people to believe that the XML document itself is unchanged. "Associate with XSD|DTD" on the other hand implies that the XML document itself is changed (i.e. special attributes added to the root element).

For your extension to perform the validation is it absolutely necessary for the XML document itself to contain the association, e.g. with `schemaLocation`?

**Comment by angelozerr** [comment]
> Thanks for your quick answer!

You are welcome! I had this idea in my mind since several time,but I waited for user issue to know if it was relevant. Thanks for having created this issue :)

> I think that "validate with XSD|DTD" would lead people to believe that the XML document itself is unchanged. "Associate with XSD|DTD" on the other hand implies that the XML document itself is changed (i.e. special attributes added to the root element).

Totally agree with you, yes command should be named with 

 * `Associate with XSD`
 * `Associate with DTD` 

> For your extension to perform the validation is it absolutely necessary for the XML document itself to contain the association, e.g. with schemaLocation?

No, there are several binding strategy like xml-model, xsi:schemaLocation, xsi:noNamespaceLocation which are standard associations and we provide a non standard association with XML file association where you declare the association with a settings (it avoid to polluate the XML with this association) or with XML catalog. 

Please read https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#validation-with-xsd-grammar

Managing XML file association or XML catalog should be very nice but I'm not sure it will be easy to implement.

**Comment by bricksdont** [comment]
Thanks,

Sorry I was not very clear: I meant does your extension need the association to be physically present either in the XML document itself, a catalog or the settings?

I was asking because if that is true, then it would be understandable that such an action would be called "Validate" instead of "associate" - because validation implies changing or creating files or settings.

**Comment by angelozerr** [comment]
> Sorry I was not very clear: I meant does your extension need the association to be physically present either in the XML document itself, a catalog or the settings?

Yes you need to store association somewhere. Otherwise how to know this association?

> I was asking because if that is true, then it would be understandable that such an action would be called "Validate" instead of "associate" - because validation implies changing or creating files or settings.

As I said you, I'm totally agree with you and vscode commands should be called `association with`

> Anyway, would be great to have a button / action like this.

vscode command is the standard support to do that.

**Comment by tomschr** [comment]
May I add the related issues #450 and #451? They shouldn't be forgotten when implementing this features. :wink: Thanks! :+1:

**Comment by angelozerr** [comment]
> May I add the related issues #450 and #451? They shouldn't be forgotten when implementing this features. 😉 Thanks! 👍

Yes sure.

I think the best mean to support this issue is to use CodeLens when XML is not bound to a grammar like this

```xml
[Associate with XSD] [Associate with DTD] [Associate with RelaxNG] [Associate with Schematron]
<root>

</root>
```

**Comment by angelozerr** [comment]
@bricksdont once my PR will be merge you should benefit with that:

![BindWithCodeLensDemo](https://user-images.githubusercontent.com/1932211/121893261-0d40de00-cd1e-11eb-96fc-f64298effab4.gif)

**Comment by bricksdont** [comment]
This looks awesome! I will definitely test it once available. If the PR is merged to the main branch, can I get this version by updating inside VS Code?
