### ISSUE TITLE
Calling extension.ts -> activate() method fails in 0.15.0

### ISSUE THREAD

**Issue by jag-sfdc** [redhat-developer/vscode-xml#418]
There is a regression in 0.15.0 likely due to these changes - https://github.com/redhat-developer/vscode-xml/commit/5495a0e2e725a61d58c49af14b94e5d0a1312e6e.

The following code used to work in 0.14.0, but now extensionApi is 'undefined'.

```
const redHatExtension = vscode.extensions.getExtension('redhat.vscode-xml');
const extensionApi = await redHatExtension!.activate();
```

**Comment by angelozerr** [comment]
Is there any chance to have a PR to fix this bug?
