### ISSUE TITLE
Simplify getSettings()

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#42]
getSettings should mostly be equivalent to 

```typescript
let configXML = workspace.getConfiguration('xml');
// add missing log file settings
let settings: Settings = {
    configXML
}
return settings;
```

That makes all xml settings automatically sent to the server, so no need to change anything here when new settings are added to package.json

**Comment by NikolasKomonen** [comment]
@fbricon what about sending the log file path. Is this an acception?
