### ISSUE TITLE
Rename not completing with binary

### ISSUE THREAD

**Issue by JVimes** [redhat-developer/vscode-xml#424]
I installed v0.15.1-117 and tried to rename an element. The operation never completed, progress bar goes forever:

https://user-images.githubusercontent.com/6148201/107999955-0be8ea00-6fa6-11eb-9ec1-3bd9c58d8679.mp4

Windows 10, version 20H2 (OS Build 19042.804).
VSCode v1.53.2

**Comment by angelozerr** [comment]
Are you using binary support?

**Comment by JVimes** [comment]
I don't think so. I don't know what that is and I haven't changed any extension settings.

**Comment by angelozerr** [comment]
I cannot reproduce the issue. Could you please activate the XML trace log (see https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file) and share the full trace in this issue please when problem occurs. Thanks.

**Comment by JVimes** [comment]
Oh I see. Yes, I must be using binary support (Java is not installed). Thank you for investigating.

**Comment by angelozerr** [comment]
> Oh I see. Yes, I must be using binary support (Java is not installed). Thank you for investigating.

You are welcome, I created a PR for that https://github.com/eclipse/lemminx/pull/990
