### ISSUE TITLE
Add a section to explain how to create a binary server in local

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#425]
Add a section for building binary in https://github.com/redhat-developer/vscode-xml/blob/master/CONTRIBUTING.md

**Comment by angelozerr** [comment]
See for instance explanation at https://github.com/eclipse/lemminx/pull/990#issuecomment-780841356

**Comment by rgrunber** [comment]
Could we also add the  following to this change :

- add `<name>XML Language Server (LemMinX)</name>` to the org.eclipse.lemminx submodule.
