### ISSUE TITLE
Hover error 

### ISSUE THREAD

**Issue by gorkem** [redhat-developer/vscode-xml#43]
When I hover on a pom.xml I see the hover content as `Unsupported Markup content received. Kind is: undefined`.

**Comment by fbricon** [comment]
@angelozerr error still occurs. Server sends:
```
[Trace - 11:37:47 AM] Received response 'textDocument/hover - (13)' in 3ms.
Result: {
    "contents": {
        "value": "The modules (sometimes called subprojects) to build as a part of this project. Each module listed is a relative path to the directory containing the module. To be consistent with the way default urls are calculated from parent, it is recommended to have module names match artifact ids."
    }
}

```

**Comment by angelozerr** [comment]
I will investigate more, but the thing I don't understand is that it worked before, now? Perhaps you are using last version of vscode which breaks something.

**Comment by angelozerr** [comment]
It works for me?

![image](https://user-images.githubusercontent.com/1932211/45917541-bb730e00-be79-11e8-8667-05329d528a06.png)

**Comment by fbricon** [comment]
I can no longer reproduce the issue. Closing as fixed.
