### ISSUE TITLE
Format XML split attributes with closing tag on new line

### ISSUE THREAD

**Issue by ecool** [redhat-developer/vscode-xml#435]
When working in vscode, I like to use the Alt+Up and Alt+Down keybinding for moving stuff around, and allowing for the ending of the tag to be on a new line if the attributes are aligned would be very helpful.

current:
```xml
<tag
    attr1=""
    attr2="" />

<tag
    attr1=""
    attr2="" >
```
proposed:
```xml
<tag
    attr1=""
    attr2=""
/>

<tag
    attr1=""
    attr2=""
>
```

proposed setting:
`xml.format.splitAttributesCloseNewLine = true` - only use if `xml.format.splitAttributes = true`.

**Comment by angelozerr** [comment]
@fbricon what do you think about this format settings?

@datho7561 do you think it can be easy to implement it?

**Comment by datho7561** [comment]
Its not trivial to implement, since you need to take into account `>` and `/>`, but it looks fairly straightforward.

**Comment by datho7561** [comment]
Also, we would need to decide how formatting with just one attribute is handled

**Comment by ecool** [comment]
@datho7561 it looks like the current setting for `splitAttributes` keeps a single attribute on the line with the tag.
```XML
<tag attr1="" />
```

So, current behavior seems to be only split when more than 1 attribute. Not sure if there should be another setting for a single attribute decision but it does counteract the main reason I was looking into having the ending of the tag be on a new line. (The easy movement/duplication of attribute lines with vscode shortcuts)

If following the understanding of making it easier to manage attributes with the shortcuts (including all line operations), I believe there should be a way to have a single attribute being split to a separate line as well.

**Comment by thet** [comment]
Format suggestion: Indent the closing part the same level the attributes are indented:
```
<tag
    attr1=""
    attr2=""
    />

<tag
    attr1=""
    attr2=""
    >
```

**Comment by AlexXuChen** [comment]
I'm interested in taking this issue.

**Comment by angelozerr** [comment]
Before working on this issue, perhaps we should rewrite the XML formatter (see PR https://github.com/eclipse/lemminx/pull/1044)

@datho7561 what do you think about that?

**Comment by datho7561** [comment]
I think the formatter rewrite will take a while. In the mean time, it would be neat to support this feature. It shouldn't require many changes to the existing formatter to implement this feature.
