### ISSUE TITLE
Auto self-closing feature deletes content

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#440]
Type `/` where the pipe is:

```xml
<foo |

  <baloney></baloney>

</foo>
```

Everything else is deleted:

![SelfCloseDeletesContent](https://user-images.githubusercontent.com/22376627/111826041-98950980-88be-11eb-915f-6744458b05ae.gif)

Expected result:

```xml
<foo />

  <baloney></baloney>

</foo>
```

**Comment by sergey-s-betke** [comment]
But I like this behavior...

**Comment by fbricon** [comment]
@datho7561 so make it a preference
