### ISSUE TITLE
support for *.xslt files

### ISSUE THREAD

**Issue by brainwasher** [redhat-developer/vscode-xml#446]
I am new to VS-Code and installed the extension because I do a lot of XSLT work. The feature I am most looking for is the auto-close. It works out of the box for *.xml but it does nto work for *xslt. In principle, an XSLT file is just another XML file. I did not find any item in the configuration to add file extensions (or languages?) to enable the extension for XSLT as well.

**Comment by angelozerr** [comment]
>  It works out of the box for *.xml but it does nto work for *xslt

The problem that I see with xsl is when you type `<` it generates `<>` and it break the workflow to auto close a tag.

For instance 

 * in XML if you type `<` and after `a` and  after `>` it generates `<a></a>`
 * in XSL if you type `<` it generates `<>` which breaks the previous workflow.

@brainwasher is this issue that you are explaining?

@datho7561 could you see the problem if you have time (I suspect a problem with language configuration).

**Comment by datho7561** [comment]
@brainwasher thanks for submitting this bug!

If you add the following snippet to your `settings.json` (Ctrl+Chift+P > Open Settings (JSON)), it should work. This disables the built-in auto-close for .xslt and replaces it with vscode-xml's auto-close tag support.

```json
"[xsl]": {
  "editor.autoClosingBrackets": "never"
}
```

I'll work on a PR that sets this setting by default.
