### ISSUE TITLE
Support Indentation Of Content Lines

### ISSUE THREAD

**Issue by SilvioMarcovic** [redhat-developer/vscode-xml#448]
Formatting the following XML 
```
<a>
        Test
    Test
        </a>
```
will leave the XML as is.

Is there a way to achieve the following formatting:
```
<a>
    Test
    Test
</a>
```

I would hope for two things to change:
1. Indent the closing tag ```</a>``` on the same depth as the opening tag ```<a>```.
2. Indent the content (2 Test lines) one depth deeper than the opening tags.

I could not find any setting that will indent the content lines and closing tags appropriately.

I could not find any related setting, the closest I could find is
```"xml.format.joinContentLines": true```
which serves a very different purpose of collapsing the content lines into one.

Maybe I missed something, otherwise, I would really appreciate this feature since I have plenty of XMLs with code in their content (OnButtonPress etc ...)

**Comment by datho7561** [comment]
This type for formatting isn't available yet, unfortunately. We would like to support this, however it will take a while to implement. We have decided to focus on other features for right now.
