### ISSUE TITLE
Cannot activate the 'XML' extension because it depends on an unknown 'redhat.vscode-commons' extension.

### ISSUE THREAD

**Issue by sumitsingh-b2b** [redhat-developer/vscode-xml#466]
ERROR - Cannot activate the 'XML' extension because it depends on an unknown 'redhat.vscode-commons' extension.

I have tried installing XML extension using .vsix file (as on my machine, I don't have Internet connectivity ). Kindly assist how can I resolve this.

**Comment by fbricon** [comment]
You need to install [Red Hat Commons](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-commons)

**Comment by sumitsingh-b2b** [comment]
Thanks for the quick response. After installing it, I am able to use XML extension.
