### ISSUE TITLE
Outdated schema file used.

### ISSUE THREAD

**Issue by stebla27** [redhat-developer/vscode-xml#481]
If there is a new schema file available, vscode-xml still uses the old cached version.

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/Commands.md#revalidate-current-xml-file

**Comment by angelozerr** [comment]
@stebla27 can we close this issue?

**Comment by angelozerr** [comment]
@stebla27 I close the issue, if you have some trouble please reopen the issue.
