### ISSUE TITLE
"Bind to grammar/schema..." should be a command available from the palette

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#514]
Currently, "Bind to grammar/schema..." can only be triggered if `xml.codeLens.enabled`is set to `true`. 

<img width="192" alt="Screenshot 2021-06-17 at 16 17 17" src="https://user-images.githubusercontent.com/148698/122414570-8858fd00-cf87-11eb-9b0a-304b4a7e9461.png">

It makes sense to also expose it as a command available from the command palette

**Comment by AlexXuChen** [comment]
Lemminx change: eclipse/lemminx/pull/1084

**Comment by AlexXuChen** [comment]
Should be part of 0.18.0
