### ISSUE TITLE
With `splitAttributes` and `closingBracketNewLine`, indent closing bracket as much as attributes

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#516]
See https://github.com/redhat-developer/vscode-xml/issues/435#issuecomment-833292031

**Comment by datho7561** [comment]
@AlexXuChen We should also document this in Formatting.md

**Comment by AlexXuChen** [comment]
> @AlexXuChen We should also document this in Formatting.md

Sure thing, I can quickly add that.
