### ISSUE TITLE
have an option to make "resolve external entities" depending on workspace trust

### ISSUE THREAD

**Issue by GitMensch** [redhat-developer/vscode-xml#537]
Ideally I'd like to have the setting enabled in trusted workspaces, but be disabled in untrusted workspaces.
Would it be reasonable to switch the current setting from boolean (always/trusted/never) to an enum or should this be a new setting?

**Comment by datho7561** [comment]
Right now, we support making a local config for your workspace (i.e. `.vscode/settings.json`), then settting "resolve external entities" in that folder. The local config only applies if the workspace is trusted.

I think it that it would be neat feature to support the workflow you described instead, though.

**Comment by rgrunber** [comment]
Agreed. If the user has not trusted the workspace we should disable the option (not just at the workspace level).
