### ISSUE TITLE
add command "Restart Language Server"

### ISSUE THREAD

**Issue by GitMensch** [redhat-developer/vscode-xml#539]
... as seen in the Python extension `python.analysis.restartLanguageServer`.

Not a priority at all, but something to possibly consider.

Reasoning: sometimes the server seems to hang and if it doesn't restart its own (which may take some seconds to be triggered, I don't know if there are other cases when this happens apart from "server chrashed") you have three options: a command like this or a manual killing of the process tree (after you've found the correct java process) or (which will loose your undo and position history) the reload window command.

**Comment by AlexXuChen** [comment]
After doing some digging, I've found some references to a VSCode issue:

microsoft/vscode/issues/76405

I'm currently investigating, and it seems doable by simply issuing a deactivate and activate in succession, I am just encountering a weird interaction with restarting the Telemetry service.

**Comment by rgrunber** [comment]
Related to https://github.com/redhat-developer/vscode-xml/issues/540 .

The language server should stop on its own in most cases (client exits). If the client crashes, or is brought down abruptly, the language server may continue to run for at most 30s before finally exiting. A (hacky) solution would be to use the ErrorHandler to restart.

**Comment by GitMensch** [comment]
Sounds good - but the user-provided command can still be added in the meantime, can't it?

**Comment by AlexXuChen** [comment]
> Eventually when we update to [vscode-language-server node client v8](https://github.com/redhat-developer/vscode-xml/pull/715) (had to revert due to lack of support in Theia), we should see if [`restart()`](https://github.com/microsoft/vscode-languageserver-node/commit/f9faf63b7f1acef6a619ac06f78bc3b1bcfed2e2) works. I think Alex will be trying it out to see if it works as expected.

See the fix in https://github.com/redhat-developer/vscode-xml/pull/551#issuecomment-1190528272
