### ISSUE TITLE
Is it possible to have a workspace reference in catalog.xml?

### ISSUE THREAD

**Issue by GitMensch** [redhat-developer/vscode-xml#542]
When we use a vscode setting for the XSD adjustment we can also [reference the workspace](https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xml-file-association-with-xsd).
It would be nice to be able to do the same or something similar in the catalog.xml and use `${workspaceFolder}` or an equivalence there. So far I have nearly the same catalog file in every workspace (the xsd files are all in the same place _below_ the workspace) but need to adjust the root path for each (and "obviously" the catalog is not portable when checked-out to a different place).

I _guess_ one _might_ use a special "key" in the catalog, resolve the workspace folder in this extension and then pass it as the value for the key to the process that actually reads the catalog.

**Comment by fbricon** [comment]
I'm -1 on that. This is not standard XML and would make the catalog only readable by vscode-xml.

**Comment by GitMensch** [comment]
If there's no key option in the standard XML then I'm also -1 on that - but I don't know - if you do it isn't - then definitely let's close the issue.

I've just checked the catalog.xsd - the attributes are always required and always of `type="xs:string"` - so I _guess_ there would be no portable option to have something in there "resolved", is it?
