### ISSUE TITLE
Adding closing bracket (>) in attribute quotation marks is causing repeated auto-complete of closing tag.

### ISSUE THREAD

**Issue by joshuacookdev** [redhat-developer/vscode-xml#547]
When the extension is enabled (v 0.17.0), if you accidentally type your closing bracket inside of the quotation marks:

`<element attribute="value"` (i.e. `<element attribute="value>"`), autocomplete attempts to add the closing tag </element>.

However, it's registering each added closing tag as a new closing bracket and attempting to add more closing tags. This happens repeatedly, and can lead to output similar to the following until the user presses another key:

`<element attribute="value></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element></element>"` (and continues going).

To prevent this behavior, the extension could either:
1. *Not* attempt to auto-close the element in cases where a closing tag is added inside of an attribute value, 
2. Move the curson and place the closing tag outside of the quotation marks, or
2. Limit itself to one closing tag, if possible.

**Comment by joshuacookdev** [comment]
Not an urgent fix, since any input to the text stops the repeated auto-complete, but it's probably not desired behavior. I figure that I'm not the only person who has accidentally attempted to close a tag without having the cursor in the right spot.

**Comment by datho7561** [comment]
This case also causes the issue:

```xml
<root>
  <child attr="value|
</root>
```

then


```xml
<root>
  <child attr="value</|
</root>
```

**Comment by datho7561** [comment]
Thanks for filing this bug! I think this makes sense to fix for the next release, so I've made a PR.
