### ISSUE TITLE
Extension issue

### ISSUE THREAD

**Issue by raju760** [redhat-developer/vscode-xml#552]
- Issue Type: `Bug`
- Extension Name: `vscode-xml`
- Extension Version: `0.17.0`
- OS Version: `Windows_NT x64 10.0.10240`
- VS Code version: `1.59.0-insider`

:warning: We have written the needed data into your clipboard. Please paste! :warning:

**Comment by angelozerr** [comment]
@raju760 could you give us more information with your bug please?

**Comment by angelozerr** [comment]
I close the issue. @raju760 please reopen if you need some help by adding more information.
