### ISSUE TITLE
Infinite Closing Tag in Attribute

### ISSUE THREAD

**Issue by InvncibiltyCloak** [redhat-developer/vscode-xml#559]
If you type a right angle bracket while in an attribute (or probably any quoted item) the autocompletion tries to close the tag. For some reason, it then attempts to close the tag again (perhaps because of seeing another right angle brace that it just added) which leads to an infinite loop of tag closing.

Steps to reproduce:
1. Open a new XML file and save to disk (so autocomplete works fully).
2. Type the following into the document: `<to infinity=">`
3. Watch as autocomplete enters the string `</to>` endlessly.

**Comment by fbricon** [comment]
I'd say it's a duplicate of #547. Please try the latest CI build to check (see https://github.com/redhat-developer/vscode-xml#contributing)

**Comment by InvncibiltyCloak** [comment]
Yes this is a duplicate and it is fixed in the latest staging.
Apologies for not finding that.
