### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by sheetalbhagat63** [redhat-developer/vscode-xml#583]
- Issue Type: `Performance`
- Extension Name: `vscode-xml`
- Extension Version: `0.18.0`
- OS Version: `Windows_NT x64 10.0.19041`
- VS Code version: `1.59.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\hp\AppData\Local\Temp\redhat.vscode-xml-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by angelozerr** [comment]
Could you retrouvez with last vesion of vscode xml. If you have problem agàin could you please share your xml and explain what you are doing. Thanks
