### ISSUE TITLE
Format CDATA sections without adding new lines

### ISSUE THREAD

**Issue by kapexx** [redhat-developer/vscode-xml#585]
I work with XML documents that contain a lot CDATA sections. These are mostly used for content that has to contain some exact value and is sensitive to whitespace changes.

When I use the formatter to format the document, an element like this:

    <Payload><![CDATA[x < y]]></Payload>

becomes this:

    <Payload>
        <![CDATA[x < y]]>
    </Payload>

In many cases the added newlines are fine (e.g. if the content is canonicalized or if additional whitespace doesn't matter) but I have to send the document to a system that is very picky about whitespace and doesn't process the element correctly because of the additional newlines.

Another case (this one is fictional though) where this is an issue, is using CDATA for xs:enumeration values. For example, if we have an enumeration that allows values like "<" and ">":

    <Operator><![CDATA[<]]></Operator>

is valid, but when formatting it becomes invalid:

    <Operator>
        <![CDATA[<]]>
    </Operator>

which results in an error:

    Value '
    					<
    				' is not in the enumeration list.

Of course for these small examples, using entities instead CDATA would work. In other cases that's not always feasible though. Is there an option to avoid adding newlines around CDATA sections? I think at least for the second example, where formatting breaks the document, an option like that would be justified.

**Comment by jonsmirl** [comment]
Please don't insert white space around `<![CDATA[]]>` inside `<xsl:text></xsl:text>`
```
        <xsl:if test='position()=1'>
            <xsl:text><![CDATA[// Prevent multiple inclusion
                #pragma once
                
                #include <app-common/zap-generated/ids/Clusters.h>
                #include <app-common/zap-generated/ids/Commands.h>
                
                #include <controller/CHIPCluster.h>
                #include <lib/core/CHIPCallback.h>
                #include <lib/support/Span.h>
                
                namespace chip {
                namespace Controller {
                
]]></xsl:text>
        </xsl:if>

don't reformat this to:

        <xsl:if test='position()=1'>
            <xsl:text>
                <![CDATA[// Prevent multiple inclusion
                #pragma once
                
                #include <app-common/zap-generated/ids/Clusters.h>
                #include <app-common/zap-generated/ids/Commands.h>
                
                #include <controller/CHIPCluster.h>
                #include <lib/core/CHIPCallback.h>
                #include <lib/support/Span.h>
                
                namespace chip {
                namespace Controller {
                
]]>
            </xsl:text>
        </xsl:if>
```

**Comment by jonsmirl** [comment]
As a work around, disable formatting in the Redhat extension. And install this which will use xmllint to format.
https://marketplace.visualstudio.com/items?itemName=SteefH.external-formatters

```
		"externalFormatters.languages": {

			"xml": {
				"command": "xmllint",
				"arguments": [
					"--format",
					"-",
				]
			},
			"xsl": {
				"command": "xmllint",
				"arguments": [
					"--format",
					"-",
				]
			},
		}
```

**Comment by beMananas** [comment]
Is there already information here if/when this could be fixed?

**Comment by angelozerr** [comment]
No sorry we must redo our formatter to fix this kind of problem

**Comment by angelozerr** [comment]
@JessicaJHee I think experimental formatter fix this issue?

**Comment by JessicaJHee** [comment]
![Peek 2022-12-09 14-43](https://user-images.githubusercontent.com/73968480/206784259-692610b9-35ab-44e7-bf4b-7662f2903703.gif)

Yes, it no longer inserts the new line when formatted.

**Comment by angelozerr** [comment]
Thanks @JessicaJHee for your feedback.

@jonsmirl @kapexx please install prerelease https://github.com/redhat-developer/vscode-xml#contributing to enjoy with this fix or wait for the release which will come soon.
