### ISSUE TITLE
Contribute to vscode-xml with a custom language

### ISSUE THREAD

**Issue by petrvanecek** [redhat-developer/vscode-xml#589]
I have a language that is based on XML. Is it possible to somehow make VS Code language extension that would use the provided XSD based on file extension with all the functionality provided from RedHat Xml extension? Something like:

```json
	"contributes": {
		"languages": [
			{
				"id": "fprg",
				"extensions": [
					".fprg"
				],
				"configuration": "./language-configuration.json"
			}
		],
		"grammars": [
			{
				"language": "fprg",
			        >>>"path": "./syntaxes/fprg.XSD"
			}
		],
		"snippets": [
                      {
                               "language": "fprg",
                               "path": "./snippets/fprg.snippets.json"
                     }
                ]
       }
```
Similar behavior as:
```json
    "xml.fileAssociations": [                    
       {
         "pattern": "**/*.fprg",
         "systemId": "${workspaceFolder}fprg.xsd"
       }
    ],
``` 
but packed into a language extension with snippets and other possibilities of language extension.

**Comment by angelozerr** [comment]
This issue requires 2 development:

 * as vscode doesn't provide the capability to extend language, we need to give the capability to declare in the package.json of custom vscode extension that a given language belongs to xml language. We did that in MP LS and I hope HTML will do that. See https://github.com/microsoft/vscode/issues/131531 for more explanation.

 * today `xml.fileAssociations` is declared only with user settings, the idea is to declare it in the package.json of custom vscode extension like JSON support does https://code.visualstudio.com/docs/languages/json#_mapping-a-schema-in-an-extension
