### ISSUE TITLE
Prevent `splitAttributes` from splitting elements with one attribute

### ISSUE THREAD

**Issue by alessandrodimarco** [redhat-developer/vscode-xml#59]
When `splitAttributes` is enabled, elements with one attribute get split onto multiple line. For example:
```
<myelement key="some_key">hellow</myelement>
```
becomes
```
<myelement
          key="some_key">hellow</myelement>
```

The `splitAttributes` comment says it will split multiple attributes onto a new line. I'm not sure if this is the expected behavior but it would nice to have elements with one attribute stay on the same line.
```
// Split multiple attributes each onto a new line
"xml.format.splitAttributes": true,
```

**Comment by NikolasKomonen** [comment]
@alessandrodimarco Thanks for pointing this out, you're right. It'll be fixed in the next release.
