### ISSUE TITLE
Support platform specific extension

### ISSUE THREAD

**Issue by heartacker** [redhat-developer/vscode-xml#593]
```
Server binary download failed: certificate signature failure. Cannot start XML language server, since Java is missing.
```

some like c/c++, https://github.com/microsoft/vscode-cpptools/releases
please provide the offline package for specify platform. OR provide a package that contains all platform server execute file.
thanks

**Comment by fbricon** [comment]
That's an interesting possibility, though we're actually eagerly waiting for platform-specific vsix support from upstream vscode/marketplace: https://github.com/microsoft/vscode/issues/23251

**Comment by heartacker** [comment]
> That's an interesting possibility, though we're actually eagerly waiting for platform-specific vsix support from upstream vscode/marketplace: https://github.com/microsoft/vscode/issues/23251

thsnks, Maybe now you can provide a package that include all perform executefile before that has implemented for nowadays

**Comment by rgrunber** [comment]
Yup, this should be possible now with https://code.visualstudio.com/api/working-with-extensions/publishing-extension#platformspecific-extensions . Looks like we just need to use npm_config_arch and --target for the vsce package command.

**Comment by heartacker** [comment]
hope that we could earn this soon

**Comment by heartacker** [comment]
thanks you @rgrunber

**Comment by GitMensch** [comment]
I'm a bit confused. Is there still an automatic download of the binary as mentioned in https://github.com/redhat-developer/vscode-xml#requirements?
https://github.com/redhat-developer/vscode-xml/releases/tag/0.21.0 says:

> Use platform specific .vsix files, and package the lemminx binary into the .vsix

?!?

**Comment by rgrunber** [comment]
We'll need to update the documentation there.

If installing through VS Code and your platform is detected as one of : `linux-x64`, `win32-x64`, `darwin-x64`, or `darwin-arm64`, then the vsix that will be installed is specific to that platform. If you're on another platform, you'll get the generic vsix, which will download the lemminx binary.

I think we can add the vsix files as well to the release tab. They're [archived as part of the build](https://github.com/redhat-developer/vscode-xml/blob/master/Jenkinsfile#L102) so we can copy them over.
