### ISSUE TITLE
sch-props-correct.2: A schema cannot contain two global components

### ISSUE THREAD

**Issue by onettmecha** [redhat-developer/vscode-xml#594]
hello everyone,
# problem scope
i've created a project where XML is used for views and i get the following issue 
![image](https://user-images.githubusercontent.com/72963129/133862843-f1fbd18d-caf6-4ba8-9411-ba69de3a9b49.png)
and since i know nothing about XML, i've asked [codename one's support](https://codenameone.com) about it and now i'm asking it here, so help please.

# system specs
OS: ArcoLinux 
Kernel: 5.14.5-arch1-1 
Shell: bash 5.1.8 
Resolution: 1920x1080 
DE: GNOME 40.4 
Terminal: termite 
CPU: Intel i5-7500 (4) @ 3.800GHz 
GPU: Intel HD Graphics 630 
Memory: 4276MiB / 7835MiB (54%)

# steps to reproduce
## prerequisites 
- java8-openjdk
- maven
## steps
1. create and download a CodeRAD project from https://start.codenameone.com
2. open the project and run `mvn clean compile` on the `-common` project
3. you should have the issue now

# expected behaviour
there shouldn't be any issues with the project and it should compile without errors

**Comment by angelozerr** [comment]
The `StartPage.xsd` used in the XML is wrong and vscode-xml report thoses errors.

 * `<?xml version="1.0"?>` is declared several times, it should be declared only on the root:
![image](https://user-images.githubusercontent.com/1932211/133883156-1ab8ba7a-c57d-43c9-9f5e-0a5ebead803d.png)

to fix that remove all `<?xml version="1.0"?>`, once you did that, you will see new errors (that you seeon your StartPage.xml). There are duplicat eof the same name in xs:simpleType, etc

![image](https://user-images.githubusercontent.com/1932211/133883246-eb721a48-4e3e-4cd0-b4cc-5d609eef11bd.png)

Please report those problem to https://start.codenameone.com

**Comment by onettmecha** [comment]
@angelozerr 
so this issue is the cause of codename one' boilerplates and has nothing to do with vscode or xml extension, correct?

**Comment by angelozerr** [comment]
Yes exactly. The xsd is wrong and vscode xml report errors

**Comment by onettmecha** [comment]
@angelozerr 
thanks..i should note that i installed Intellij IDE just to see if it produces the same issue but it doesn't, everything is working perfectly there. does this mean that `vscode xml` extension could be grown to accommodate the schemas generated by codename one boilerplates?

**Comment by angelozerr** [comment]
In IJ you can see the same errors with validate menu:

![image](https://user-images.githubusercontent.com/1932211/133906038-b99f6b53-9a31-47af-8af2-8431ecf952f6.png)

You will see problem with duplicate <?xml version="1.0"?> and if you remobe them, you will see the newt problems.

**Comment by onettmecha** [comment]
@angelozerr correct, thanks for your time and effort.
i'll track the issue with codename1 support from here on after.

**Comment by angelozerr** [comment]
> @angelozerr correct, thanks for your time and effort.

You are welcome! Hoep you will enjoy with vscode-xml.
