### ISSUE TITLE
Ensure the extension works with a proxy

### ISSUE THREAD

**Issue by NikolasKomonen** [redhat-developer/vscode-xml#60]
Enable the server to be started with proxy values if they exist.

Existing default vscode preferences already there for proxy information.
Just search proxy in preferences.

**Comment by fbricon** [comment]
Should be covered by #61 . But we need to be able to check it. @snjeza can help test that kind of thing hopefully ;-)

**Comment by fbricon** [comment]
please add that to the wiki

**Comment by NikolasKomonen** [comment]
Ill do it

**Comment by snjeza** [comment]
A proxy with a password won't work if https://github.com/angelozerr/lsp4xml/pull/171 isn't applied.
