### ISSUE TITLE
Format is wrong with multiple line content

### ISSUE THREAD

**Issue by Tacha-S** [redhat-developer/vscode-xml#600]
Indent of close tag for multiple line content is wrong.

The XML file for example as shown below.
```xml
<a>
  <b>
    foo
    bar
  </b>
</a>
```

Format the XML file with this plugin.
```xml
<a>
  <b>
    foo
    bar
</b>
</a>
```

Is this correct behavior?

**Comment by angelozerr** [comment]
> Is this correct behavior?

No our XML formatter must be improved.

**Comment by angelozerr** [comment]
The https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatexperimental should fix this issue. Here the result:

```
<a>
	<b> foo bar </b>
</a>
```

@JessicaJHee could you write a test with this usecase please.
