### ISSUE TITLE
Java error: ENOENT: no such file or directory, lstat '../libexec/openjdk.jdk/Contents/Home/bin/java'

### ISSUE THREAD

**Issue by pjlsergeant** [redhat-developer/vscode-xml#601]
The project proudly exclaims:

`NO LONGER REQUIRES JAVA! since v0.15.0`

However, attempting to install v0.18.0 from inside VS Studio Code gives me an Error in Runtime Status:

`ENOENT: no such file or directory, lstat '../libexec/openjdk.jdk/Contents/Home/bin/java'`

My Java knowledge is non-existant, but that sure looks like it's trying (and failing) to load Java? Any pointers?

**Comment by rgrunber** [comment]
Interesting that https://github.com/redhat-developer/vscode-quarkus/issues/403#issuecomment-937615201 has the exact same error. I suppose the only thing in common is their Java finding logic.

Both issues seem to be happening on MacOS. Could the installed directory structure be a little different there and we're not handling some case correctly ?
