### ISSUE TITLE
wrap element around xml with schema based suggestions

### ISSUE THREAD

**Issue by otichy** [redhat-developer/vscode-xml#605]
It would be great to have the oXygen like ability to wrap a selected text with an xml element. 

This is currently partly implemented in VS Code as "Emmet: Wrap with abbreviation" command, but it lacks suggestions/completion based on the associated schema.

**Comment by angelozerr** [comment]
Could you give us more explanation about this feature please.

**Comment by angelozerr** [comment]
Sorry there is no XML and XSD attached.

**Comment by otichy** [comment]
Sorry, but this is a general remark, not about a specific XML file or a specific XSD. Maybe if what I am saying is not clear, try opening any XML in VSCode, select a piece of text and use the "Emmet: Wrap with Abbreviation" in the Command Palette. This is exactly what I am looking for, but instead of manually entering the element name, I would like a selection of valid element names based on an attached schema.

**Comment by angelozerr** [comment]
Indeed it should be nice to have that, but I don't know when we will have time to implement it.

I think we should implementing an Emmet engine on XML Language server side to provide emmet support but based on XSD, DTD. It's a very long and hard task.

**Comment by otichy** [comment]
OK, it seemed simple for a user perspective, since schema based suggestions for tag completion is already implemented, but I know that the developer perspective may be very different here. Thanks for looking into it and perhaps one day!

**Comment by angelozerr** [comment]
The main problem is that Emmet support from vscode is not customizable; we have not the capability to say "hey please provides those given elements"

It means that we must re-implement Emet support inside the XML Language Server which is written in Java (although Emet is written in JS)

**Comment by otichy** [comment]
Right, that does not sound good. However, I gave the emmet function just as an example of how it should work, but it certainly does not have to be implemented through that. If you could just make VScode wrap an element with an element whose name would be selectable from valid schema based choices, maybe emmet does not have to be involved at all.
