### ISSUE TITLE
Formatting changes whitespace

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#610]
First of all, I hope I really use the formatter provided by this package. I don't know how to find out. I think I use it because changing settings like `xml.format.emptyElements` changes the formatting.

My document:

```xml
<root>
	<sub>contents sub<subsub ></subsub></sub>
</root>
```

Now I run the command `Format Document`, the document changes to:

```xml
<root>
    <sub>
        contents sub
        <subsub />
    </sub>
</root>
```

which introduces whitespace before and after `contents sub`. How can I switch off this whitespace? I'd expect that the "whitespace only" text nodes should be allowed to be formatted. (via a setting perhaps).

I have set `"xml.format.joinContentLines": false,` in `settings.json` but changing this to true does not make any difference.

**Comment by angelozerr** [comment]
I suggest that you try the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental
