### ISSUE TITLE
trailing whitespace is removed from text content even when xml.format.preserveEmptyContent is set

### ISSUE THREAD

**Issue by seansfkelley** [redhat-developer/vscode-xml#611]
Minimal repro: `<foo> </foo>` correctly preserves all whitespace, while `<foo> bar </foo>` is erroneously transformed to `<foo> bar</foo>` (but notice the leading whitespace is preserved).

This is on version 0.18.0.

If you're interesting in the use-case for this, I often use VS Code to poke around DOCX files, which are XML internally. Text in a Word document is represented with nodes like `<w:t xml:space="preserve">foobar </w:t>`, so as you can imagine, the trailing whitespace is often significant.

**Comment by angelozerr** [comment]
@seansfkelley this issue should be fixed now with our new formatter. Please note that we take care of `xml:space="preserve"` too.

Please install last version of vscode-xml  0.23.0.
