### ISSUE TITLE
Improve xsd-based quick-fix suggestions

### ISSUE THREAD

**Issue by mengineerchen** [redhat-developer/vscode-xml#618]
Hi, it would be nice if xsd-validation-based quick-fixes can be as intelligent as auto-completion.

A trivial example here, given xsd says, the value should be taken from **an ordered list {Less, Greater}**.

Auto-completion is doing a good job:
![autocopmletion](https://user-images.githubusercontent.com/33261984/140640676-4a80adb8-2ac1-4609-ac33-c132ed5ea3ff.png)

Quick fix suggestion takes the original ordered list. If the list could be re-ordered based on match degrees, it would be awesome!
![quickfix](https://user-images.githubusercontent.com/33261984/140640677-75f2f394-8c66-45ec-b12e-85d9c2af69ba.png)

Perhaps I missed something existing? Please let me know :smiley:

**Comment by angelozerr** [comment]
When XML doesn't declare the proper name, (ex : type `Opertor`), it should show a code action like `Did you mean 'Operator'?`. I think we should have this same feature with enum.

**Comment by AlexXuChen** [comment]
@mengineerchen Could you provide an example of how to recreate this quick fix suggestion?

**Comment by angelozerr** [comment]
@AlexXuChen  I think you can use one of XSD that we are using for test https://github.com/eclipse/lemminx/blob/master/org.eclipse.lemminx/src/test/resources/xsd/dressSize.xsd

See test which use this xsd https://github.com/eclipse/lemminx/search?q=dresssize

**Comment by mengineerchen** [comment]
Happy to see the progresses there on https://github.com/eclipse/lemminx/pull/1136! Now I am really looking forward to the next extension release.

**Comment by angelozerr** [comment]
@mengineerchen please note the pr from @AlexXuChen use the same "similar" feature "Did you mean ...?" than tag name. In other words it will not have the same bahavior than completion which is managed by vscode itself.

**Comment by mengineerchen** [comment]
> @mengineerchen please note the pr from @AlexXuChen use the same "similar" feature "Did you mean ...?" than tag name. In other words it will not have the same bahavior than completion which is managed by vscode itself.

Good to know. If “Did you mean ...?" does not find some option to prompt, would it fall back to “Replace with ..." pattern?

**Comment by angelozerr** [comment]
Yes its exactly that. You can test this behavior already with tag name.
