### ISSUE TITLE
Search for XSD files in the local file system

### ISSUE THREAD

**Issue by i-and** [redhat-developer/vscode-xml#622]
In my case, the tags `xsi:schemaLocation` and `xsi:noNamespaceSchemaLocation` are used to associate XML and XSD. In this case, the link to the xsd file is set as a local relative path: `../../schemas/xml_check 1.xsd`. I would like to get away from binding to the file structure. 

In this regard, the suggestion is to implement the ability to configure the search paths of XSD files (by analogy with the gcc -I argument).

**Comment by angelozerr** [comment]
I think you should use [XML catalog](https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#XML-catalog-with-XSD) for that.

**Comment by i-and** [comment]
@angelozerr, thanks for the quick response! Do I understand correctly that the catalog that is specified with 
~~~
<catalog xmlns="urn:oasis:names:tc:entity:xmlns:xml:catalog">
  <uri
      name="http://foo"
      uri="./foo.xsd" />
</catalog>
~~~
it only works for variant with `xsi:schemaLocation`, but it is not applicable for `xsi:noNamespaceSchemaLocation` because it requires a namespace name from XML?

**Comment by angelozerr** [comment]
> it only works for variant with xsi:schemaLocation, but it is not applicable for xsi:noNamespaceSchemaLocation because it requires a namespace name from XML?

I'm not an expert with XML catalog, but I think so.

If you don't want to declare xsi:schemaLocation or xsi:noNamespaceSchemaLocation in your XML you can use too [file association](https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#xml-file-association-with-xsd).

To use it, I suggest that you [enable codelens](https://github.com/redhat-developer/vscode-xml/blob/master/docs/Features/XMLFeatures.md#codelens) to benefit with `Bind to grammar/schema`

**Comment by angelozerr** [comment]
@i-and is file association can help you?

**Comment by i-and** [comment]
@angelozerr thank you. I managed to use the `XML catalog` option and switch to using `xsi:schemaLocation` instead of `xsi:noNamespaceSchemaLocation`. 

Is it possible to implement the possibility of referring to a catalog-file("xml.catalogs": [ ... ]) by specifying an environment variable (currently only a constant string is possible). This would allow storing a common configuration file `settings.json` for different projects/users under Git.

**Comment by angelozerr** [comment]
> Is it possible to implement the possibility of referring to a catalog-file("xml.catalogs": [ ... ]) by specifying an environment variable

No, the only non static that you we manage today is for file association https://github.com/redhat-developer/vscode-xml/blob/master/docs/Validation.md#XML-file-association-with-xsd

**Comment by i-and** [comment]
I realized that at the moment there is no such possibility. It was a proposal to modify the XML extension.

**Comment by angelozerr** [comment]
Could you create a new issue please by adding some detailed sample. Thanks!
