### ISSUE TITLE
Disable formatting for next/following lines

### ISSUE THREAD

**Issue by PJUllrich** [redhat-developer/vscode-xml#624]
Dear maintainers,

is there a way to tell the XML formatter to ignore the next, or even the next few lines?

My problem is that I want to save some HTML code in a XML tag as simple text (it might not be a supported use-case and I would fully understand if you'd reject this request on these grounds of course).
Unfortunately, the formatter interprets the HTML tags as XML tags and removes most of the code. Could I add a comment like `ignore-line` or something to tell the formatter to ignore the HTML code?

Thank you very much in advance!

**Comment by fbricon** [comment]
Can you provide a sample document?

**Comment by PJUllrich** [comment]
Thank you for your super quick reply! Sorry, but I actually have some HTML+Elixir code (think JSX) and it formats the HTML code well, but doesn't understand the Elixir code and falls back to `<null>` tags. Here's an example:

What I need:
```xml
<message>
  <!-- I'd like to ignore all this -->
  <table>
    <tbody>
      <%= for el <- @elements do %>
        <tr>
            <td><%= el.id %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <!-- Until here -->
</message>
```

What I get after formatting:
```xml
  <message>
    <table>
      <tbody>
        <null
          <null>
            <tr>
              <td>
                <null>
              </td>
            </tr>
          <null>
      </tbody>
    </table>
  </message>
```

So, if there was an easy way to tell the formatter to ignore the next X lines, I'd be very happy. But of course, it that's not possible or too much work, I'll try to find a workaround.

**Comment by angelozerr** [comment]
It's the same issue than https://github.com/eclipse/lemminx/issues/1041

We need to redo our XML formatter from scratch, but it's a lot of work I think.

**Comment by PJUllrich** [comment]
Yes, that seems indeed to be the same issues. Thank you for the info. I will workaround it for now by disabling the formatter. I'll watch this and the other issue though for the case that you decide on rewriting everything 😄

**Comment by angelozerr** [comment]
@fbricon we have more and more users who complain with the xml formatter. It should be perhaps good to provide a settings to disable formatting by waiting formatter improvement.

What do you think about that?

**Comment by clementnuss** [comment]
as an end user that would be really profitable, for the moment I have to disable formating for documents where  I use macros to insert e.g. credentials (what lemminx considers as unknown content). commenting to show the interest and to get notified of future improvements :)

**Comment by angelozerr** [comment]
@fbricon @rgrunber @AlexXuChen I think we should provide this setting

**Comment by angelozerr** [comment]
I forgot that we can disable formating with https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatenabled

After reading this issue its not a trivial issue so im not sure we will implement quickly

**Comment by angelozerr** [comment]
@PJUllrich @clementnuss please note we have implemented an experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental which should not remove comment like <%
