### ISSUE TITLE
'No definition found' when using 'Go to Definition' for types defined in imported XSD 

### ISSUE THREAD

**Issue by jawn** [redhat-developer/vscode-xml#632]
## Summary

Go to definition works to navigate to a complex type defined in the same XSD.
However, this fails when the complex type is defined in an imported file, giving error message 'No definition found for ...' 

## Steps to reproduce

1. Unzip repro files to local folder, that is a trusted workspace
2. Open Parent.xsd in VS Code
3. Apply go to definition on line 11, 'SomeGenericType'. 

## Actual result:
![image](https://user-images.githubusercontent.com/1705112/147955880-f8c24d12-7ffd-4b0c-9fe8-463f3f000ddb.png)

## Expected result

The type definition is selected in the Child.xsd file.

## Repro files 
[repro.zip](https://github.com/redhat-developer/vscode-xml/files/7802967/repro.zip) containing Parent.xsd and Child.xsd

## VS Code version info

Version: 1.63.2 (system setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z (2 wks ago)
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

## Extension version info

XML: v0.18.2
Red Hat Commons: v0.0.6

**Comment by angelozerr** [comment]
Thanks @jawn for your detailed issue. https://github.com/eclipse/lemminx/pull/1146 should fix your issue

**Comment by angelozerr** [comment]
@jawn you can install last vesrion of vscode-xml by downloading vsix https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D and give us feedback. Thanks

**Comment by jawn** [comment]
> @jawn you can install last vesrion of vscode-xml by downloading vsix https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D and give us feedback. Thanks

Verified as fixed using version vscode-xml-0.18.3-472.vsix

**Comment by angelozerr** [comment]
Great thanks @jawn !
