### ISSUE TITLE
No way to format document symbols and outline with custom symbol filters

### ISSUE THREAD

**Issue by twoseascharlie** [redhat-developer/vscode-xml#633]
There doesn't appear to be a way to control the way custom symbol filter rules are displayed in the outline.

Ex:
using this config:
```json
        {
            "pattern": "build*.xml",
            "expressions" :[
                {
                    "xpath": "//target/@name"
                },
                {
                    "xpath": "//text()"
                }
            ]
        }
```

If I have a symbol filter for text, it is shown next to the element in the outline:

![text](https://user-images.githubusercontent.com/6892694/148571985-9355d40d-ba83-4d8b-b594-5cff99bb740a.jpg)

If I have a symbol filter for an attribute, it is shown as a child element in the outline:

![targetAttribute](https://user-images.githubusercontent.com/6892694/148572033-919d99ab-1722-4d73-900e-eeadd1b00e7d.jpg)

For an extension that has great customizability, this seems like a missing customization point. I would love the ability to move the attribute in the outline to the same line as the xml element.

**Comment by angelozerr** [comment]
What is your suggestion to customize that?

**Comment by twoseascharlie** [comment]
I think I would see it working 1 of 2 ways:

Option 1:
Introduce a new preference that allows for single attribute symbol filters to be on the same line as their element.
ex:
`xml.symbols.filters.singleAttributePosition: 'sameLine' | 'nestedLine'`

Or
2. Introduce a new "format" field to the "expression" object for attribute selectors that could control the position and whether to show the attribute value only (and not the attribute name).
ex:
```json
        {
            "pattern": "build*.xml",
            "expressions" :[
                {
                    "xpath": "//target/@name",
                    "format": 
                            {
                                // keep the value of the attribute "name" on the same line
                                // as the target element, and only show the attribute value
                                "position": "sameLine",
                                "valueOnly": true
                            }
                },
                {
                    "xpath": "//text()"
                }
            ]
        }
```

Example mocked up screenshot:

![targetAttribute2](https://user-images.githubusercontent.com/6892694/148578057-916697f0-b50c-421e-8b1e-96286b38eafb.jpg)

I would think this specific case would only be applied when there is only 1 attribute being shown in the outline. For cases where there is more than 1 attribute, I certainly understand it making sense to show them nested under their elements.

For my specific use of this, it would be very helpful to be able to quickly see all the target names in my build.xml file (and it would be nice for all the property names too). But I could certainly see this kind of customization point being useful for other xml based files as well.

**Comment by angelozerr** [comment]
Ok I see the idea thanks. For the moment, I don't know where we will able to implement this feature.

**Comment by twoseascharlie** [comment]
Ok sounds good, I appreciate you taking a look at this :)

**Comment by twoseascharlie** [comment]
Closing this issue as this has been implemented with:
#636
[eclipse/lemminx/#1151](https://github.com/eclipse/lemminx/pull/1151)
