### ISSUE TITLE
multiple root elements

### ISSUE THREAD

**Issue by florenso** [redhat-developer/vscode-xml#634]
The formatter does not include an new line if there are multiple root elements. I think its inconsistent because it does add them for nested elements.

```
<parent>
    <child>
        Text
    </child>
    <child>
        Text
    </child>
</parent>
<parent>
    <child>
        Text
    </child>
</parent>
```
is formated as
```
<parent>
    <child>
        Text
    </child>
    <child>
        Text
    </child>
</parent><parent>
    <child>
        Text
    </child>
</parent>
```

it even becomes worse with empty root elements
```
<foo />
<bar />
<fizz />
<buzz />
```
becomes
```<foo /><bar /><fizz /><buzz />```

**Comment by angelozerr** [comment]
I agree. Is there any chance to have some contribution?

**Comment by angelozerr** [comment]
The https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatexperimental should fix this issue, here the format result:

```xml
<parent>
	<child> Text </child>
	<child> Text </child>
</parent>
<parent>
	<child> Text </child>
</parent>
```

And for teh scond, it keep like this:

```xml
<foo />
<bar />
<fizz />
<buzz />
```

@JessicaJHee could you write 2 tests with those usecases please.
