### ISSUE TITLE
quick fix: add missing child elements

### ISSUE THREAD

**Issue by GitMensch** [redhat-developer/vscode-xml#648]
On the error "child elements are missing from element" (cvc-complex-type.2.4.b) there is "no quickfix available".
It would be nice to have one "add all mandatory elements".

**Comment by angelozerr** [comment]
Indeed it should be nice, but I don't know when we will have time to implement it.

**Comment by rgrunber** [comment]
This was addressed in https://github.com/eclipse/lemminx/issues/1218 . Thanks again @JessicaJHee !
