### ISSUE TITLE
Where can I create new XSD?

### ISSUE THREAD

**Issue by EmilySeville7cfg** [redhat-developer/vscode-xml#653]
Where can I find smth like [this repo](https://github.com/SchemaStore/schemastore) but for XSD/DTD?

**Comment by fbricon** [comment]
See https://github.com/redhat-developer/vscode-xml/blob/master/docs/BindingWithGrammar.md#generate-xsd-from-xml

**Comment by angelozerr** [comment]
No answer, if the answer of @fbricon is not enough please reopen the issue.
