### ISSUE TITLE
Error : "Couldn't start client XML Support"

### ISSUE THREAD

**Issue by revollat** [redhat-developer/vscode-xml#654]
I have this xml and when I open it with vscode I got this error : "Couldn't start client XML Support"
I'm using version v0.18.3 and I checked server:prefer binary in the settings ...
anyone can help me please ?

thanks :)

```xml
<?xml version="1.0"?>
<serializer xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/symfony/serializer/6.0/Mapping/Loader/schema/dic/serializer-mapping/serializer-mapping-1.0.xsd">
    <class name="App\Entity\Product\Product">
        <attribute name="minimalQuantityResolver">
            <group>admin:product:read</group>
        </attribute>
    </class>
</serializer>
```

**Comment by angelozerr** [comment]
Could you enable xml trace https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file and share your trace please

**Comment by angelozerr** [comment]
@revollat could you try with last vesion of vscode-xml? If you have again the problem could you share your traces please.

**Comment by angelozerr** [comment]
No answer. I close the issue. If you have again a problem please reopen it.
