### ISSUE TITLE
Crash Extension host (LocalProcess) terminated unexpectedly. Code: 134, Signal: null

### ISSUE THREAD

**Issue by vcioffi** [redhat-developer/vscode-xml#657]
Issue Type: <b>Bug</b>

Just using the Editor 

Extension version: 0.18.3
VS Code version: Code 1.64.1 (d6ee99e4c045a6716e5c653d7da8e9ae6f5a8b03, 2022-02-07T17:16:22.147Z)
OS version: Windows_NT x64 10.0.19042
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz (8 x 2112)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|15.63GB (4.98GB free)|
|Process Argv|--crash-reporter-id 57d12ea7-a97b-4c3d-a6a0-77f22552301e|
|Screen Reader|no|
|VM|40%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593:30376534
vsc1dst:30433059
pythonvs932:30410667
wslgetstarted:30433507
vscop453:30404998
vsrem710cf:30416617

```

</details>

**Comment by angelozerr** [comment]
Could you enable xml trace https://github.com/redhat-developer/vscode-xml/blob/master/docs/Troubleshooting.md#no-support-on-xml-file and share your trace please

**Comment by angelozerr** [comment]
Could you try with 1.9.1 if you have the same problem?

**Comment by angelozerr** [comment]
No answer. I close the issue. If you have again a problem please reopen it.
