### ISSUE TITLE
no code completion on nested xml elements

### ISSUE THREAD

**Issue by ehigiepaul** [redhat-developer/vscode-xml#66]
Good day,
I will like to report an issue I noticed.

I  created a custom xsd schema for a xml file. Am using Vscode with your vscode-xml extension.

The schema works for only the top elements giving me all its attributes from my xsd file but not on the nested elements in the xml file.

I used the same xsd schema file in Jetbrain Intellij and it worked fine.

Here is an example of my issue.
![xml_schema_error2](https://user-images.githubusercontent.com/8577824/47615961-ca6f6080-dab6-11e8-8c35-61ba08dfa68a.gif)

I will really appreciate it if you could solve this problem in vscode for me. Thanks

And nice work on this project.

**Comment by angelozerr** [comment]
@ehigiepaul I improved XML Schema in server but I don't know if vscode-xml use it.

Please share your xml + schema in order I reproduce your problem. Thanks!

**Comment by ehigiepaul** [comment]
Please find attached are the files i used 

[kll Page.zip](https://github.com/redhat-developer/vscode-xml/files/2522788/kll.Page.zip)

**Comment by fbricon** [comment]
Can you please share your file association settings? Also, give the latest [vsix build](http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D) a try.

**Comment by fbricon** [comment]
Latest build gives even different errors, no completion at all:

<img width="1369" alt="screen shot 2018-10-28 at 10 48 29 am" src="https://user-images.githubusercontent.com/148698/47617594-229a6880-da9f-11e8-83fe-c7eabf31a5ed.png">

Look like a severe regression server-side

**Comment by ehigiepaul** [comment]
I got the same issue. I solved that by
replacing this line

>`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://schemas.nativescript.org/tns.xsd" id="tns" targetNamespace="http://schemas.nativescript.org/tns.xsd" elementFormDefault="qualified" attributeFormDefault="unqualified">`

with this

>`<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">`

Just remove the namespace and targetNamespace attributes from the xsd file

But i still get the swirling line on the Page tag, I get completion on the top element but still not on the  nested.

**Comment by angelozerr** [comment]
Please create an issue at https://github.com/angelozerr/lsp4xml/issues 

I suspect the use of xs:extension causes the problem (perhaps which is not supported?), but I have not sure.

**Comment by fbricon** [comment]
Upstream issue: https://github.com/angelozerr/lsp4xml/issues/177

**Comment by ehigiepaul** [comment]
Can I get the **VSIX Build** with the fix so i can test it out

**Comment by fbricon** [comment]
Sorry, but our CI server is currently down and no longer builds the vsix files.
Your best chance to get a new binary quickly is to build it yourself: follow [steps 1-5](https://github.com/redhat-developer/vscode-xml/blob/master/CONTRIBUTING.md), then, from the vscode-xml directory, execute:

* `npm install -g vsce`
* `vsce package`

It'll generate a new visx file under vscode-xml.
