### ISSUE TITLE
Fold closing tags too

### ISSUE THREAD

**Issue by ris58h** [redhat-developer/vscode-xml#665]
For now folding regions don't contain closing tags. By folding them too we could save screen space and increase readability of big XML files such as `pom.xml`.

Actual behavior
<img width="196" alt="Screenshot 2022-02-17 at 01 26 01" src="https://user-images.githubusercontent.com/511242/154368407-4d234e2a-6b27-4810-8b26-f1f3d464ae00.png">

Desired behavior
<img width="196" alt="Screenshot 2022-02-17 at 01 27 14" src="https://user-images.githubusercontent.com/511242/154368456-3a47f336-b1e4-4f00-92ba-c59838f06090.png">

**Comment by angelozerr** [comment]
Close for https://github.com/eclipse/lemminx/issues/1178
