### ISSUE TITLE
Add option to split Attributes only if the line length is too long

### ISSUE THREAD

**Issue by AL1L** [redhat-developer/vscode-xml#666]
I have something like this

```xml
<record id="quality_blocking_action" model="ir.actions.act_window">
  <field name="help" type="html">
    <p>Configure blocking</p>
  </field>
</record>

<menuitem id="menu_config_quality_blocking" name="Quality Blocking" groups="quality.group_quality_manager" action="quality_blocking_action" parent="quality_control.menu_quality_configuration" sequence="30"/>
```

and I really only want to split the attributes if the line length is >120 so the output would be

```xml
<record id="quality_blocking_action" model="ir.actions.act_window">
  <field name="help" type="html">
    <p>Configure blocking</p>
  </field>
</record>

<menuitem
    id="menu_config_quality_blocking"
    name="Quality Blocking"
    groups="quality.group_quality_manager"
    action="quality_blocking_action"
    parent="quality_control.menu_quality_configuration"
    sequence="30" />
```

My proposed solution is to allow `xml.format.splitAttributes` to accept an integer to specify the length required for the attributes to be split. Otherwise I think it's just ugly and harder to read, especially when the attributes are very short and there's only one or two. And sorry if this is a duplicate or this feature already exists, I tried looking thorough it to see. And I couldn't find any other extension that does this.

**Comment by angelozerr** [comment]
Indeed it should be nice but we need to redo from scratch our formatter to support line width

**Comment by fbricon** [comment]
@angelozerr  duplicate of #350 ?

**Comment by AL1L** [comment]
@fbricon looks like it's so, same problem, different proposed solution. Although I think 350 has two issues in one, respecting `.editorconfig`, and formatting based on max line length. I'll close as a duplicate
