### ISSUE TITLE
Support for nested DTDs

### ISSUE THREAD

**Issue by amasino** [redhat-developer/vscode-xml#667]
Does the extension support the use of nested DTDs?  For instance, I have a .dtd file including the following declarations:

<!ENTITY % part1 SYSTEM "part1.mod"> 
<!ENTITY % part2 SYSTEM "part2.mod"> 

%part1;
%part2;

The motivation for this is to factorize common definitions for different xml grammars.

**Comment by angelozerr** [comment]
@amasino can you manage your nested dtd like you wish? If yes can we close the issue?

**Comment by amasino** [comment]
yes, it worked like a charm! Thanks!

**Comment by angelozerr** [comment]
Great! Thanks for your feedback.
