### ISSUE TITLE
Unwanted autocompletion

### ISSUE THREAD

**Issue by DaWolfi** [redhat-developer/vscode-xml#668]
Every time I start typing in an empty string or at the end of a string, an autocompletion window opens with filenames of the directory, which contains the file in use:

![image](https://user-images.githubusercontent.com/26442759/155608294-e943d6ca-c81a-493b-ac39-e5505c07f749.png)

If I disable the XML extension this autocompletion doesn't show up any more.

Can anybody please help me to disable this "feature"!

Version: 1.65.0-insider (user setup)

**Comment by angelozerr** [comment]
Its not possible to disable it. We need to provide a settings for that like xml.completion.fileSupport

@fbricon what do you think about that?

**Comment by fbricon** [comment]
Agree, we need a setting

**Comment by angelozerr** [comment]
What about xml.completion.fileSupport.enabled?

@AlexXuChen are you interested to work on this issue?

**Comment by DaWolfi** [comment]
Thanks for your quick support guys, great extension!

**Comment by AlexXuChen** [comment]
@fbricon What should the default behaviour be for this setting?

**Comment by fbricon** [comment]
I'd say it could support boolean (true by default) and file glob patterns.

**Comment by fbricon** [comment]
@DaWolfi  I don't understand how you get file name completion though, from your picture. It should only kick in if you start the attribute value with `/` or `\`  or `.`

**Comment by angelozerr** [comment]
Instead of having only glob patterns I think we should have xpath too exactly like we have for symbole filters. 

All mechanism already exists (perhaps with some refactoring)

**Comment by angelozerr** [comment]
With xpath I mean we could write @path to allow file completion for path attribute

**Comment by DaWolfi** [comment]
> @DaWolfi I don't understand how you get file name completion though, from your picture. It should only kick in if you start the attribute value with `/` or `\` or `.`

@fbricon : I also thought that it should work this way, but even though I disabled all other extensions, the result is always the same.

**Comment by fbricon** [comment]
@DaWolfi can you set the  "xml.trace.server" preference to "verbose" and give us the logs from the "XML Support" Output channel, from startup to file name completion

**Comment by DaWolfi** [comment]
[Trace.log](https://github.com/redhat-developer/vscode-xml/files/8156065/Trace.log)

Here you are...

**Comment by DaWolfi** [comment]
Hi guys, any news about this issue?

**Comment by angelozerr** [comment]
No sorry we had.no time to work on that. I know this completion file feature is annoting for camel //cc @apupier 

We need to filter this file completion with a new completion file filtrer wherr we can write some xpath like we have with symbol filter. We could define a default value to allow some attributs like @path @file
