### ISSUE TITLE
turn lsp4xml cache on by default

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#67]
Need to set `"xml.useCache":true` in the extension preferences. See https://github.com/angelozerr/lsp4xml/issues/159

**Comment by angelozerr** [comment]
@fridex I have set it as default in server side, see https://github.com/angelozerr/lsp4xml/commit/db419972bc8bb0c6261684fd365743d7b5ba560c

**Comment by fridex** [comment]
@angelozerr wrong nick? :)

**Comment by angelozerr** [comment]
Sorry @fridex -( with my mistake.

@fbricon I have set it as default in server side, see angelozerr/lsp4xml@db41997

**Comment by fbricon** [comment]
@angelozerr I don't see anything downloaded/cached when opening an actual schema:
```
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:complexType name="property">
        <xs:attribute name="name" type="xs:string" />
        <xs:attribute name="value" type="xs:string" />
    </xs:complexType>

    <xs:complexType name="resource">
        <xs:sequence>
            <xs:element name="property" type="property" minOccurs="0" maxOccurs="unbounded" />
        </xs:sequence>
        <xs:attribute name="name" type="xs:string" use="required" />
    </xs:complexType>

    <xs:element name="resources">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="resource" type="resource" minOccurs="0" maxOccurs="unbounded" />
            </xs:sequence>
            <xs:attribute name="variant" type="xs:string" use="required"/>
        </xs:complexType>
    </xs:element>
</xs:schema>
```

**Comment by angelozerr** [comment]
> @angelozerr I don't see anything downloaded/cached when opening an actual schema:

Yes it's normal. The cache download is done when Xerces `XMLEntityResolver#resolveEntity` is done.

This resolveEntity method is called when:

 * XML Schema uses import (not in your case of resource.xsd) 
 * XML declares use of XML Schema with `xsi:schemaLocation` or `xsi:noNamespaceSchemaLocation` which have uri which start with `http` or `ftp`.
