### ISSUE TITLE
Does vscode-xml support display all optional attributes when editing an element?

### ISSUE THREAD

**Issue by joe914** [redhat-developer/vscode-xml#677]
In xsd files, element defines many optional attributes (having default value).

Does vscode-xml support display all optional attributes when editing an element, without inputing the first charactor of attribute's name? I cannot find the related setting.

**Comment by angelozerr** [comment]
Sorry I don't understand very well. You mean completion? If you do Ctrl+Space you should see allowed attributes (optional and no optional).

**Comment by joe914** [comment]
@angelozerr  Yes

On Windows，Ctrl + Space probably conflicts with other applictions. Ctrl +I works for me on Windows:

![image](https://user-images.githubusercontent.com/93459145/158117060-173523b1-b47d-470f-a963-9e9ca0c79334.png)



Thank you.
