### ISSUE TITLE
Command “XML: Revalidate  the current XML file” always succeeds even though there is error

### ISSUE THREAD

**Issue by joe914** [redhat-developer/vscode-xml#682]
Command “XML: Revalidate  the current XML file” always succeeds even though there is error.

Pls refer to the following screenshot:

![Revalidate  the current XML file](https://user-images.githubusercontent.com/93459145/159602622-8519930b-08ed-4eb2-80ea-3973a1235317.png)
[foo.zip](https://github.com/redhat-developer/vscode-xml/files/8329489/foo.zip)

**Comment by joe914** [comment]
I need to validate the current xml file and then do something else.

I got the same result when calling the "xml.validation.current.file" command in js:

    // call command "xml.validation.current.file" directly
    const command="xml.validation.current.file"
    let result=await vscode.commands.executeCommand(command)
    console.log(result); // **undefined**

    // call command "xml.workspace.executeCommand"
    const EXECUTE_WORKSPACE_COMMAND = "xml.workspace.executeCommand";
    const VALIDATE_CURRENT_FILE = "xml.validation.current.file";
    const uri = vscode.window.activeTextEditor.document.uri; // {uri}
    const identifier = TextDocumentIdentifier.create(uri.toString());
    try{
      result=await vscode.commands.executeCommand(EXECUTE_WORKSPACE_COMMAND, VALIDATE_CURRENT_FILE, identifier);
    }catch(err){
      result="error"
      console.error(err)
    }
    console.log(result); // **null**
    vscode.window.showInformationMessage(JSON.stringify(result));

**Comment by joe914** [comment]
It's better to return true if succeeded or false if failed.

The following snippet is excerpted from the XML extension source:
  // Revalidate current file
  context.subscriptions.push(commands.registerCommand(ClientCommandConstants.VALIDATE_CURRENT_FILE, async (params) => {
    const uri = window.activeTextEditor.document.uri;
    const identifier = TextDocumentIdentifier.create(uri.toString());
    commands.executeCommand(ClientCommandConstants.EXECUTE_WORKSPACE_COMMAND, ServerCommandConstants.VALIDATE_CURRENT_FILE, identifier).
      then(() => {
        window.showInformationMessage('The current XML file was successfully validated.');
      }, error => {
        window.showErrorMessage('Error during XML validation ' + error.message);
      });
  }));

**Comment by angelozerr** [comment]
This command remove some cache and retrigger the diagnostics publish and return true if this process occured with no errors (ex: the cache cannot be removed for some reason the command will return the error)

I have the impression that you need to know if the current file have diagnostic errors. To do that I suggest you see the vscode api to coĺlect diagnostics from a given editor

**Comment by joe914** [comment]
@angelozerr Thanks for the idea.

I get the solution: 

    const uri = vscode.window.activeTextEditor.document.uri;
    const diagnosticses = vscode.languages.getDiagnostics();
    const checkFlag = diagnosticses.every((d) => d[1] && d[1].length <= 0);
    if (checkFlag) {
      vscode.window.showInformationMessage("succedded");
      return true;
    } else {
      vscode.window.showInformationMessage("failed");
      return false;
    }

**Comment by angelozerr** [comment]
> I get the solution:

Nice! I suggest that you filter the diagnostics with `d.source === 'xml'` to collect only XML diagnostics .

Can we close the issue?

**Comment by joe914** [comment]
@angelozerr Yes.  Thanks for your addvice.
