### ISSUE TITLE
schema-for-xslt30.xsd is considered non valid

### ISSUE THREAD

**Issue by gidmoth** [redhat-developer/vscode-xml#683]
Hi, I'm not sure if this is a schema-validation error, or an actual error in the schema, but the extension can't verify my xsl (version 3.0) due to errors in the schema. To reproduce, try this xsl:

```
<xsl:transform version="3.0"
  xmlns:xsl="http://www.w3.org/1999/XSL/Transform">

  <xsl:template match="*">
    <xsl:value-of select="." />
  </xsl:template>

</xsl:transform>
```

The Extension seems to get the right schema from the Internet, but underlines the first "xsl:transform" in red, when you hoover over it, it says:

```
There are '45' errors in 'schema-for-xslt30.xsd'
```

I tried downloading the schema from here: https://www.w3.org/TR/xslt-30/schema-for-xslt30.xsd and use the downloaded schema through a catalog.xml. But that yields the same result. Since I can't confirm the errors the Extension names, I think it's an error in the schema-validation.

__
s.

**Comment by angelozerr** [comment]
It's because the xsl 3.0 requires xsd 1.1, but the official xerces doesnt support it.

I created a draft PR with xsd 1.1 https://github.com/eclipse/lemminx/pull/515but it doesn't use the official xerceslibrary which is really annoying.

I fear that we cannot support it today.
