### ISSUE TITLE
Outline Formatting not working as expected

### ISSUE THREAD

**Issue by nblyumberg** [redhat-developer/vscode-xml#684]
I am attempting to customize the outline view for XML files however, it does not appear to be working as expected. What I see after making my modifications...
![image](https://user-images.githubusercontent.com/17443495/160016244-42791a40-7c7e-4cd6-8fab-108292a235d4.png)

I customized the settings.json and I reopen the file every time I update the settings.json
`{   
   "editor.fontSize": 14,
   "editor.linkedEditing": true,
    "workbench.colorTheme": "Default Dark+",
    
    "remote.SSH.showLoginTerminal": true,
    "remote.SSH.remotePlatform": {
        "devnixster01.imanheim.com": "linux"
    },
    "workbench.sideBar.location": "right",
    "files.associations": {
        "*.bpml": "xml"
    },
    "security.workspace.trust.untrustedFiles": "open",
    "redhat.telemetry.enabled": false,
    "xml.codeLens.enabled": true,

    "xml.symbols.enabled": true,
    "xml.symbols.maxItemsComputed": 30000,
    "xml.symbols.filters": [
        {
           "pattern": "*.{bpml,xml}",
           "expressions" :[
              {
                // Process Name
                "xpath": "//@name",
                "inlineAttribute" : true,
                "showAttributeName": false
             }
           ]
        }
   ]

}`

Sample XML I am trying to use:
`<process name="name_of_process"> 
	<sequence name="Error Sequence">
		
		<operation name="Get BP MetaData">
			<participant name="BPMetaDataInfoService" />
			<output message="Xout">
				<assign to="DISPOSITION">false</assign>
				<assign to="LINKAGE">false</assign>
				<assign to="." from="*" />
			</output>
			<input message="Xin">
				<assign to="WORKSPACE/REPORT/SAVETILL" from="substring-before(BPDATA/WFD_LIFE_SPAN,' Minute(s)')" append="true"/>
				<assign to="WORKSPACE/REPORT/REPORTID" from="string(BPDATA/WFD_ID)" />
			</input>
		</operation>	</sequence>
</process>`

**Comment by angelozerr** [comment]
I don't understand your XML sample. In your screenshot you show proces, rule, condition, where are those elements in your XML sample?

**Comment by nblyumberg** [comment]
![image](https://user-images.githubusercontent.com/17443495/160129022-c526eb61-cba9-41c3-9b3b-f1ca8727234e.png)

I would expect the Outline to be populated with the names as this XPath test from FreeFormatter shows:
Attribute='name=my process'
Attribute='name=check condition'
Attribute='name=check condition2'
Attribute='name=Main'
Attribute='name=PreProcess'
Attribute='name=PreProcess'
Attribute='name=Invoke Business Process Service'

https://www.freeformatter.com/xpath-tester.html#ad-output

Here's the sample XML from the screenshot:
```
<process name="my process">
    <rule name="check condition">
        <condition>boolean(/ProcessData/NODE1</condition>
    </rule>
    <rule name="check condition2">
        <condition>boolean(/ProcessData/NODE2</condition>
    </rule>
    <sequence name="Main">
        <choice name="PreProcess">
            <select>
                <case ref="PreProcessBP"/>
            </select>
           <sequence name="PreProcess">
               <operation name="Invoke Business Process Service">
                   
               </operation>
           </sequence>
        </choice>
    </sequence>
</process>

```

**Comment by fbricon** [comment]
try with `"pattern": "**/*.{bpml,xml}",`
```json
"xml.symbols.filters": [
        {
            "pattern": "**/*.{bpml,xml}",
            "expressions": [
                {
                    // Process Name
                    "xpath": "//@name",
                    "inlineAttribute": true,
                    "showAttributeName": false
                }
            ]
        }
    ]
 ```

**Comment by fbricon** [comment]
<img width="1645" alt="Screenshot 2022-03-25 at 16 27 26" src="https://user-images.githubusercontent.com/148698/160150952-bb0e6f36-bf04-4c8a-8391-1cc4051eaf11.png">

**Comment by nblyumberg** [comment]
Thank you, this worked...Can you explain why the directory boundry option is necessary with the extra **/ change?

**Comment by angelozerr** [comment]
Indeed it can be annoying, perhaps we could allow to write only `*.xml`

**Comment by nblyumberg** [comment]
@angelozerr I think an update to the documentation here: 
https://github.com/redhat-developer/vscode-xml/blob/master/docs/Symbols.md#xmlsymbolsfilters

to explain the current behavior would be greatly helpful. I went by the example in that documentation where the pom.xml and bean*.xml are shown without the directory boundry configuration so I assumed *.bpml or *.xml would work that way as well.

**Comment by angelozerr** [comment]
I totally agree with you. We need to update document. Is there any chance that you create a PR for that?

I will study why only *.xml is not working

**Comment by angelozerr** [comment]
@nblyumberg I'm worjing again with pattern to support a new feature (validation filter which uses pattern), and the after reading https://mincong.io/2019/04/16/glob-expression-understanding/#wildcard-expressions article I noticed that we can write just `**` like `**.{bpml,xml}`
