### ISSUE TITLE
How to exclude <literallayout> blocks from being indented?

### ISSUE THREAD

**Issue by robp-tw** [redhat-developer/vscode-xml#691]
When I format XML content with this extension activated/configured, it indents `<literallayout>` blocks. This is not advantageous, as it results in indented content where there should be none. Is there a setting to turn this off or some kind of (un)documented workaround? Thanks much!

**Comment by angelozerr** [comment]
Today it's not possible but it should be nice to provide this feature.

**Comment by angelozerr** [comment]
I'm working on experimental formatter at https://github.com/eclipse/lemminx/issues/1195 and I think I could support this feature.

**Comment by angelozerr** [comment]
This issue should be fixed by the experimental formatter https://github.com/redhat-developer/vscode-xml/blob/master/docs/Formatting.md#xmlformatexperimental
