### ISSUE TITLE
Use org.eclipse.lsp4xml-all.jar?

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#7]
I have noticed in https://github.com/gorkem/vscode-xml/blob/master/src/javaServerStarter.ts#L33 that you consume the org.eclipse.lsp4xml-all.jar which contains only https://github.com/angelozerr/lsp4xml/tree/master/org.eclipse.lsp4xml and their dependencies but it doesn't contains extension projects https://github.com/angelozerr/lsp4xml/tree/master/extensions (to have completion, validation for XML Schema, compleetion for Emmet, etc)

I would like to clarify if org.eclipse.lsp4xml-all.jar should exist? In my Eclipse client https://github.com/angelozerr/lsp4e-xml, I'm using all JARs https://github.com/angelozerr/lsp4e-xml/tree/master/org.eclipse.lsp4e.xml/server and I build the Jar command with those files?

@fbricon I believe that you want not to have an  org.eclipse.lsp4xml-all.jar , no?

**Comment by fbricon** [comment]
@angelozerr we will probably also use all individual jars once we decide to add emmet support in the vscode extension.
It might be useful for the server to provide an uber jar containing both the dependencies and the extensions, but I wouldn't focus on that unless there was an actual need.

**Comment by fbricon** [comment]
Nothing to change for now. Closing.
