### ISSUE TITLE
Provide documentation in the wiki

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#70]
* [x] file associations
* [x] catalogs
* [x] server vm arguments
* [x] proxy support
* [x] formatter settings
* [x] cached data

**Comment by fbricon** [comment]
then add a link to the wiki from the readme

**Comment by ralfhandl** [comment]
Happy to see catalogs in the todo list: I can't figure out how to set up a catalog of XML schemas.

Ideal example would contain:
- xml.catalogs entry in (user/workspace) settings with path to catalog file in (Windows) file system
- catalog.xml file with entries mapping XML namespace names to XSD files in (Windows) file system

Naive approach (in user settings: "xml.catalogs":["path to Eclipse Photon system_catalog.xml"]) did not produce the desired result 🙁

**Comment by fbricon** [comment]
@ralfhandl you mean you pointed to your workspace's system catalog, like:
/Users/username/path/to/workspace/.metadata/.plugins/org.eclipse.wst.xml.core/system_catalog.xml? or some other path?

Anyways, if that doesn't work, I suspect this might be caused by schemas using the `jar:` URIs. I suggest you open a specific ticket about it. cc @angelozerr

**Comment by angelozerr** [comment]
> Anyways, if that doesn't work, I suspect this might be caused by schemas using the jar: URIs. 

Yes it's mu suspection too:)

@ralfhandl I think file: URIs should work, have you tried?

**Comment by fbricon** [comment]
@ralfhandl please start by opening a separate issue ;-)

**Comment by ralfhandl** [comment]
@fbricon Done: https://github.com/redhat-developer/vscode-xml/issues/78

**Comment by NikolasKomonen** [comment]
@fbricon everything but formatting settings is implemented, do you think its something we need to do?

**Comment by fbricon** [comment]
Everything's done. Thanks @NikolasKomonen!
