### ISSUE TITLE
Add option to increase heap maximum in OOM notification

### ISSUE THREAD

**Issue by idkman2021** [redhat-developer/vscode-xml#700]
I need to give the thing more memory.
It says "go to xml.server.vmargs and add -Xmx1G.
I search for xml.server.vmargs in settings and press Edit in settings.json
![image](https://user-images.githubusercontent.com/76593873/163768518-ac5d1d37-8dec-4862-8fa6-013971b420dc.png)
thats what the file looks like
![image](https://user-images.githubusercontent.com/76593873/163768548-c149376d-d141-45f3-b614-2500f4404ce3.png)
where do i put the " -Xmx1G."

**Comment by angelozerr** [comment]
Are you in untrusted workspace?

Have you tried to write the settings at hand?

**Comment by idkman2021** [comment]
> Are you in untrusted workspace?
> 
> Have you tried to write the settings at hand?

sorry I am not sure what that means, how do I know if I am in untrusted workspace and how do I try to to write the settings at hand? I sometimes notice there is a blue notification saying something about untrusted workspace, but it doesn't appear when I try to edit this setting.

**Comment by angelozerr** [comment]
I suggest that you read https://code.visualstudio.com/blogs/2021/07/06/workspace-trust

**Comment by idkman2021** [comment]
> I suggest that you read https://code.visualstudio.com/blogs/2021/07/06/workspace-trust

i disabled the trust and nothing changed

**Comment by idkman2021** [comment]
> 

![image](https://user-images.githubusercontent.com/76593873/164005578-13a24864-5ffd-4ed6-a8ee-54c5774ef838.png)
![image](https://user-images.githubusercontent.com/76593873/164005594-f7a0523f-55a2-434f-ac8f-6ab2da121b6b.png)
it doesn't like it no matter how i put it

**Comment by idkman2021** [comment]
> simply type "xml.server.vmargs" in the User settings.json file

It doesn't like it no matter how i put it
![image](https://user-images.githubusercontent.com/76593873/164005686-0cd8fb20-7734-4628-8ae5-5f722561333d.png)
![image](https://user-images.githubusercontent.com/76593873/164005709-85e0ee8a-fc87-4c66-bb9b-19372fa28830.png)
![image](https://user-images.githubusercontent.com/76593873/164005743-b9d83669-a197-4ced-8cd4-6008b3330c11.png)

**Comment by fbricon** [comment]
looks like vscode-xml is not installed/active on your machine

**Comment by fbricon** [comment]
Ctrl+Space after xml.server.vmargs.
Eventually it should look like "xml.server.vmargs":"-Xmx1G", once you configure it

**Comment by idkman2021** [comment]
> looks like vscode-xml is not installed/active on your machine

it definitely is intalled because i am currently using it
![image](https://user-images.githubusercontent.com/76593873/164006409-0ebf3e71-bd1b-49d2-b8b7-e663682f06e7.png)

**Comment by idkman2021** [comment]
> Ctrl+Space after xml.server.vmargs. Eventually it should look like "xml.server.vmargs":"-Xmx1G", once you configure it
where do i put it?

**Comment by fbricon** [comment]
towards the end of the settings.json file for instance, before the closing bracket.

**Comment by angelozerr** [comment]
If you go to your second line of your settings.json and you type `xml`, you should see:

![image](https://user-images.githubusercontent.com/1932211/170291701-5145681b-07c1-4373-9408-9fd854e4fdfe.png)

if you continue to type `xml.ser`, you should see:

![image](https://user-images.githubusercontent.com/1932211/170291563-8fe47949-b5d0-4bb3-9e30-de4bd38dfdba.png)

**Comment by angelozerr** [comment]
> i disabled the trust in accordance to the article and nothing changed, I still don't know where to put -Xmx1G.

Your workspace should be in trust mode.

@fbricon @rgrunber to avoid this problem, I think the popup which display the out of memory problem should provide a new button `Apply suggestion` to update the setting `xml.server.vmargs` with the proper value. What do you think about that?

**Comment by rgrunber** [comment]
We seem to do that in vscode-java. https://github.com/redhat-developer/vscode-java/pull/2085 . One of the options is "Configure" which appears to double the given XmX value. We should do the same.
