### ISSUE TITLE
Unable to associate external xml catalog (xsd) (user error?)

### ISSUE THREAD

**Issue by ralphcallaway** [redhat-developer/vscode-xml#702]
First off, thank you for all your amazing open source contributions. I appreciate all the development time you've put into and the time you spend reading these issues. Fingers crossed I've got all the info you need.

I work on Salesforce projects which have a ton of random xml files, which generates a ton of error noise. I'd love to replace that noise with actual validation and auto-complete if it's possible (may not be). Maybe that's done after the log4j issues? Or maybe I'm just not following the directions correctly? A lot of googling and reviewing issues in this repo and so far I haven't stumbled across a similar situation (hopefully I haven't missed it.

I know i've got some other options, but before I head down that route figured I'd make sure that I wasn't making some dumb user error. And if it's not user error, perhaps I can alter this to be a feature request.
- disable the schema warnings
- uninstall the plugin
- (maybe) download the catalog into the project and use the "file://" protocol instead of using http or https

Did my best to following the instructions, and reloaded by disabling and re-enabling the extension so vs code would restart. The first restart typically crashed Electron. EXC_BAD_ACCESS (SIGSEGV). I tried a variety of configuration styles, although I didn't mess with java versions as I'm pretty weak there.

No matter what I'm still getting file warnings like, which can be a frustrating when you have 100s of these files,
```
[{
	"resource": "/<redacted>/src/main/default/objects/<redacted>/fields/<redacted>.field-meta.xml",
	"owner": "_generated_diagnostic_collection_name_#9",
	"code": "cvc-elt.1.a",
	"severity": 8,
	"message": "cvc-elt.1.a: Cannot find the declaration of element 'CustomField'.",
	"source": "xml",
	"startLineNumber": 2,
	"startColumn": 2,
	"endLineNumber": 2,
	"endColumn": 13
}]
```

At the same time I'll get pop warnings like
```
Invalid path for setting 'xml.catalogs': 'http://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd'

Source: XML (Extension)
```

Here's the "XML Support" logs from the "Output" section of vs code after the restart (in full)
```
[Info  - 1:49:15 AM] Apr 19, 2022 01:49:14 org.eclipse.lemminx.XMLLanguageServer initialize()
Message: Initializing XML Language server
LemMinX Server info:
 - Version : 0.20.0
 - Java : /Library/Java/JavaVirtualMachines/zulu-11.jdk/Contents/Home
 - VM Version : 11.0.3
 - Git 6e1aecb - [maven-release-plugin] prepare release 0.20.0
[Error - 1:49:16 AM] Apr 19, 2022 01:49:15 org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCatalogResolverExtension setCatalogs()
Message: Cannot add XML catalog 'http://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd' with expand system id 'http://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd' and root URI 'file:///Users/<redacted>/Development/<redacted>/'.
[Info  - 1:49:16 AM] Apr 19, 2022 01:49:15 org.eclipse.lemminx.extensions.contentmodel.uriresolver.XMLCatalogResolverExtension setCatalogs()
Message: Adding XML catalog '/Users/<redacted>/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-54.8.0/resources/static/js-meta-home.xml' with expand system id 'file:///Users/<redacted>/.vscode/extensions/salesforce.salesforcedx-vscode-lwc-54.8.0/resources/static/js-meta-home.xml' and root URI 'file:///Users/<redacted>/Development/kestra_sfdc/'.
[Warn  - 1:49:16 AM] Apr 19, 2022 01:49:16 org.eclipse.lsp4j.jsonrpc.RemoteEndpoint handleCancellation()
Message: Unmatched cancel notification for request id 4
```

Here's the configuration I added to my workspace in my workspace. I increased the maxItemsComputed given the catalog is 10k lines long, although the files being validated are usually much shorter (my example is less than 50 lines). 
```
  "xml.fileAssociations": [
        {
            "pattern": "**/*-meta.xml",
            "systemId": "https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd"
        }
    ],
    "xml.catalogs": ["http://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd"],
    "xml.validation.namespaces.enabled": "onNamespaceEncountered",
    "xml.validation.resolveExternalEntities": true,
    "xml.symbols.maxItemsComputed": 15000
}
```

Here's an example file at `{projectroot}/src/main/default/objects/Some_Object__e/Some_Field__c.field-meta.xml`. Note that there are a number of different similar files that all end in `*-meta.xml`, have the same `xmlns` value, and different root elements (i.e. in this example it's `CustomField` but there is also `CustomObject`)

```
<?xml version="1.0" encoding="UTF-8"?>
<CustomField xmlns="http://soap.sforce.com/2006/04/metadata">
    <fullName>Some_Field__c</fullName>
    <description>Field Description</description>
    <externalId>false</externalId>
    <isFilteringDisabled>false</isFilteringDisabled>
    <isNameField>false</isNameField>
    <isSortingDisabled>false</isSortingDisabled>
    <label>Some Field</label>
    <length>32768</length>
    <type>LongTextArea</type>
    <visibleLines>3</visibleLines>
</CustomField>
```

The definition for this is in the [catalog](https://raw.githubusercontent.com/forcedotcom/idecore/master/com.salesforce.ide.api/schema/metadata.xsd) - abbreviated as it's about 10k ilnes. See [line 1953 in the non-raw version for context](https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd#L1953)

```
<xsd:complexType name="CustomField">
    <xsd:complexContent>
     <xsd:extension base="tns:Metadata">
      <xsd:sequence>
       <xsd:element name="caseSensitive" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="customDataType" minOccurs="0" type="xsd:string"/>
       <xsd:element name="defaultValue" minOccurs="0" type="xsd:string"/>
       <xsd:element name="deleteConstraint" minOccurs="0" type="tns:DeleteConstraint"/>
       <xsd:element name="deprecated" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="description" minOccurs="0" type="xsd:string"/>
       <xsd:element name="displayFormat" minOccurs="0" type="xsd:string"/>
       <xsd:element name="encrypted" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="escapeMarkup" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="externalDeveloperName" minOccurs="0" type="xsd:string"/>
       <xsd:element name="externalId" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="fieldManageability" minOccurs="0" type="tns:FieldManageability"/>
       <xsd:element name="formula" minOccurs="0" type="xsd:string"/>
       <xsd:element name="formulaTreatBlanksAs" minOccurs="0" type="tns:TreatBlanksAs"/>
       <xsd:element name="inlineHelpText" minOccurs="0" type="xsd:string"/>
       <xsd:element name="isConvertLeadDisabled" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="isFilteringDisabled" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="isNameField" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="isSortingDisabled" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="label" minOccurs="0" type="xsd:string"/>
       <xsd:element name="length" minOccurs="0" type="xsd:int"/>
       <xsd:element name="lookupFilter" minOccurs="0" type="tns:LookupFilter"/>
       <xsd:element name="maskChar" minOccurs="0" type="tns:EncryptedFieldMaskChar"/>
       <xsd:element name="maskType" minOccurs="0" type="tns:EncryptedFieldMaskType"/>
       <xsd:element name="metadataRelationshipControllingField" minOccurs="0" type="xsd:string"/>
       <xsd:element name="populateExistingRows" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="precision" minOccurs="0" type="xsd:int"/>
       <xsd:element name="referenceTargetField" minOccurs="0" type="xsd:string"/>
       <xsd:element name="referenceTo" minOccurs="0" type="xsd:string"/>
       <xsd:element name="relationshipLabel" minOccurs="0" type="xsd:string"/>
       <xsd:element name="relationshipName" minOccurs="0" type="xsd:string"/>
       <xsd:element name="relationshipOrder" minOccurs="0" type="xsd:int"/>
       <xsd:element name="reparentableMasterDetail" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="required" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="restrictedAdminField" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="scale" minOccurs="0" type="xsd:int"/>
       <xsd:element name="startingNumber" minOccurs="0" type="xsd:int"/>
       <xsd:element name="stripMarkup" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="summarizedField" minOccurs="0" type="xsd:string"/>
       <xsd:element name="summaryFilterItems" minOccurs="0" maxOccurs="unbounded" type="tns:FilterItem"/>
       <xsd:element name="summaryForeignKey" minOccurs="0" type="xsd:string"/>
       <xsd:element name="summaryOperation" minOccurs="0" type="tns:SummaryOperations"/>
       <xsd:element name="trackFeedHistory" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="trackHistory" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="trackTrending" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="type" minOccurs="0" type="tns:FieldType"/>
       <xsd:element name="unique" minOccurs="0" type="xsd:boolean"/>
       <xsd:element name="valueSet" minOccurs="0" type="tns:ValueSet"/>
       <xsd:element name="visibleLines" minOccurs="0" type="xsd:int"/>
       <xsd:element name="writeRequiresMasterRead" minOccurs="0" type="xsd:boolean"/>
      </xsd:sequence>
     </xsd:extension>
    </xsd:complexContent>
   </xsd:complexType>
```

**Comment by ralphcallaway** [comment]
on further inspection, maybe this is related to #698 and #699?

**Comment by angelozerr** [comment]
Just a Quick question. Metadata.xsd is a xml schema not a xml catalog, no?

**Comment by ralphcallaway** [comment]
i seem to be getting closer with the following

```
    "xml.fileAssociations": [
        {
            "pattern": "**/*meta.xml",
            "systemId": "https://github.com/forcedotcom/idecore/blob/master/com.salesforce.ide.api/schema/metadata.xsd"
        }
    ],
    "xml.server.vmargs": "-Xmx512M"
```

it appears to be getting cached and loaded, although it's still flagging the element the root "CustomField" as invalid, apologies if my xml knowledge is a bit weak, i'm one of those millenial json schema guys (╯°□°）╯︵ ┻━┻

**Comment by fbricon** [comment]
try referencing the raw file: `https://raw.githubusercontent.com/forcedotcom/idecore/master/com.salesforce.ide.api/schema/metadata.xsd`

**Comment by angelozerr** [comment]
At first you should create a valid xml catalog which références your xsd like your metadata.xsd.

And after that you référence the created local xml catalog file. I dont know if xml catalog coming from http is working.

**Comment by ralphcallaway** [comment]
oh wild, thought i had the raw uggh, too late, i'll play with this a bit more

**Comment by angelozerr** [comment]
You must choose between file association and xml catalog and not use the both.

I think xml catalog can be used in your usecase since your xml have a namespace. So  you can write à xml catalog which bind the namespace with the proper metadata.xsd

**Comment by ralphcallaway** [comment]
i'll give it a go, one thing I did notice the hover for `xml.fileAssociations[*].systemId` says "The path or URL to the XML schema (XSD or DTD)."

regardless, just thought I'd flag in case the intention was for the fileAssociations to support URLs to xsd

doing some learning on xml catalogs to try and take that route (guessing that's what #698 and #699 will address when merged

**Comment by ralphcallaway** [comment]
secondary issue .... i'm working off an old schema (seems like they've given up on publishing them for a while), just happened it's missing "CustomField" as an element type even though it's there as a complex type that can be referenced in say CustomObject.

Thanks for this. I'm seeing auto-complete and it appears to be working provided the xsd actually includes stuff as an element, I can incorporate. 

I'm going to clone what they have up there and tweak as needed.

**Comment by ralphcallaway** [comment]
well nothing like starting with an outdated xsd and a recent wsdl and trying to work those into a recent xsd, but got it done and it's working. thank you @angelozerr for all the pointers :)
