### ISSUE TITLE
Not recognizing xml

### ISSUE THREAD

**Issue by 7heMech** [redhat-developer/vscode-xml#708]
How can I make extension recognize or treat files with specific extension as XML, or can I do that?

**Comment by fbricon** [comment]
any file with `<?xml version="1.0" encoding="UTF-8"?>` in its first line will be automatically treated as xml, if its extension is unrecognized.
If you don't or can't modify the files' first line, you can define a custom [file mapping](https://code.visualstudio.com/docs/languages/identifiers) in your vscode' settings.json, like:

```
    "files.associations": {
        "*.myxml": "xml"
    }
```
