### ISSUE TITLE
No completions while the java build is running

### ISSUE THREAD

**Issue by gayanper** [redhat-developer/vscode-xml#710]
When Java Build is running, not completions are provided for xml files. The completions popup just shows "Loading...."

**Comment by gayanper** [comment]
Spoke too soon, this happens for plugin configurations such as goals, phases completions as well. Tag completions work fine, But values completions are hanging.

**Comment by angelozerr** [comment]
Are you sure that you have not vscode-maven which is not installed, because it provide those kind of features (without lemminx).

**Comment by angelozerr** [comment]
If it works with WWD it is a problem with lemminx-maven and I suspect that it misses some dependency. Have you see some lemminx maven errors in trace of the XML support?

**Comment by gayanper** [comment]
Works in eclipse. You are correct after disabling maven plugin and restarting vscode, not no completion suggestions.

**Comment by gayanper** [comment]
> If it works with WWD it is a problem with lemminx-maven and I suspect that it misses some dependency. Have you see some lemminx maven errors in trace of the XML support?

No errors. Only the server info in the output

**Comment by angelozerr** [comment]
Ok so it means lemminx-maven is not started in vscode-xml. Do you see some error in the trace?

**Comment by angelozerr** [comment]
Could you share your full trace please.
