### ISSUE TITLE
Move to vscode-languageclient 8.0.1

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#711]
With vscode-languageclient 8.0.1, we will benefit with:

 * LSP 3.7 support
 * we could remove shouldLanguageServerExitOnShutdown

**Comment by angelozerr** [comment]
With this PR we need to test that:

 * XML features should work (completion, validation, hover, etc).
 * when we close the vscode, we must not have some zombie process (because I remove shouldLanguageServerExitOnShutdown)
 * when we change settings, we must test that it continues to work (refresh of settings should continue to work).

**Comment by rgrunber** [comment]
Can we prepare this for the 0.24.0 release ?

**Comment by vince-fugnitto** [comment]
I believe with the update to `8.0.1` the defined API version should be stepped to align, else it will fail to activate for older versions and applications that support the VS Code API:

https://github.com/redhat-developer/vscode-xml/blob/efd52ad1f6e89e962c576795c324621aed7d8370/package.json#L44-L46

The dependency `vscode-languageclient@8.0.1` requires `^1.67.0`:

- https://github.com/microsoft/vscode-languageserver-node/blob/8b3c375adc4fa69f63726ef58d911c8e27b261c5/client/package.json#L7-L9

**Comment by datho7561** [comment]
Thanks for letting us know. I filed a bug to get this done
