### ISSUE TITLE
Server binaries for "osx-x86_64" are not found

### ISSUE THREAD

**Issue by shwao** [redhat-developer/vscode-xml#729]
The URL for the `osx-x86_64` binaries configured here:

https://github.com/redhat-developer/vscode-xml/blob/a026ba1615f8d14bf05ca22206757b8b83b3cebf/package.json#L23

is returning 404 `Not Found`.

The other ones work.

**Comment by rgrunber** [comment]
I think it's a bug in the naming for the development version at https://github.com/redhat-developer/vscode-xml/blob/master/.github/workflows/native-image.yaml#L115 . We alternate in a few places between `osx-x86_64` and `darwin` so we just need to modify the build to match. It's correct on windows and linux.

**Comment by rgrunber** [comment]
I've also fixed the release location for the development build https://github.com/redhat-developer/vscode-xml/releases/tag/latest .
