### ISSUE TITLE
Autocompletion of attribute values won't display documentation

### ISSUE THREAD

**Issue by bimimicah** [redhat-developer/vscode-xml#736]
**Documentation appears properly when autocompleting attribute names:**
![image](https://user-images.githubusercontent.com/34111930/178773586-f0cc384b-780e-4a2f-bf46-03c2cb2add58.png)
**But when autocompleting attribute values (<xs:enumeration>), the documentation does not appear:**
![image](https://user-images.githubusercontent.com/34111930/178773601-04e412d8-c81d-4206-a23a-6d09a072aa6f.png)

**I think it used to work, but I'm not entirely certain. Has anyone else noticed this issue? Is it working for anyone?**

**Comment by fbricon** [comment]
can you provide a self contained sample reproducing this issue?

**Comment by bimimicah** [comment]
**Ok. So it looks like when one or more &lt;xs:enumeration&gt; do not have documentation, it breaks the documentation for all enums for that attribute.**

**Example Document:**
```xml
<?xml version="1.0" encoding="utf-8"?>
<root attribute="value1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="schema.xsd" />
```

**Example Schema:**
```xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="root">
		<xs:annotation>
			<xs:documentation>Documentation for root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:attribute name="attribute">
				<xs:annotation>
					<xs:documentation>Documentation for attribute</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="value1">
							<xs:annotation>
								<xs:documentation>Documentation for attribute value1</xs:documentation>
							</xs:annotation>
						</xs:enumeration>
						<xs:enumeration value="value2" /> <!-- this one has no documentation. if you delete this line, documentation displays properly for 'value1' -->
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
</xs:schema>
```

**Comment by bimimicah** [comment]
@fbricon Were you able to reproduce the issues with the sample I provided? Thanks for looking into this.

**Comment by angelozerr** [comment]
I can reproduce the problem @[bimimicah](https://github.com/bimimicah).

Many thanks for your sample. Let us investigate the problem.

**Comment by angelozerr** [comment]
@bimimicah I create a PR which should fix your issue, see demo at:

https://github.com/eclipse/lemminx/pull/1260#issuecomment-1195775762

**Comment by bimimicah** [comment]
I tried the [pre-release build of lemminx](https://github.com/redhat-developer/vscode-xml/releases/tag/latest) built 6 days ago, and it looks like **problem # 1 has been solved completely! Thank you!**

However, it looks like that **didn't solve the second problem**:

- If you create the attribute (instead of typing manually) by typing a space, the first letter, then choose the attribute name from the dropdown, the attribute will be autocompleted, and the enumerated attribute values will appear in a dropdown, as expected. However, none of them will display documentation, even if all of them have documentation in the xsd.

For illustration:

![image](https://user-images.githubusercontent.com/34111930/184393184-99d61b8d-3cd5-4f22-8a41-faa61f6f0d2a.png)

- Type &lt;space>, then 'a'

![image](https://user-images.githubusercontent.com/34111930/184393551-50f36dc4-59e7-436a-a4f6-e49dfa2870a5.png)

- Press &lt;tab>

![image](https://user-images.githubusercontent.com/34111930/184393819-75373f51-4770-4586-838b-2a70cd990f91.png)

**Thank you again for your quick solution to the first problem!**

**Comment by bimimicah** [comment]
@angelozerr should I make a new issue for the second part that hasn't been solved yet, since this issue is closed?

**Comment by angelozerr** [comment]
I fear that it is not possible to support the second problem because it is not supported by the lsp specification. In otherwise when completion item is applied you can define a simple list of string value called choice but without specifying à documentation.

**Comment by bimimicah** [comment]
I may be misunderstanding, since I am not very familiar with the details of LSP implementations, but shouldn't the process I illustrated above work like this?:

1. user types 'a', triggers a [textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) call to the LSP server (for the attributes beginning with 'a'), returning a list of completion items including documentation
2. user selects the item from the list and presses &lt;tab>, choosing the completion item, and triggering a second textDocument/completion call to the LSP server (for the chosen attribute's values), which should also return a list of completion items including documentation?

**Comment by angelozerr** [comment]
I see your idea but it will require some hack on client side so it will require to do this Hack for vscode eclipe sublime etc wuich is not the goal of lsp.

Please create an issue for this problem. Perhaps there is a solution that I miss with lsp . We should study in détail the mroblem.

**Comment by bimimicah** [comment]
Thanks. I created #760 to track the second problem.
