### ISSUE TITLE
Publish platform-specific binaries & pre-releases to open-vsx.org

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#739]
According to https://github.com/eclipse/openvsx/pull/406, it seems open-vsx.org supports platform-specific extensions. It would be neat if we published platform specific extensions for open-vsx.org as well.

**Comment by rgrunber** [comment]
Before we adopt this, we should follow :

https://open-vsx.org/extension/jbangdev/jbang-vscode
https://github.com/jbangdev/jbang-vscode/blob/main/.github/workflows/ci.yaml#L72

and maybe try it out on a flavour of VS Code that uses OpenVSX as the default marketplace.
According to @fbricon , there is no distinction between a release and a pre-release as far as the marketplace goes.

**Comment by rgrunber** [comment]
At least for pre-releases, there is no distinction currently between a release and a pre-release in the UI. The UI allows installing pre-release as if they were regular releases. https://github.com/redhat-developer/vscode-java/pull/2587#issuecomment-1233389519
