### ISSUE TITLE
Format TODO and FIXME in comments

### ISSUE THREAD

**Issue by AceAttorneyMaster111** [redhat-developer/vscode-xml#740]
I'm currently manually creating an XML file, to use as an example for an application. As I'm working on it, it would be really helpful to have special formatting for `TODO` and `FIXME` notes within `<!-- -->` comments. Is this something that would be possible to implement?

**Comment by angelozerr** [comment]
Could you give us some samples before znd after formatting please

**Comment by AceAttorneyMaster111** [comment]
```xml
<element type="song" id="12345">
    <!-- TODO: Hmm. How to deal with storing names of songs when downloading?
    Brings up a bigger question of should this XML be independent of the database?-->
</element>
```
I want to make sure I don't forget about this comment, for instance. Would love for the word `TODO` to be highlighted in a color, and show as a Task in the sidebar like in other languages.

**Comment by angelozerr** [comment]
Have you tried https://marketplace.visualstudio.com/items?itemName=Gruntfuggly.todo-tree ?

**Comment by adunning** [comment]
The TODO Highlight extension also accomplishes this.

https://marketplace.visualstudio.com/items?itemName=wayou.vscode-todo-highlight

**Comment by angelozerr** [comment]
Thanks @adunning for your feedback. I close this issue since it exists an extension which does that and this feature is out of the scope of the vscode xml project which provides xml editing support.
