### ISSUE TITLE
Autocompleted attribute doesn't display documentation for popped up attribute values

### ISSUE THREAD

**Issue by bimimicah** [redhat-developer/vscode-xml#760]
This is a second problem discovered while investigating #736:

- If you create the attribute (instead of typing manually) by typing a space, the first letter, then choose the attribute name from the dropdown, the attribute will be autocompleted, and the enumerated attribute values will appear in a dropdown, as expected. However, none of them will display documentation, even if all of them have documentation in the xsd.

For illustration:

![image](https://user-images.githubusercontent.com/34111930/184393184-99d61b8d-3cd5-4f22-8a41-faa61f6f0d2a.png)

- Type &lt;space>, then 'a'

![image](https://user-images.githubusercontent.com/34111930/184393551-50f36dc4-59e7-436a-a4f6-e49dfa2870a5.png)

- Press &lt;tab>

![image](https://user-images.githubusercontent.com/34111930/184393819-75373f51-4770-4586-838b-2a70cd990f91.png)

_Originally posted by @bimimicah in https://github.com/redhat-developer/vscode-xml/issues/736#issuecomment-1213264096_

**Comment by bimimicah** [comment]
My guess of a model of LSP interaction, copied from #736:
> 
>1. user types 'a', triggers a [textDocument/completion](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_completion) call to the LSP server (for the attributes beginning with 'a'), returning a list of completion items including documentation
> 
>2. user selects the item from the list and presses <tab>, choosing the completion item, and triggering a second textDocument/completion call to the LSP server (for the chosen attribute's values), which should also return a list of completion items including documentation?

@angelozerr  My guess is maybe the [CompletionItems](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem) returned in step 2 do not include the 'documentation' attribute. Could that be the issue?

> I see your idea but it will require some hack on client side so it will require to do this Hack for vscode eclipe sublime etc wuich is not the goal of lsp.
> 
> Please create an issue for this problem. Perhaps there is a solution that I miss with lsp . We should study in détail the mroblem.

The 'documentation' attribute is built-in to the ['CompletionItem' Interface](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#completionItem), so I would hope that it does not require a hack to fix? I may be misunderstanding something. Thanks for your help.

**Comment by angelozerr** [comment]
We use LSP choice which supports only a list of string, I fear that we can not fix this issue because of LSP limitation.

**Comment by angelozerr** [comment]
I close this issue since LSP doesnt provide this feature.
