### ISSUE TITLE
Inadequate error message for download error

### ISSUE THREAD

**Issue by mwisnicki** [redhat-developer/vscode-xml#763]
I'm experiencing the issue similar to the one described in #134.

The error message `Error while downloading 'foo.xsd' to 'C:\...' xml(DownloadProblem)`

 This message is entirely inadequate. Please change it to describe actual problem.

**Comment by angelozerr** [comment]
If you activate the trace you should see the détail of the error.

What is your suggestion to improve the erŕor message?

**Comment by mwisnicki** [comment]
The underlying error such as connection refused or relevant HTTP error should be surfaced to the UI in default configuration.

**Comment by angelozerr** [comment]
@mwisnicki see screenshot at https://github.com/eclipse/lemminx/pull/1282#issuecomment-1228084355

**Comment by mwisnicki** [comment]
Looks great, thank you!
