### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Alice-Lins** [redhat-developer/vscode-xml#773]
- Issue Type: `Performance`
- Extension Name: `vscode-xml`
- Extension Version: `0.21.2022062916`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.71.0`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/Alice/AppData/Local/Temp/redhat.vscode-xml-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by rgrunber** [comment]
@Alice-Lins , are you able to attach the file mentioned in your original comment ? Also, are you able to attach the file you had opened, or the actions you were performing when you encountered the high CPU load ?

@angelozerr , any ideas what could be causing this ?

**Comment by angelozerr** [comment]
I close this issue since we have no informations. @Alice-Lins please reopen it if you have again some problems by giving us more information. Thanks.
