### ISSUE TITLE
RelaxNG file association

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#786]
I don't want to clutter #450, so I open a new issue here. I have an otherwise empty directory with two files:

`addressbook.rng`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<grammar ns="" xmlns="http://relaxng.org/ns/structure/1.0" datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <start>
    <element name="addressBook">
      <element name="card">
        <element name="name">
          <data type="NCName"/>
        </element>
        <element name="email">
          <empty/>
        </element>
      </element>
    </element>
  </start>
</grammar>
```
and `addressbook.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="addressbook.rng"?>
<addressBook>
    <card>
        <name>ABC</name>
        <email></email>
    </card>
</addressBook>
```

The vscode version is v0.21.2022101304.  I cannot use tag completion in `addressbook.xml`.

**Comment by pgundlach** [comment]
I have not tried the example you've linked in your comment as I believe this is close enough (should I try the example?). And (for the sake of completeness) I couldn't get the completion to work with catalogs either.

**Comment by angelozerr** [comment]
@pgundlach it seems that the prerelease doen't embed RelaxNG, let us investigate why?

**Comment by angelozerr** [comment]
@pgundlach please retry to install the new prerelease. 

For your information I wrote a documentation for RelaxNG with the PR https://github.com/redhat-developer/vscode-xml/pull/787

If you think it misses something please comment.

And don't hesitate to create any issues if you encounter some problem or if you wish some improvement, features.

**Comment by angelozerr** [comment]
If it is working for you, please close the issue.

**Comment by pgundlach** [comment]
Great, thank you, it works now with <? xml-model and with the catalog. I think I have found a small glitch but open another issue for that if I can reproduce it.
