### ISSUE TITLE
DTD validation problems not refreshing correctly

### ISSUE THREAD

**Issue by iTReprise** [redhat-developer/vscode-xml#79]
When I change a dtd <!ELEMENT> declaration the file doesn't validate automatically. I have to force restart VSCode to see, if my changes fixed the problem.

Example:

```
<?xml version="1.0"?>
<!DOCTYPE student [
  <!ELEMENT student (surname,id)>
  <!ELEMENT surname (#PCDATA)>
]>
<student>
  <surname>Smith</surname>
  <id>567896</id>
</student>
```

This file is invalid because its missing `<!ELEMENT id (#PCDATA)>`. Adding the line doesn't cause the error to disappear, only after restarting VSCode the problem is it fixed.

I'm using VSCode 1.27.2 on Kali Linux. Java JDK is openjdk-10

**Comment by fbricon** [comment]
See upstream issue: https://github.com/angelozerr/lsp4xml/issues/194

**Comment by angelozerr** [comment]
Indded it should work:

![dtd](https://user-images.githubusercontent.com/1932211/48066260-65f68480-e1cd-11e8-8976-fc106cd6e56f.gif)

I think we should add a test with this case.

**Comment by fbricon** [comment]
Works in 0.2.0.  Please try the latest CI build:

- Download the latest development VSIX archive [from here](http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D). `(vscode-xml-XXX.vsix)`
- Go to the Extensions section in VSCode.
- At the top right click the `...` icon.
- Select 'Install from VSIX...' and choose the visx file.
