### ISSUE TITLE
RelaxNG autocompletion without namespace

### ISSUE THREAD

**Issue by pgundlach** [redhat-developer/vscode-xml#791]
`simple.rng`:

```xml
<grammar xmlns="http://relaxng.org/ns/structure/1.0"
  datatypeLibrary="http://www.w3.org/2001/XMLSchema-datatypes">
  <start>
    <ref name="rootelt"/>
  </start>
  <define name="rootelt">
      <element name="rootelt">
        <attribute name="xml:lang">
          <choice>
            <value>en</value>
            <value>de</value>
          </choice>
        </attribute>
      </element>
  </define>
</grammar>
```

```xml
<?xml-model href="simple.rng"?>
<rootelt lang="en"></rootelt>
```

the autocompletion should provide the xml namespace so the result looks like this:

```xml
<rootelt xml:lang="en"></rootelt>
```

but instead vscode-xml autocompletes to this:

```xml
<rootelt lang="en"></rootelt>
```

Version: v0.22.2022101505

![completion](https://user-images.githubusercontent.com/209434/195983082-2680612f-19b5-4fc3-a44d-43ad362975dd.png)

(BTW: the RelaxNG support is awesome!)

**Comment by pgundlach** [comment]
Thank you very much. It works like a charm.

**Comment by angelozerr** [comment]
@pgundlach thanks for your feedback and don't hesitate to create any issues to continue to improve the RelaxNG support. 

I have some ideas how to improve it and I will create some issues but if issue coming from user, should be better.
