### ISSUE TITLE
Wrap selection in XML element

### ISSUE THREAD

**Issue by adunning** [redhat-developer/vscode-xml#794]
Most XML editors have a feature to wrap the current selection in an XML element, providing completion to suggest valid tags at that point in a file.

Within VS Code, the built-in 'Emmet: Wrap with Abbreviation' function provides part of this, but it is not XML-aware and does not give a list of the allowed tags in the current context. It would thus be brilliant if the XML extension could provide this.

There are at least two ways to implement this:

1. Inline: TextMate allows the user to make a selection, then type <kbd>Ctrl</kbd> + <kbd><</kbd> to insert open/close tags around it, balancing the element name as the user types. The VS Code XML plugin could use this approach to immediately provide a list of options identical to the current functionality when typing <kbd><</kbd>.
2. With a dialogue box: Similar to the existing Emmet function but with autocompletion. The Oxygen XML Editor, for example, provides such a dialogue with the shortcut <kbd>Ctrl</kbd> + <kbd>E</kbd>. The [Scholarly XML](https://marketplace.visualstudio.com/items?itemName=raffazizzi.sxml) extension for VS Code has an implementation of this, but it conflicts with this XML plugin.

Many thanks for your work on this project and considering this request!

**Comment by angelozerr** [comment]
@adunning if I understand correctly, teh native emmet extension does the job, but you would like to just have completion for allowed XML tags  in command palette, is that?

**Comment by adunning** [comment]
Yes, exactly: giving users a list of available tags is an enormous help for beginners to a schema and prevents typos for everyone.

I prefer an inline interface along the lines of what the extension already provides, but it's likely a question of what is easier to implement.

Thank you again for your consideration!

**Comment by angelozerr** [comment]
I fear it can be a long task, I'm not sure that we will implement that soon. If we see that we hav emore andmore user who want to have this feature, we could change the priority.

@adunning don't hesitate to create any issue that you think it is important for RelaxNG and TEI.

For instance I wonder if `xml:id` supports could help TEI users (having completion, definitin, validation for xml:id). If you think it is important please create the issue and another. Thanks!

**Comment by otichy** [comment]
This similar to https://github.com/redhat-developer/vscode-xml/issues/605

I just want to add that this has been implemented both by the [Scholarly XML](https://marketplace.visualstudio.com/items?itemName=raffazizzi.sxml) (mentioned above) as well by [TEI Publisher Extension for Visual Studio Code](https://github.com/eeditiones/tei-publisher-vscode), but neither of them has the completion feature.

**Comment by angelozerr** [comment]
Ok thanks @otichy for your feedback. I will see if it is easy to implement.

**Comment by angelozerr** [comment]
@adunning @otichy I have started to implement inline wrap element at https://github.com/redhat-developer/vscode-xml/pull/813#issuecomment-1319672325 but it requires to do some more work.

**Comment by datho7561** [comment]
The prerelease containing this feature should be out December 9th. Please let us know if you run into any issues

**Comment by adunning** [comment]
Looking forward to seeing it – very many thanks for your work on this!

**Comment by angelozerr** [comment]
> Looking forward to seeing it – very many thanks for your work on this!

You are welcome!

Please install the prerelease https://github.com/redhat-developer/vscode-xml#contributing to try the wrap element feature (see https://github.com/redhat-developer/vscode-xml/blob/main/docs/Refactor.md#surround-with-tags-wrap) and give us feedback

**Comment by otichy** [comment]
Just tested this, very cool, thank you all very much!  

I have one very minor comment: when I select the action, the first item from the completion is selected and inserted automatically. When I decide to cancel the action e.g. using escape, the wrapping tag remains. I can of course undo, so no big deal.

**Comment by otichy** [comment]
OK, will do. 

Is it also a good idea to start a new issue about possibly having the choice between documentation and multiline as discussed in https://github.com/redhat-developer/vscode-xml/pull/813#issuecomment-1339760727 ?

**Comment by angelozerr** [comment]
> Is it also a good idea to start a new issue about possibly having the choice between documentation and multiline as discussed in https://github.com/redhat-developer/vscode-xml/pull/813#issuecomment-1339760727 ?

Yes please. In otherwords please create an issue per improvement to investiagte.

**Comment by angelozerr** [comment]
And please create any issues if you think an important features from Oxygen is provided but not in vscode-xml.
