### ISSUE TITLE
Experimental formatter ignores xml.format.preservedNewlines

### ISSUE THREAD

**Issue by kapexx** [redhat-developer/vscode-xml#797]
Thanks for working on the new experimental formatter. I've just tried it on a few documents and compared them to the old formatting. I see a lot differences because the setting `xml.format.preservedNewlines` seems to be ignored in some cases.

With the setting `"xml.format.preservedNewlines": 2` when formatting following document

``` xml
<foo>

    <bar>1</bar>

    <bar>2</bar>


    <bar>3</bar>



    <bar>4</bar>

</foo>
```

I would expected this result:
``` xml
<foo>

    <bar>1</bar>

    <bar>2</bar>


    <bar>3</bar>


    <bar>4</bar>

</foo>
```

The actual result is: 
``` xml
<foo>
    <bar>1</bar>
    <bar>2</bar>


    <bar>3</bar>


    <bar>4</bar>
</foo>
```

The three empty lines after `<bar>3</bar>` collapse into two empty lines as expected. But it looks like all single empty line are removed.

**Comment by angelozerr** [comment]
Thanks so much @kapexx for having reported this issue. It should be fixed now. Don't hesitate to report other issues with experimental formatter. Our goal is to swith the old formatter with the experimental once we  will be cover all usecases that old formatter is supporting.
