### ISSUE TITLE
Code completion is sometimes "one off"

### ISSUE THREAD

**Issue by ralfhandl** [redhat-developer/vscode-xml#80]
Code completion is "one off" in some places of the XML file in the attached [mini.zip](https://github.com/redhat-developer/vscode-xml/files/2553189/mini.zip).

At this position it should suggest `edmx:Include` and `edmx:IncludeAnnotations`, instead it suggests nothing:

![image](https://user-images.githubusercontent.com/951576/48065124-1a8ea700-e1ca-11e8-8a84-13d872fcde2c.png)

Instead it shows these suggestions when triggering code completion one level up in the XML tree (where it should instead suggest `edmx:Reference` and others):
![image](https://user-images.githubusercontent.com/951576/48065185-4dd13600-e1ca-11e8-8516-aec79cca1fa9.png)

To make things more confusing this only happens with suggestions for the "outer" XSD (here: edmx). Suggestions for elements in the "inner" XSD (here: edm) work fine - only `edm:PropertyRef` is allowed and suggested here:
![image](https://user-images.githubusercontent.com/951576/48065310-a0125700-e1ca-11e8-94a3-9eaa86d0ae8b.png)

To make things even more confusing the "one off" suggestions only show when pressing Control-Space on "white space". Once I type a `<` the correct suggestions show:
![image](https://user-images.githubusercontent.com/951576/48065538-49f1e380-e1cb-11e8-87e8-0e0a8e55ac1a.png)

**Comment by angelozerr** [comment]
Please install vscode-xml upstream, it should work better:

![image](https://user-images.githubusercontent.com/1932211/48066542-32682a00-e1ce-11e8-8b96-dcc37c9cd22d.png)

**Comment by fbricon** [comment]
Already fixed in 0.2.0. Please try the latest CI build:

- Download the latest development VSIX archive [from here](http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D). `(vscode-xml-XXX.vsix)`
- Go to the Extensions section in VSCode.
- At the top right click the `...` icon.
- Select 'Install from VSIX...' and choose the visx file.

**Comment by ralfhandl** [comment]
Thanks!
