### ISSUE TITLE
Any plans to create an XML Schema Designer type feature?

### ISSUE THREAD

**Issue by davidmcl** [redhat-developer/vscode-xml#803]
Visual Studio versions like Community & Pro have an XML Schema Designer feature that is very helpful when working with complex XSD documents like those in DDEX.

Any plans to support agraphical feature like this? 

Thanks,
David

![XSD](https://user-images.githubusercontent.com/2047925/201904261-ad6aa386-766a-468a-b08d-35b73d98af45.png)

**Comment by fbricon** [comment]
No, we don't have the bandwidth to do that. 
Anyone willing to contribute such a feature, as part of vscode-xml or another companion extension, is welcome.
