### ISSUE TITLE
Referenced RelaxNG schema not found via XML catalog

### ISSUE THREAD

**Issue by jperterm** [redhat-developer/vscode-xml#804]
I tried out your new RelaxNG validation feature and it seems that an URI given in `<?xml-model href="[...]"` does not resolve against XML catalogs which can be configured via `xml.catalogs` setting. Absolute file URIs and OS path's are working fine.

```xml
[...]
<?xml-model href="http://canonical-uri/schema.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
[...]
```

I tested with v0.22 and v0.23.2022111503 (pre-release).

**Comment by angelozerr** [comment]
Indeed we don't use XML catalog for xml-model, we should implement that.

**Comment by angelozerr** [comment]
@jperterm could you share the XML that you try to bind. I would like to test with your same rng URL.

Thanks

**Comment by angelozerr** [comment]
Thanks so much! Let me investigate the problem.

**Comment by angelozerr** [comment]
@jperterm I create a PR to fix the problem at https://github.com/eclipse/lemminx/pull/1371#issuecomment-1317186602
