### ISSUE TITLE
no svg validation if `jock.svg` is also installed

### ISSUE THREAD

**Issue by BuZZ-dEE** [redhat-developer/vscode-xml#805]
If I have a group and remove the end tag `</g>`, I get no error, so the validation does not work.

**Comment by angelozerr** [comment]
@BuZZ-dEE you can install pre-release to enjoy with this fix. Please give me feedback.

You should set `xml.validation.resolveExternalEntities` to `true`, see https://github.com/redhat-developer/vscode-xml/issues/810

**Comment by BuZZ-dEE** [comment]
Hi @angelozerr I will try it, but what do I need?: https://github.com/redhat-developer/vscode-xml/releases/tag/latest

**Comment by angelozerr** [comment]
Try to install vscode-xml as you did, and click on `Switch To Pre Release version`

![image](https://user-images.githubusercontent.com/1932211/202482081-30d09a86-42e5-430e-829b-e999fa1365a1.png)

**Comment by BuZZ-dEE** [comment]
```
g: Group Element ..................................

Source: [svg11.dtd](vscode-file://vscode-app/usr/lib/code/out/vs/code/electron-sandbox/workbench/workbench.html)

The SVG element is a container used to group other SVG elements.

[MDN Reference](vscode-file://vscode-app/usr/lib/code/out/vs/code/electron-sandbox/workbench/workbench.html)

The element type "g" must be terminated by the matching end-tag "</g>".xml(ETagRequired)
test.svg(54, 9): Closing tag expected here
```

It works now.

**Comment by angelozerr** [comment]
Thanks for your feedback.

The problem now is with completion. You will see 2 duplicate completion item for the same element which comes from jock.svg and vscode-xml.

I think vscode-xml could support the same feature than jock.svg like better hover documentation and color for rgb attribute.

I will see if jock.svg could be interested to delegate thise features to vscode-xml

**Comment by BuZZ-dEE** [comment]
@angelozerr I have created https://github.com/lishu/vscode-svg2/issues/129 just to make `jock.svg` aware if the issue.

**Comment by lishu** [comment]
@BuZZ-dEE 
I installed the vscode-xml plugin and found no duplicate completions, whether some specific configuration or version has changed?

**Comment by angelozerr** [comment]
@lishu have you svg validation which is working?

Could you share your svg file please. It requires the svg namespace if I remember

**Comment by lishu** [comment]
Maybe it's not working properly.

![image](https://user-images.githubusercontent.com/1331008/208230205-824e36e0-f5fb-430a-8c74-8216c3b9b837.png)

**Comment by angelozerr** [comment]
Could you share please your svg file

**Comment by angelozerr** [comment]
I tested it and you can see duplicate completion items:

![image](https://user-images.githubusercontent.com/1932211/208237970-8b15a565-4f74-4589-9d95-d5b435ee0990.png)

Here my svg file:

```xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" 
  "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="5cm" height="4cm" version="1.1"
     xmlns="http://www.w3.org/2000/svg">
     <a xlink:href=""></a>
  <desc>Four separate rectangles
  </desc>
    <a
    <rect x="0.5cm" y="0.5cm" width="2cm" height="1cm"/>
    <rect x="0.5cm" y="2cm" width="1cm" height="1.5cm"/>
    <rect x="3cm" y="0.5cm" width="1.5cm" height="2cm"/>
    <rect x="3.5cm" y="3cm" width="1cm" height="0.5cm"/>

  <!-- Show outline of canvas using 'rect' element -->
  <rect x=".01cm" y=".01cm" width="4.98cm" height="3.98cm"
        fill="none" stroke="blue" stroke-width=".02cm" />

</svg>
```

You can notice you need to declare DOCTYPE.

Is the validation working for you?

**Comment by angelozerr** [comment]
I noticed in the log the same error than you, but is is working for me. We need to invesitgate this error log.

**Comment by angelozerr** [comment]
I noticec that the first completion item a (coming from vscode-xml) generates:

`<a xlink:href=""></a>`

which is valid according to the DTD, although your extension generates:

`<a href="#url"></a>`

which seems not be valid. Is it allowed?

**Comment by lishu** [comment]
Yes, my svg doesn't use `DOCTYPE`

`DOCTYPE` - [MDN does not recommend using DOCTYPE](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Getting_Started)

`xlink:href` - [Deprecated XLink URL reference attributes](https://svgwg.org/svg2-draft/linking.html#XLinkRefAttrs)

**Comment by angelozerr** [comment]
> Yes, my svg doesn't use DOCTYPE

LemMinx doesn't provide a specific SVG support, so you need to declare the DOCTYPE with the proper DTD. But it is possible to write a little Java LemMinx extension which does that. But I think you will not be interested to provide that.

My another idea is to gives the capability to do that with package.json in your extension point (no dependency to vscode-xml), but before developping that, we need some user requirements.

**Comment by lishu** [comment]
There are many conflicts between the standards under HTML and the XML standard, so it is indeed a problem that is not easy to handle 🤣
