### ISSUE TITLE
Legal comments break into lines after formatting

### ISSUE THREAD

**Issue by bkarolyi** [redhat-developer/vscode-xml#851]
After updating to the v0.23.0 version, legal comments break into lines after formatting.

Structure of the comment:
``
 
 becomes
 
 ``

Expected behaviour: 
lines in comments don't break after formatting.

It is related to the 'Xml › Format: Max Line Width' setting. When I set it from the default 100 to 500 for example, it works fine, comments don't break.
It looks like the legal area considered as a one long string, that formatting wants to break to lines in every 100th character.

Update: The bullet points in the description are stars: *, just Github changed it.

**Comment by angelozerr** [comment]
@JessicaJHee could you look at this issue please.Thanks!

**Comment by bkarolyi** [comment]
Thank you!

**Comment by angelozerr** [comment]
@bkarolyi please try to install prerelease https://github.com/redhat-developer/vscode-xml#contributing which should fix your issue

**Comment by bkarolyi** [comment]
> @bkarolyi please try to install prerelease https://github.com/redhat-developer/vscode-xml#contributing which should fix your issue

It fixed the issue, thank you!
