### ISSUE TITLE
Problems with npm run build-server on Windows

### ISSUE THREAD

**Issue by ralfhandl** [redhat-developer/vscode-xml#86]
When trying to build vscode-xml on Windows 10 Enterprise 1803 I run into a few issues:

1) `npm install` ends with warnings
```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
```

2) `npm run build-server` ends with an error:
```
Couldn't find "C:\Temp\vscode-xml-build-test\lsp4xml\.mvn\wrapper\maven-wrapper.jar", downloading it ...
Downloading from: "https://repo.maven.apache.org/maven2/io/takari/maven-wrapper/0.4.2/maven-wrapper-0.4.2.jar"
Exception calling "DownloadFile" with "2" argument(s): "The request was aborted: Could not create SSL/TLS secure
channel."
At line:1 char:1
+ (New-Object Net.WebClient).DownloadFile('https://repo.maven.apache.or ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : WebException

Finished downloading "C:\Temp\vscode-xml-build-test\lsp4xml\.mvn\wrapper\maven-wrapper.jar"
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
```

3) After manually downloading the `maven-wrapper.jar` I ran into another maven-related error so I decided to look over at https://github.com/angelozerr/lsp4xml where I found the hint to 
* Run `./mvnw clean verify` (OSX, Linux) or `mvnw.cmd clean verify` (Windows)
Doing that gave me another bunch of errors:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for lsp4xml 0.0.3-SNAPSHOT:
[INFO]
[INFO] lsp4xml ............................................ SUCCESS [  0.109 s]
[INFO] org.eclipse.lsp4xml ................................ SUCCESS [ 20.310 s]
[INFO] lsp4xml-extensions ................................. SUCCESS [  0.016 s]
[INFO] org.eclipse.lsp4xml.extensions.emmet ............... FAILURE [ 25.260 s]
[INFO] org.eclipse.lsp4xml.extensions.web ................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  45.833 s
[INFO] Finished at: 2018-11-09T11:06:25+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project org.eclipse.lsp4xml.extensions.emmet: There are test failures.
```

4) Ignoring these errors I headed back to `vscode-xml` and re-ran `npm run build-server` which then succeeded. 

So apparently just some steps are missing in CONTRIBUTING.md:
* `cd ../lsp4xml`
* Run `./mvnw clean verify` (OSX, Linux) or `mvnw.cmd clean verify` (Windows)
* `cd ../vscode-xml`

Plus the advice to ignore certain warnings or errors 😃

**Comment by snjeza** [comment]
mvnw.cmd can't download maven-wrapper.jar because some Windows versions have TLS 1.2 disabled.
See https://docs.microsoft.com/en-us/windows/desktop/SecAuthN/protocols-in-tls-ssl--schannel-ssp-
TLS 1.0 and TLS 1.1 are disabled on the https://repo.maven.apache.org/ server - https://www.ssllabs.com/ssltest/analyze.html?d=repo.maven.apache.org

The Java LS (https://github.com/eclipse/eclipse.jdt.ls) has the same issue.

We can do the following:

a) enable TLS 1.2 on Windows as described at https://success.outsystems.com/Support/Enterprise_Customers/Maintenance_and_Operations/(.NET)_Enable_SSL_Protocols_for_your_Integrations_-_TLS_1.1_and_TLS_1.2

or

b) add maven-wrapper.jar to the lsp4xml and eclipse.jdt.ls repository

All the projects including org.eclipse.lsp4xml.extensions.emmet build on both, Linux and Windows.

**Comment by fbricon** [comment]
Thanks @snjeza. I've added the maven wrapper to the lsp4xml git repo. @ralfhandl please try again.

**Comment by fbricon** [comment]
@snjeza can you confirm this works now on windows?

**Comment by snjeza** [comment]
> @snjeza can you confirm this works now on windows?

I confirm. There is the same issue in vscode-java.
