### ISSUE TITLE
DTD Validation and GIT Repository throws errors in GIT files

### ISSUE THREAD

**Issue by Thallius** [redhat-developer/vscode-xml#861]
Hi,

easy to reproduce:

Create a new folder:

Create a DTD file person.dtd

`<!ELEMENT person ( first_name) >`

Create a XML file person.xml with a reference to a DTD file

`<?xml version="1.0" ?>`
`<?xml-model href="person.dtd" ?>`
`<person>`
            `    <first_name>Michael</first_name>`
`</person>`

Go to terminal and type

git init
git add * 
git commit -m"test"

Now vscode will show you a problem in file

person.xml.git
- Cannot find DTD 'git:/c%3a/Users/path_to_my_folder/person.dtd

which normally does not exists

**Comment by datho7561** [comment]
I can reproduce this bug. That's really odd, vscode-xml should only be reporting errors on open files.

**Comment by datho7561** [comment]
This is a known issue from other VS Code extensions, I'll take a look into it.
