### ISSUE TITLE
Discrepancy in completion between prefixed and default namespaces

### ISSUE THREAD

**Issue by ralfhandl** [redhat-developer/vscode-xml#87]
I have XML files that use an "outer" namespace which in turn imports an "inner" namespace. 

If the "inner" namespace is declared as the default namespace via `xmlns="..."`, code completion works fine in the "outer" and the "inner" part, e.g.:
![image](https://user-images.githubusercontent.com/951576/48425038-41b61d00-e764-11e8-943d-f9658f289dd3.png)

However if the "inner" namespace is declared with a namespace prefix via `xmlns:edm="..."`, code completion for constructs in the "outer" namespace also shows top-level elements from the "inner" namespace that are not allowed by the "outer" XSD in that place:
![image](https://user-images.githubusercontent.com/951576/48425260-c012bf00-e764-11e8-8b2d-b708369139df.png)

This effect only shows on "level 1", i.e. directly below the root element of the "outer" namespace, where no elements of the "inner" namespace are allowed at all. 

On "level 2", i.e. within children of the root element, code completion works fine and only shows allowed elements.

Test project is attached: [vscode-xml-catalog-test.zip](https://github.com/redhat-developer/vscode-xml/files/2577019/vscode-xml-catalog-test.zip)
* `examples/mini-catalog.xml` works as expected
* `examples/mini-catalog-prefix.xml` has the above strange behavior in one place.

**Comment by fbricon** [comment]
Can you provide a sample document reproducing this issue?

**Comment by ralfhandl** [comment]
@fbricon is attached now

**Comment by fbricon** [comment]
ok, I can reproduce the issue with those samples, thanks!
That should give @angelozerr and/or @NikolasKomonen enough info to find a solution.

**Comment by angelozerr** [comment]
@ralfhandl just for you rinformation this issue should be fixed with my PR https://github.com/angelozerr/lsp4xml/pull/478 planned for 0.8.0

**Comment by angelozerr** [comment]
Fixed by angelozerr/lsp4xml#478

**Comment by angelozerr** [comment]
Thanks @ralfhandl for your great information. It was an hard issue but it is now fixed. Just for your information Completion on 0.8.0 is improved by filtering XML completion item according the existing XML elements of the document. See https://github.com/angelozerr/lsp4xml/pull/505

**Comment by ralfhandl** [comment]
@angelozerr Cool, thanks!

When will the VS Code XML plugin 0.8.0 be released?

**Comment by fbricon** [comment]
@ralfhandl  before the end of the month. Until then, you can try the latest CI build from https://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D
