### ISSUE TITLE
DTDs should not be validated against lsp4xml

### ISSUE THREAD

**Issue by fbricon** [redhat-developer/vscode-xml#88]
if you save http://java.sun.com/dtd/web-app_2_3.dtd locally and open it in VS Code, an error shows up on the 1st ELEMENT, L72. "The markup in the document preceding the root element must be well-formed."
DTDs are not actual xml documents themselves, so they should not be validated against lsp4xml.

**Comment by angelozerr** [comment]
It's an issue for lsp4xml, no? More perhaps we should have support for DTD himself like completion and validation. I don't know if xerces provides this features.

**Comment by fbricon** [comment]
Because DTD is actually part of the XML spec, we should probably be able to get tooling support for it, but "The markup in the document preceding the root element must be well-formed." should be ignored. So it might be a server-side issue after all

**Comment by fbricon** [comment]
I opened https://github.com/angelozerr/lsp4xml/issues/223 upstream

**Comment by fbricon** [comment]
The error no longer shows up
