### ISSUE TITLE
DocBook snippets available for VSCode

### ISSUE THREAD

**Issue by tbazant** [redhat-developer/vscode-xml#882]
Hi, just to inform you that i have uploaded DocBook snippets extension for both VSCode & VSCodium, in case it's helpful. See https://open-vsx.org/extension/openSUSE/docbook-snippets

**Comment by angelozerr** [comment]
Which snippets kind this extension provide? Is the completion takes care of where the completion is triggered?

**Comment by angelozerr** [comment]
Ok I see https://github.com/openSUSE/suse-vscode-doc/blob/main/extensions/docbook-snippets/snippets/snippets.code-snippets and it means that it will provide completion even if it is not allowed.

To be context aware, we should implement https://github.com/eclipse/lemminx/issues/1468 and you could use your snippets.

**Comment by tbazant** [comment]
> Ok I see https://github.com/openSUSE/suse-vscode-doc/blob/main/extensions/docbook-snippets/snippets/snippets.code-snippets and it means that it will provide completion even if it is not allowed.

yes

> 
> To be context aware, we should implement [eclipse/lemminx#1468](https://github.com/eclipse/lemminx/issues/1468) and you could use your snippets.

That is actually a very good idea!

**Comment by angelozerr** [comment]
> That is actually a very good idea!

Please add a comment on this issue, because we need requirement user issue to work on it (it was just an idea that I had, but it is not our priority)
