### ISSUE TITLE
xml.format.preserveAttributeLineBreaks False not working with all characters

### ISSUE THREAD

**Issue by anasstahiri99** [redhat-developer/vscode-xml#888]
xml.format.preserveAttributeLineBreaks is set to false
xml.format.splitAttributes is set to false

This is an example :

Not Working 
```
<syncShipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="file:///C:/Users/aa/Canonical.xsd">
```
	
Not Working
```
<syncShipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="x">
```
	
Working 
```
<syncShipment xmlns:xsi="www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="x">
```
result :` <syncShipment xmlns:xsi="www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="x">`
	
Working
```
<syncShipment xmlns:xsi="x"
	xsi:noNamespaceSchemaLocation="x">
```
result :` <syncShipment xmlns:xsi="x" xsi:noNamespaceSchemaLocation="x">`

**Comment by anasstahiri99** [comment]
It works after enabling xml.format.legacy

**Comment by angelozerr** [comment]
@JessicaJHee could you look at this issue please.

**Comment by angelozerr** [comment]
I reopen this issue since legacy formatter should disappear.

We need to fix this issue.

**Comment by JessicaJHee** [comment]
In the current formatter, we introduced [xml.format.maxLineWidth](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md#xmlformatmaxlinewidth), which is set to 100 by default. If you increase this or turn off this setiing by setting it to `0`, the attributes will join lines in your use cases.

This example contains 102 characters, so it will not join lines as to not exceed the max line width.
```
<syncShipment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="x">
```

**Comment by anasstahiri99** [comment]
Thanks @JessicaJHee, I didn't think about that.
