### ISSUE TITLE
Configuring from Neovim

### ISSUE THREAD

**Issue by ignamartinoli** [redhat-developer/vscode-xml#893]
Hi, I'm using this Language Server with Neovim.

I want to configure it to create the directory `~/.lemminx` into `~/.cache/lemminx`.

I already figured it out that the configuration file for this should look like this:

```json
{
	"initializationOptions": {
		"settings": {
			"xml": {
				"server": {
					"workDir": "~/.cache/lemminx"
				}
			}
		}
	}
}
```

The question is, where should I put it?

**Comment by angelozerr** [comment]
This configuration must be done whenthe LSP client (vscode, Eclipse IDE, neovim, etc) starts the XML language server.

I close this issue since it us not related to vscode-xml. Please create the issue to neovim or project which manages LSP client for neovim
