### ISSUE TITLE
 npm install -g n   npm ERR! code EBADPLATFORM npm ERR! notsup Unsupported platform for n@9.1.0: wanted {"os":"!win32"} (current: {"os":"win32"}) npm ERR! notsup Valid os:  !win32 npm ERR! notsup Actual os: win32 npm ERR! 

### ISSUE THREAD

**Issue by NagarjunaParala** [redhat-developer/vscode-xml#896]
npm install -g n  
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for n@9.1.0: wanted {"os":"!win32"} (current: {"os":"win32"})
npm ERR! notsup Valid os:  !win32
npm ERR! notsup Actual os: win32

**Comment by fbricon** [comment]
The "n" module is not supported on Windows. See 
- https://github.com/npm/npm/issues/12967#issuecomment-225497383
- https://github.com/tj/n#supported-platforms

In any case this has nothing to do with vscode-xml. Closing.

**Comment by lrq3000** [comment]
Just to note that some [websites](https://blog.hubspot.com/website/update-node-js) do recommend using `npm install -g n` to update node.js on Windows, which never ever worked, so this may explain why there are so many new devs end up asking this same question over and over.

Luckily the new error message is quite explicit. But it's just so strange that so many websites still recommend this incorrect method.
