### ISSUE TITLE
npm update npm -g npm WARN EBADENGINE Unsupported engine { npm WARN EBADENGINE   package: '@salesforce/apex-node@1.6.0', npm WARN EBADENGINE   required: { node: '>=16.13.0' }, npm WARN EBADENGINE   current: { node: 'v14.17.6', npm: '9.6.4' } npm WARN EBADENGINE } npm WARN EBADENGINE Unsupported engine { npm WARN EBADENGINE   required: { node: '>=16.13.0' }, npm WARN EBADENGINE   current: { node: 'v14.17.6', npm: '9.6.4' } npm WARN EBADENGINE }  changed 16 packages in 48s  140 packages are looking for funding   run `npm fund` for details

### ISSUE THREAD

**Issue by NagarjunaParala** [redhat-developer/vscode-xml#897]
npm update npm -g
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: '@salesforce/apex-node@1.6.0',
npm WARN EBADENGINE   required: { node: '>=16.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.17.6', npm: '9.6.4' }
npm WARN EBADENGINE }
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   required: { node: '>=16.13.0' },
npm WARN EBADENGINE   current: { node: 'v14.17.6', npm: '9.6.4' }
npm WARN EBADENGINE }

changed 16 packages in 48s

140 packages are looking for funding
  run `npm fund` for details

**Comment by fbricon** [comment]
You're trying to update npm to a version requiring node >= 16.13.0 but you're currently running Node v14.17.6.
Always use an npm version compatible with the nodejs version you're using. 

In any case, this has nothing to do with vscode-xml. Closing.
