### ISSUE TITLE
Mac ARM / AS

### ISSUE THREAD

**Issue by ST33LDI9ITAL** [redhat-developer/vscode-xml#898]
Mac users shouldn't have to use Rosetta for a vscode plugin. That's ridiculous.

**Comment by thtliife** [comment]
@ST33LDI9ITAL... I can use it without rosetta on an m2 MacBook.
Steps to get it going:

1. Install [homebrew](https://docs.brew.sh/Installation)

2. Install openjdk:

```bash
brew install openjdk

# get the JAVA_HOME path in your clipboard
echo $(brew --prefix openjdk)/libexec/openjdk.jdk/Contents/Home | pbcopy
```

3. Add java home path to vscode settings for Xml Language server
* Open vscode settings: <kbd>⌘</kbd> + <kbd>.</kbd>
* In search settings bar type: `XML > Java: Home`
* Click link for Edit in settings.json
* Paste the previously copied path for `JAVA_HOME` in between the empty quotes provided in the automatically inserted `"xml.java.home": ""` property.

4. Restart VSCode

**Comment by fbricon** [comment]
@datho7561 @rgrunber  Github actions now provide M1 runners https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/, we should be able to generate the LemMinX binary for ARM-based macs.

**Comment by rgrunber** [comment]
Could someone verify that https://github.com/rgrunber/vscode-xml/releases/download/0.26.1/vscode-xml-darwin-arm64-0.26.1-693.vsix works as expected without Rosetta ?
