### ISSUE TITLE
"Auto indent" setting is broken in version 0.25.0

### ISSUE THREAD

**Issue by pvburkov** [redhat-developer/vscode-xml#899]
Hello!

Unfortunately, after my update to version 0.25.0, "auto indent" setting was broken for XML and XSD files (even with value "full" there is no indentation after pressing Enter). In version 0.24.0 this rule is working fine.

Here're some of my tech parameters (if you need more, please, tag me in comments below):
- OS: Windows 10 Home Edition 22H2 (19045.2846)
- VS Code: 1.77.3

**Comment by angelozerr** [comment]
I suspect the problem comes from https://github.com/redhat-developer/vscode-xml/commit/a17945188ade7f39a3d8ee0fbc75443db5ac3200

@JessicaJHee  @datho7561 canyou reproduce it?

**Comment by datho7561** [comment]
Yes, I can reproduce the issue, and it comes from the commit you mentioned. Sorry about that, I must have missed it in review.

**Comment by angelozerr** [comment]
> es, I can reproduce the issue, and it comes from the commit you mentioned. Sorry about that, I must have missed it in review.

No problem @datho7561 it is too my fault:) Thanks for your fix https://github.com/redhat-developer/vscode-xml/pull/900, I think you are in the right direction.

**Comment by angelozerr** [comment]
@pvburkov please note that @datho7561 did a fix now for your issue and you will able to [install prerelease](https://github.com/redhat-developer/vscode-xml#contributing) tomorrow I think to test it

**Comment by pvburkov** [comment]
@angelozerr and redhead-developer team, thank you very much! Auto-indentation works again)

**Comment by angelozerr** [comment]
@pvburkov glad it fixes your issue. The congrat is for @datho7561 and @JessicaJHee , I do nothing for this fix:)
