### ISSUE TITLE
Indent by 4 instead of 2 spaces

### ISSUE THREAD

**Issue by vorburger** [redhat-developer/vscode-xml#902]
Is 4 space indention currently hard-coded?

I (now) prefer 2 instead of 4 space indendation in XML files.

It's also recommended e.g. on https://maven.apache.org/guides/development/guide-documentation-style.html for `pom.xml`.

I tried to look for a configuration to change this on https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md, but couldn't find any....

**Comment by vorburger** [comment]
What's funny is that even (some of, it's inconsistent) the examples on https://github.com/redhat-developer/vscode-xml/blob/main/docs/Formatting.md are intended with 2 instead of 4 spaces...

Maybe I'm missing something - if so, it's probably worth to clarifty better in docs?

**Comment by angelozerr** [comment]
Nothing are hard coded. Webuse standard format settings from vscodeI mean editor.insertSpaces and editor.tabSize

**Comment by vorburger** [comment]
@angelozerr duh! I see. Sorry, I'm dumb - that wasn't clear to me. I'll propose a small PR to add a line to the doc.

**Comment by angelozerr** [comment]
>  I'll propose a small PR to add a line to the doc.

Any contribution are welcome!
