### ISSUE TITLE
Error messages hard to read

### ISSUE THREAD

**Issue by akaroml** [redhat-developer/vscode-xml#91]
When editing pom.xml file with an error, the error message showed by XML extension is very hard to read.
<img width="760" alt="screen shot 2018-11-19 at 10 12 24 am" src="https://user-images.githubusercontent.com/16755094/48682564-c92be200-ebe3-11e8-8afa-1f27dc835673.png">
It's too long
It has too much information and unnecessary details
It does not provide clear action items

Please consider improve the message by:

1. Remove all the namespaces before the actual element names: e.g. `{"http://maven.apache.org/POM/4.0.0":name2}` -> `name2`
2. Incorporate proper formatting/coloring to improve readability
3. Check similarity of the node name and rank the most possible one on top

Sample:

[XML] Invalid content was found starting with element 'name2'.
Possible values:
-> **name**
description
packaging
url
...

**Comment by fbricon** [comment]
See upstream issue: https://github.com/angelozerr/lsp4xml/issues/181

**Comment by fbricon** [comment]
So here's how it looks after overriding the error messages in https://github.com/angelozerr/lsp4xml/pull/297:
Before:
<img width="1382" alt="screen shot 2019-02-26 at 12 18 02 pm" src="https://user-images.githubusercontent.com/148698/53432684-f6e1ad80-39c0-11e9-8ceb-219dc513e081.png">

After
<img width="1380" alt="screen shot 2019-02-26 at 12 22 06 pm" src="https://user-images.githubusercontent.com/148698/53432794-2c869680-39c1-11e9-8d28-458582135aa2.png">

I'm a bit concerned by the way vscode shows the error message in the problems view.

**Comment by fbricon** [comment]
With the latest VS Code insiders, it looks much better:
<img width="1021" alt="screen shot 2019-02-26 at 12 58 35 pm" src="https://user-images.githubusercontent.com/148698/53435217-4ecee300-39c6-11e9-813e-ef549532a4d7.png">

**Comment by fbricon** [comment]
I've opened https://github.com/Microsoft/vscode/issues/69473 about the diagnostic rendering

**Comment by fbricon** [comment]
*Copying the [upstream comment ](angelozerr/lsp4xml#181) here about the changes:*

Before:

<img width="516" alt="screen shot 2019-02-25 at 12 34 22 pm" src="https://user-images.githubusercontent.com/32624665/53356601-c1be5800-38f9-11e9-983e-afa6340c3229.png">


After:

![selection_016](https://user-images.githubusercontent.com/32624665/53184071-6a06b080-35ca-11e9-8a59-393328f2ea3b.png)

---

Before:

<img width="639" alt="screen shot 2019-02-25 at 12 22 16 pm" src="https://user-images.githubusercontent.com/32624665/53355927-2d072a80-38f8-11e9-9389-cd1e887df95e.png">


After:

![selection_019](https://user-images.githubusercontent.com/32624665/53184215-a5a17a80-35ca-11e9-8d7c-1b7a21850299.png)

--- 

Before:
<img width="507" alt="screen shot 2019-02-25 at 12 08 45 pm" src="https://user-images.githubusercontent.com/32624665/53355141-5f178d00-38f6-11e9-812f-5c5c295b9254.png">

After: (Uses single quotes now)

![selection_021](https://user-images.githubusercontent.com/32624665/53184521-2eb8b180-35cb-11e9-8511-cbf921672eda.png)

---

Before:

<img width="549" alt="screen shot 2019-02-25 at 12 24 39 pm" src="https://user-images.githubusercontent.com/32624665/53355993-5e7ff600-38f8-11e9-9865-2c95ee5c8daf.png">

After:

![selection_022](https://user-images.githubusercontent.com/32624665/53184649-6c1d3f00-35cb-11e9-90af-7a243017e314.png)

---

Before:

<img width="522" alt="screen shot 2019-02-25 at 12 36 37 pm" src="https://user-images.githubusercontent.com/32624665/53356742-1b268700-38fa-11e9-89e0-cb6226a4c4e7.png">


After:

![selection_024](https://user-images.githubusercontent.com/32624665/53184806-b7375200-35cb-11e9-8701-6ba491e36a0e.png)

---

Before:

<img width="529" alt="screen shot 2019-02-25 at 12 17 24 pm" src="https://user-images.githubusercontent.com/32624665/53355725-a3eff380-38f7-11e9-9312-f50920fb2c97.png">


After:

![selection_026](https://user-images.githubusercontent.com/32624665/53185035-32006d00-35cc-11e9-9ff5-fbfaa25d554e.png)
