### ISSUE TITLE
Unable to recognize JavaScript/TypeScript inside XML tags 

### ISSUE THREAD

**Issue by zC4sTr0** [redhat-developer/vscode-xml#913]
Hello everyone.
I have a problem to solve in my project, which do have very extensive use of the RedHat XML plugin for vscode. This issue is very important for us and can amazingly improve our productivity

When using the RedHat XML component for VSCode, I encountered an issue where my VSCode cannot understand that certain parts within XML tags contain JavaScript/TypeScript code. Consequently, the VSCode does not apply JavaScript/TypeScript features, such as syntax highlighting, IntelliSense, and other related plugins, within these JavaScript/TypeScript sections.

**Expected Behavior:**

I would like to have an XML document with predominantly XML content, leveraging the features provided by the RedHat XML component for VSCode. However, when I include JavaScript/TypeScript code within certain XML tags, I expect VSCode to recognize that specific section as JavaScript/TypeScript and apply all the relevant language features and plugins accordingly.

**Current Behavior:**

Currently, when I include JavaScript/TypeScript code inside XML tags, the RedHat XML component treats the entire file as XML, and thus, the JavaScript/TypeScript code is not recognized as such, leading to a lack of language-specific support for that section.

**Example:**

```xml
<exampleTag>
    <script language="JavaScript">
        <![CDATA[
            //HERE THE VSCODE IS SUPPOSED TO UNDERSTAND THAT IS JAVASCRIPT AND APPLY EVERY JS FEATURE
            importClass(Packages.br.com.davinti.vitruvio.spi.is.DatabaseSnippet); //function declared in types which should be recognized
            importClass(Packages.br.com.davinti.base.vaadin.components.layout.MessageBox); 
            var componentes = libService.loadScript('vaadinComponents');
            
            var dbUpdate = function(id, plan, motivo_excesso) {
               
                var sql = 'UPDATE PCP_ITENS SET planejado = :planejado, MOTIVO_EXCESSO = :parMotivoExcesso WHERE chave = :chave';
                vQueryService.doInTransaction('superus_producao', new DatabaseSnippet() {
                    execute: function(db, tx) {
                        var params = new java.util.HashMap();
                        params.put("chave", id);
                        params.put("planejado", Number(plan).toFixed(3));
                        params.put("parMotivoExcesso", motivo_excesso);
                        db.update(sql, params);
                    }
                });
                
            }; 
        ]]>
    </script>
</exampleTag>
```

**Desired Solution:**

I would like the RedHat XML component for VSCode to behave similarly to the default behavior in **VSCode when editing HTML documents**. In HTML files, **when I include a <script> tag, VSCode correctly recognizes the contained code as JavaScript/TypeScript and applies all relevant language features specifically for that JavaScript/TypeScript section**. I expect the same behavior for my custom XML files with embedded JavaScript/TypeScript.

**Additional Information:**

VSCode Version: 1.77.0
RedHat XML Component Version: 0.25.0
Operating System: Windows 10/11

**Comment by fbricon** [comment]
it might be possible, we've done similar things (getting HTML support in Qute templates in [vscode-quarkus](https://github.com/redhat-developer/vscode-quarkus/commit/f38f4caaf218cf9c6ce91e64a0d9cd632314a483))

But then how do we determine if something needs to be treated as Javascript? `<script language="JavaScript">` might be very specific to your use case, I'd be more interested in a general solution. We could also provide HTML or some other language support in some XML sections

**Comment by zC4sTr0** [comment]
Thank you for considering the possibility of improving language support for custom XML files with embedded JavaScript/TypeScript in VSCode. y use case is indeed very specific and I understand the need for a general solution that can cater to various scenarios. 
Here are three approaches that can be considered to achieve better language support for JavaScript/TypeScript in custom XML files: 

**1. Language Identifier:** (maybe not the best)
Instead of relying on the specific `<script language="JavaScript">` tag, we could introduce a language identifier attribute in the opening `<script>` tag. For example, `<script lang="javascript">` or `<script lang="typescript">`. This approach aligns with the behavior in HTML files where the `lang` attribute specifies the script's language. Then, VSCode can recognize the appropriate language and provide relevant language support within those sections.

**2. Custom Language Comment Tags:** (maybe better)
We could introduce custom comment tags in the XML, similar to how some code editors handle language selection in code blocks. For example:

```xml
<exampleTag>
    <!-- language: javascript -->
    <![CDATA[
        // JavaScript code here
    ]]>
</exampleTag>

3. Language Selector in VSCode Status Bar: (maybe not possible)
We could implement a language selector in the VSCode status bar. When the cursor is inside a <script> tag, the language selector allows users to manually choose the language (e.g., JavaScript/TypeScript). Based on the user's selection, VSCode can then apply the corresponding language support.

I hope these suggestions help in devising a more generalized approach to address the language support for embedded JavaScript/TypeScript in custom XML files. I am avaiable to help with such changes, if I know how to do them =D

I am checking quarkus to learn more about how to solve this issue.
Thank you

**Comment by angelozerr** [comment]
I fear that this issue is very hard to implement since LSP doesn't support embedded language. I add a comment at https://github.com/microsoft/language-server-protocol/issues/1757#issuecomment-1623078953

> it might be possible, we've done similar things (getting HTML support in Qute templates in [vscode-quarkus](https://github.com/redhat-developer/vscode-quarkus/commit/f38f4caaf218cf9c6ce91e64a0d9cd632314a483))

In case of Qute, we use

 * the HTML language server which supports HTML and embedded CSS, Javascript.
 * the Qute language server

but both of language servers are independent and there are not some embedded region. It means that you have HTML completion inside Qute region which is bad.

**Comment by zC4sTr0** [comment]
@angelozerr if qute won't work, do you have any idea about how this issue could be solved?

**Comment by angelozerr** [comment]
To be honnest with you,I fear that it is a very hard topic and I will not have time to work on it, since no people except you requires this support.

The HTML language server can support embed CSS and JavaScript code by:

 * detecting JavaScript, CSS regions (we could do that in LemMinx, the XML language server used by vscode-xml)
 * call completion, validation, etc from the proper vscode-$language-service (https://github.com/microsoft/vscode-css-languageservice for CSS, etc). As HTML language server is written in TypeScript, it can do that. LemMinx is written in Java so it cannot follow the same strategy. So the idea is to delegate this stuff in the LSP client and it is the goal of LSP client to return to the XML language server the completion result. I thinkthis part can be hard because you will need to stores cache on LSP client of the regions, etc

**Comment by zC4sTr0** [comment]
@angelozerr thank you very much for the description of your tips, this direction is very important to someone who don't know how to start.

So in a nutshell:

- I will fork this repository and firstly implement a way to determine which sections are JS/TS sections (as we were discussing).
- I will implement the javascript server (an issue here: I couldn't find 'officia'l vscode-typescript/javascript-languageservice from microsoft). So as I understand you suggest to use  (https://github.com/microsoft/vscode-css-languageservice) since it has this feature, right?
- create a channel to send this info to the typescript server and get the informatio of errors etc

Some questions I wonder if you can give us some tips:
- Will the highlights (erros, variables, reserved words etc) be created by the LemMinx language server (based on parrallel response from ts/js server)?
- You suggest to use the HTML language server (https://github.com/microsoft/vscode-css-languageservice) since it has this feature, right?

I wonder if i'ts possible to do it in a way that it can be also useful to vscode-xml.
We will work on that this month and it would be better if we also could contribute to this wonderful project insted of just running our own vscode-xml forked version.

Thnak you very much. Every information you can share is very useful!

**Comment by dinogomez** [comment]
I had a headache with this problem and made an extension to handle the embedded code inside the CDATA Tags.

[CDATA JS Highlighter](https://marketplace.visualstudio.com/items?itemName=PaulGomez.cdata-js-highlighter)

**Comment by zC4sTr0** [comment]
I also solved the problem using an extension.

If you need any help on this issue, send me a message.

For me the issue is solved .

**Comment by angelozerr** [comment]
@dinogomez your extendion is great but it manages only syntax coloration with textmate. The hard part is about completion validation etc

@zC4sTr0 could you please share in this issue how to you resolved your issue pleaqe in order to vscode xml community benefits with yout solution. Thanks!__

**Comment by angelozerr** [comment]
> @angelozerr This isn't such a strange request, as putting JS / Typescript inside of CDATA is the STANDARDS COMPLIANT way to embed them in XML.


I agree

> In fact, it works great in XHTML. 

HTML language server can support embedded css and js which uses some js and css services coming from css and js language server. Those css´ js s de rvices are written in TypeScript so we cannot use them in our xml language server which are written in Java.

> Look around, and you'll find it everywhere. My pain point is Shibboleth IdP configuration. I can understand why zC4sTr0 got frustrated with you and gave up. I may eventually return to this extension, but without CDATA support I may not bother.

Supporting this issue is very hard and will take a lot of time to implement it. But any contribution are welcome.

**Comment by dnorthup-ums** [comment]
@angelozerr I'm not a wizzard at VSCode Extensions, but I did help maintain an Atom plugin for while. If there's something I can do to help test, debug, or gather data, let me know. Otherwise, I'll just let this one be for now.
Cheers.

**Comment by angelozerr** [comment]
I'm  really sorry @dnorthup-ums but supporting this issue is not a trivial issue, it is not our priority and we have very busy with other topics, but if we have some contributions we will do our best to review them.
