### ISSUE TITLE
"Element type ... must be declared" when using DTD with XML catalog

### ISSUE THREAD

**Issue by TheKvist** [redhat-developer/vscode-xml#914]
I want to edit some MusicXML files with VSCode, but can not get the XML extension to load the schema. I am trying to follow the [MusicXML tutorial](https://www.w3.org/2021/06/musicxml40/tutorial/hello-world/) and can't get the first example to work. 

Steps to reproduce:
1. clone [the repository](/w3c/musicxml), which contains the XML catalog located at [`schema/catalog.xml`](https://github.com/w3c/musicxml/blob/gh-pages/schema/catalog.xml)
   ```sh
   git clone https://github.com/w3c/musicxml.git
   ```
1. register the XML catalog in the extension settings
   ```json
   "xml.catalogs": [
        "/path/to/musicxml/schema/catalog.xml"
    ]
   ```
1. set up a minimal example in VSCode
   ```
   <?xml version="1.0" encoding="UTF-8" standalone="no"?>
   <!DOCTYPE score-partwise PUBLIC
       "-//Recordare//DTD MusicXML 4.0 Partwise//EN"
       "http://www.musicxml.org/dtds/partwise.dtd">
   <score-partwise version="4.0">
   </score-partwise>
   ```

After completing the above steps, I *can* navigate to the DTD by ctrl-clicking the file name in the DOCTYPE definition. However, all elements are marked with the error that they "need to be declared".

I'm a bit puzzled that it's so hard to get this working, but I have no idea about XSD, DTD or any of the other XML schema techniques, so I am probably just missing something. [The docs](https://github.com/redhat-developer/vscode-xml/wiki/XMLValidation#XML-catalog-with-DTD) do not seem to be very detailed regarding this topic, so searching there didn't help either.

**Comment by TheKvist** [comment]
@angelozerr Wow that was fast, and it did the trick! Thank you so much and apologies for the noise

**Comment by angelozerr** [comment]
@TheKvist glad it works for you. 

@rgrunber @fbricon @datho7561  We should really provide a code action which ask to the user to enable this settings. We have so many users who have this problem. The hard part is to detect that there are some entities to load, without loading them.

**Comment by angelozerr** [comment]
> Thank you so much and apologies for the noise

Please don't apologies, don't hesitate to create any issue if you have any problems. We try to fix them or improve the documentation. If you think document must be improved, please contribute it, thanks.

**Comment by goyalyashpal** [comment]
> it did the trick

thanks for sharing that it worked for you. yes, it worked for me too. 

<details open><summary>Minimal Working Example/Reproducing Sample:</summary>

<br/>

I was trying with this:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<!-- <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> -->

<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head><title>My Webpage</title></head>
<body>
  shown error 'Element type "..." must be declared.' indicates the error of this issue
  shown error 'The content of "body" must match "...".'  indicates validation is working good :)
  <p>hello, homepage</p>
</body>
</html>
```

</details>

surprisingly, when instead of `1.1`, the dtd used is `XHTML 1.0 STRICT ...` (the commented out doctype declaration above) the validation works fine even with defaults (i.e. `"xml.validation.resolveExternalEntities": "false"`). i wonder why.

note: it requires executing "XML: Restarting XML Language Server" after resetting this option back to false for the original behaviour to show up again.

Refer dtds for web docs:
* [valid-dtd-list.html] "Recommended Doctype Declarations to use in your Web document"

[valid-dtd-list.html]: https://www.w3.org/QA/2002/04/valid-dtd-list.html "🔍 : xhtml doctype"

**Comment by goyalyashpal** [comment]
> The hard part is to detect that there are some entities to load
> \- @angelozerr at https://github.com/redhat-developer/vscode-xml/issues/914#issuecomment-1628891180

`The entity "%" was referenced , but not declared` maybe this error can be used?
