### ISSUE TITLE
Getting a ContentIllegalInProlog error in my maven.config file

### ISSUE THREAD

**Issue by tristan957** [redhat-developer/vscode-xml#92]
```
${workspaceRoot}/.mvn/maven.config

--settings .mvn/local-settings.xml
```
leads to
```
[xml] Content is not allowed in prolog. [ContentIllegalInProlog]
```

This is not an XML file as far as I can tell. Trying to point Maven at a mirror using project specific settings. Maven from command line works fine.

**Comment by fbricon** [comment]
VSCode [associates the .config extension to xml ](https://github.com/Microsoft/vscode/blob/master/extensions/xml/package.json#L18) by default.

I suggest you open a bug upstream for the VS Code team to remove that association.

Meanwhile LSP4XML does its job. It's been told this is an XML file, but doesn't validate so reports the error.
As an immediate workaround, you can either set the proper language for that file by clicking on the language mode icon (XML here):
<img width="137" alt="screen shot 2018-11-19 at 5 00 59 pm" src="https://user-images.githubusercontent.com/148698/48738022-b0402280-ec1d-11e8-8a23-f537da1db558.png">

Or you can set a file association in your vscode settings.json:
```json
	"files.associations": {
		"jvm.config": "plaintext",
		"mvn.config": "plaintext",
   },
```

There's nothing for us to do here, so I'll close this issue.

**Comment by tristan957** [comment]
I will open a report upstream. Sorry for the issue.
