### ISSUE TITLE
"Surround" Commands are not shown in the Command Palette

### ISSUE THREAD

**Issue by enxio** [redhat-developer/vscode-xml#923]
The commands `xml.refactor.surround.with.*` are not shown in the command palette. The other ones are, e.g. `xml.validation.current.file` or `xml.restart.language.server` are shown and can be invoked.

I can assign keys to these "surround" commands just fine, and then they work as expected, I just cannot invoke them via the palette.

**Comment by enxio** [comment]
I am using the preview: v0.26.2023072504

**Comment by angelozerr** [comment]
Indeed we introduced a bug, I create a PR to fix it https://github.com/redhat-developer/vscode-xml/pull/924

Thanks @enxio for having reported the issue!

**Comment by angelozerr** [comment]
@enxio your issue should be fixed, you have to wait tomorrow to install the prerelease. Please try it and give us feedback if it is working for you. Thanks.

**Comment by enxio** [comment]
Hi @angelozerr, I just got the update and it now works as expected. Thanks a lot for the fix and the fast response!

**Comment by angelozerr** [comment]
Great thanks for your feedbavk.
