### ISSUE TITLE
Show attributes in breadcrumb?

### ISSUE THREAD

**Issue by srl295** [redhat-developer/vscode-xml#926]
example file [here](https://github.com/unicode-org/cldr/blob/main/common/main/ps.xml)

<img width="738" alt="image" src="https://github.com/redhat-developer/vscode-xml/assets/855219/f8fa3a0a-15d4-40ff-b884-9dfbb7c56756">

looking at the breadcrumb, it says my element has a parent of, for example, `<unitLength>` - but there are several unitLength elements distinguished by attributes.

Is there any way to get the attributes, such as `<unitLength type="long">` into the breadcrumb, at least on hover? 

In the popup list where it shows:

- unitLength
- unitLength
- unitLength

… that list could easily show the attributes of the three `unitLength` elements, in this case there's only one.

**Comment by angelozerr** [comment]
You can configure symbol to show attribute in outline, see https://github.com/redhat-developer/vscode-xml/blob/main/docs/Symbols.md#xmlsymbolsfilters

I don't know if it will affect the breadcrumb.

**Comment by srl295** [comment]
Thanks! I will try that.

**Comment by angelozerr** [comment]
@srl295 I close the issue because I think  https://github.com/redhat-developer/vscode-xml/blob/main/docs/Symbols.md#xmlsymbolsfilters is the answer of your issue.

If I'm wrong, please reopen the issue.

**Comment by srl295** [comment]
@angelozerr it works, thanks
