### ISSUE TITLE
Node 14 is EOL

### ISSUE THREAD

**Issue by datho7561** [redhat-developer/vscode-xml#928]
Node 16 will also be EOL (no maintenance) on September 11 2023. As a result, we should upgrade to Node 18.

A part of this migration is updating the version of npm used and updating `package-lock.json`. npm v7, which ships with Node 16, changed the format of this file. This might cause some complications with `npm-force-resolutions`, which is a library we use to for all instances of a library to a specified version in the lockfile.

**Comment by fbricon** [comment]
can't update to 18 before the embedded version in VS Code updates too. Currently at 16

**Comment by fbricon** [comment]
well insiders's on 18, so probably for next month

**Comment by datho7561** [comment]
I don't expect we will do a new release before the next VS Code release, unless something urgent comes up
