### ISSUE TITLE
Extension isn't working properly for Windows User folders with space characters 

### ISSUE THREAD

**Issue by Ivo-Andrade-Taxation-Mind** [redhat-developer/vscode-xml#939]
Hi!, first I'd love to compliment the work on the extension! Unfortunately, I've recently ran into an odd issue, the extension wasn't working out of the box at a different Windows install I manage. Been cracking my head trying to understand why until I finally figured to check the extension output and found this:
```
[Info  - 5:31:03 PM] Unable to parse effective pom. Cause: Command failed: mvn help:effective-pom -Doutput='\c%3A\Users\Name Surname\Documents\git\project\target\effective-pom.xml' --quiet -f '\c%3A\Users\Name Surname\Documents\git\project\target\in-memory-pom.xml'
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 
```
I've attempted to change my user folder name, but it's been more hassle than it's worth, as much as it would to just starting a fresh new install. I have yet to replicate this on a fresh Windows account (apologizes for that!, but I will do once I'm home in a couple of hours).

I'm not sure if this is the only issue getting in the way of the extension not working, but would hope it is and it could be an easy fix for a future extension update!

VSCode version info:

> Version: 1.84.1 (user setup)
> Commit: 2b35e1e6d88f1ce073683991d1eff5284a32690f
> Date: 2023-11-06T12:35:59.022Z
> Electron: 25.9.2
> ElectronBuildId: 24603566
> Chromium: 114.0.5735.289
> Node.js: 18.15.0
> V8: 11.4.183.29-electron.0
> OS: Windows_NT x64 10.0.22621

Console output:
```
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 
[Info  - 5:27:31 PM] Unable to parse effective pom. Cause: Command failed: mvn help:effective-pom -Doutput='\c%3A\Users\Name Surname\Documents\git\project\target\effective-pom.xml' --quiet -f '\c%3A\Users\Name Surname\Documents\git\project\target\in-memory-pom.xml'
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 

manifest parse took 37 ms, found 10 deps
sendDiagnostics: 0
fetch vulns took 7440 ms
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 
[Info  - 5:31:00 PM] Unable to parse effective pom. Cause: Command failed: mvn help:effective-pom -Doutput='\c%3A\Users\Name Surname\Documents\git\project\target\effective-pom.xml' --quiet -f '\c%3A\Users\Name Surname\Documents\git\project\target\in-memory-pom.xml'
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 

manifest parse took 23 ms, found 10 deps
[Warn  - 5:31:03 PM] fetch error. Error: Command failed: mvn -q help:effective-pom -Doutput=C:\Users\USER~1\AppData\Local\Temp\exhort_yjCqmW\effective-pom.xml -f C:\Users\USER~1\AppData\Local\Temp\exhort_yjCqmW\target-pom.xml
sendDiagnostics: 0
fetch vulns took 2974 ms
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 
[Info  - 5:31:03 PM] Unable to parse effective pom. Cause: Command failed: mvn help:effective-pom -Doutput='\c%3A\Users\Name Surname\Documents\git\project\target\effective-pom.xml' --quiet -f '\c%3A\Users\Name Surname\Documents\git\project\target\in-memory-pom.xml'
POM file "'\c%3A\Users\Name" specified the -f/--file command-line argument does not exist 

manifest parse took 22 ms, found 10 deps
sendDiagnostics: 0
fetch vulns took 5228 ms
```

**Comment by angelozerr** [comment]
Your trace seems about parse of pom xml file. If it that I think the problem comes from vscode-maven.

What is your problem?

**Comment by angelozerr** [comment]
vscode-xml is a vscode extension which provides XML support to editing XML files and not Maven support.

I suggest that you report your issue at https://github.com/Microsoft/vscode-maven

**Comment by Ivo-Andrade-Taxation-Mind** [comment]
Well, guess VS Code showing it as an extension error was quite a curveball then, I'll take this to vscode-maven then, thanks for your time!

**Comment by fbricon** [comment]
Actually, the issue should be reported against the [Dependency Analytics repo](https://github.com/fabric8-analytics/fabric8-analytics-vscode-extension/issues)
