### ISSUE TITLE
vscode xml 0.3.0 is broken?

### ISSUE THREAD

**Issue by angelozerr** [redhat-developer/vscode-xml#94]
I have installed  vscode-xml-0.3.0-630.vsix and nothing is working (hover, completion, etc). I have checked that in the trace that vscode client sends requests, but there is never response from the lsp4xml server.

I don't know if it's an issue with lsp4xml? It works with Eclipse IDE (LSP4E)

I'm using VSCode:

```
Version : 1.29.1 (system setup)
Validation : bc24f98b5f70467bc689abf41cc5550ca637088e
Date : 2018-11-15T19:13:36.375Z
Electron: 2.0.12
Chrome : 61.0.3163.100
Node.js : 8.9.3
V8 : 6.1.534.41
Architecture : x64
```

**Comment by angelozerr** [comment]
Just for your information, I have removed 0.3.0 installation, reinstall 0.2.0 and change the xml-language-server.all.jar with my mine (from master) and it works great.

I hav enot found why 0.3.0 doesn't work?

**Comment by fbricon** [comment]
I installed vscode-xml-0.3.0-630.vsix and it works for me.

<img width="968" alt="screen shot 2018-12-01 at 12 30 58 pm" src="https://user-images.githubusercontent.com/148698/49331032-fe7deb80-f564-11e8-8c91-607807e0675c.png">

Check with `jps` if you have any org.eclipse.lsp4xml-all.jar processes running, and kill them if necessary.

**Comment by fbricon** [comment]
@angelozerr [recent visx](http://download.jboss.org/jbosstools/vscode-xml/staging/?C=M;O=D ) still doesn't work for you?

**Comment by angelozerr** [comment]
I will retry it ASAP and gives you feedback.

**Comment by fbricon** [comment]
ping?

**Comment by fbricon** [comment]
can we close it?

**Comment by fbricon** [comment]
seems to work now, 0.3.0 has been released anyway.
