### ISSUE TITLE
XML support crashes when workspace folders are empty

### ISSUE THREAD

**Issue by Chadehoc** [redhat-developer/vscode-xml#940]
I had used this extension with success some times ago (say, last month), including schema validation and formatting.

When I came back to it, editing the same XML files I did before, suddenly the only item offered by the command palette had become "XML: Open XML Documentation", and nothing works (validation, formatting, auto-closing tag when typing "/"...).

I have tried to reinstall the extension, remove every personnalized settings, install the RC version, disable all other extensions... in vain. (Note: `vscode-xml` was my latest installed extension.)

**Comment by angelozerr** [comment]
Could you enable trace with `xml.trace.server:verbose` please and share the log.Thanks!

**Comment by angelozerr** [comment]
Thanks so much @Chadehoc for yoyr feedback and trace. is it possible to share your vscode project which causes the problem please.

**Comment by angelozerr** [comment]
@Chadehoc I did a fix in https://github.com/redhat-developer/vscode-xml/pull/941

**Comment by angelozerr** [comment]
@Chadehoc my PR has been merged, tomorrow you should enjoy with vscode-xml prerelease https://github.com/redhat-developer/vscode-xml#contributing (checks the date before installing).

Please give us feedback if it fixes your issue.
