### ISSUE TITLE
OpenQuoteExpected error for ATTLIST breaks DTD validation

### ISSUE THREAD

**Issue by ejgutierrez74** [redhat-developer/vscode-xml#943]
Im trying to validate xml file against DTD file.
The problem is that vscode-xml only says that is an error in DTD file...no more info...and then is difficult to debug...

![Captura desde 2023-11-11 13-04-23](https://github.com/redhat-developer/vscode-xml/assets/11474846/92217127-a257-4cc1-8960-5c929e13eca0)

But if you use a internet/online validator the info is much clearer ( for example https://www.xmlvalidation.com/ ):

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/26f0cc36-a014-4cf5-b0fe-ee0c52afdbe8)

or this:

![Captura desde 2023-11-11 13-04-42](https://github.com/redhat-developer/vscode-xml/assets/11474846/1c51d0f4-24d7-4eb8-a15b-e0dfc1353260)

So im missing something ? is there any chance that vscode-xml should show a list of errors/warnings.like when you test if an xml file is well formed ? Would be really useful...

**Comment by angelozerr** [comment]
Could you share your xml and ďtd files please.

**Comment by ejgutierrez74** [comment]
Yes of course
For example these ones....many errors to debug...

[bautistamonicaoriginal.zip](https://github.com/redhat-developer/vscode-xml/files/13325925/bautistamonicaoriginal.zip)

Also once corrected:

[monicacorrected.zip](https://github.com/redhat-developer/vscode-xml/files/13325931/monicacorrected.zip)

**Comment by ejgutierrez74** [comment]
Also you can make something better with netbeans....
https://www.youtube.com/watch?v=DQpX9bns-d0

But id like to see all the errors at once generated, as vscode-xml do it when xml file is not well formed.
Seems that netbeans only shows the first error, at least is something better than this extension...

The better place i found is the online validator linked in previous post...

Thanks

**Comment by ejgutierrez74** [comment]
Edited first post, because i uploaded the same image twice...No you can see at least two errors validating the xml against a DTD file...

**Comment by fbricon** [comment]
Testing your sample files, I found an error in the XML language server:
```
[Error - 14:12:17] Nov 13, 2023 02:12:17 org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDValidator doDiagnostics()
Message: Unexpected DTDValidator error
java.lang.NullPointerException: Cannot invoke "org.eclipse.lemminx.dom.DOMAttr.getNodeAttrName()" because "attr" is null
	at org.eclipse.lemminx.utils.XMLPositionUtility.createAttrNameRange(XMLPositionUtility.java:217)
	at org.eclipse.lemminx.utils.XMLPositionUtility.selectAttributeNameAt(XMLPositionUtility.java:98)
	at org.eclipse.lemminx.extensions.contentmodel.participants.XMLSyntaxErrorCode.toLSPRange(XMLSyntaxErrorCode.java:286)
	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.LSPErrorReporterForXML.toLSPRange(LSPErrorReporterForXML.java:62)
	at org.eclipse.lemminx.extensions.xerces.AbstractReferencedGrammarLSPErrorReporter.toLSPRange(AbstractReferencedGrammarLSPErrorReporter.java:84)
	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.internalToLSPRange(AbstractLSPErrorReporter.java:216)
	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.reportError(AbstractLSPErrorReporter.java:91)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
	at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanAttDefaultDecl(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanAttlistDecl(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDTDExternalSubset(Unknown Source)
	at org.apache.xerces.impl.dtd.XMLDTDLoader.loadGrammar(Unknown Source)
	at org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDValidator.doDiagnostics(DTDValidator.java:60)
	at org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDDiagnosticsParticipant.doDiagnostics(DTDDiagnosticsParticipant.java:53)
	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:67)
	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:49)
	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:190)
	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:204)
	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:716)
	at org.eclipse.lemminx.XMLTextDocumentService.lambda$validate$35(XMLTextDocumentService.java:691)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
```

**Comment by angelozerr** [comment]
I tested now and I discover the same problem. @ejgutierrez74 vscode-xml should manage your DTD validation like you wished (show error detail instead of just 1 error) but it seems that we have a bug with your DTD

**Comment by ejgutierrez74** [comment]
Perhaps something related to #945 . vscode-xml could not detect or get the DTD file so it gives the first error....Just an idea...

Im a teacher of computer science  in vocational education and this error has been reproduced by different students also

**Comment by ejgutierrez74** [comment]
> Testing your sample files, I found an error in the XML language server:
> 
> ```
> [Error - 14:12:17] Nov 13, 2023 02:12:17 org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDValidator doDiagnostics()
> Message: Unexpected DTDValidator error
> java.lang.NullPointerException: Cannot invoke "org.eclipse.lemminx.dom.DOMAttr.getNodeAttrName()" because "attr" is null
> 	at org.eclipse.lemminx.utils.XMLPositionUtility.createAttrNameRange(XMLPositionUtility.java:217)
> 	at org.eclipse.lemminx.utils.XMLPositionUtility.selectAttributeNameAt(XMLPositionUtility.java:98)
> 	at org.eclipse.lemminx.extensions.contentmodel.participants.XMLSyntaxErrorCode.toLSPRange(XMLSyntaxErrorCode.java:286)
> 	at org.eclipse.lemminx.extensions.contentmodel.participants.diagnostics.LSPErrorReporterForXML.toLSPRange(LSPErrorReporterForXML.java:62)
> 	at org.eclipse.lemminx.extensions.xerces.AbstractReferencedGrammarLSPErrorReporter.toLSPRange(AbstractReferencedGrammarLSPErrorReporter.java:84)
> 	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.internalToLSPRange(AbstractLSPErrorReporter.java:216)
> 	at org.eclipse.lemminx.extensions.xerces.AbstractLSPErrorReporter.reportError(AbstractLSPErrorReporter.java:91)
> 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
> 	at org.apache.xerces.impl.XMLErrorReporter.reportError(Unknown Source)
> 	at org.apache.xerces.impl.XMLScanner.reportFatalError(Unknown Source)
> 	at org.apache.xerces.impl.XMLScanner.scanAttributeValue(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanAttDefaultDecl(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanAttlistDecl(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDecls(Unknown Source)
> 	at org.apache.xerces.impl.XMLDTDScannerImpl.scanDTDExternalSubset(Unknown Source)
> 	at org.apache.xerces.impl.dtd.XMLDTDLoader.loadGrammar(Unknown Source)
> 	at org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDValidator.doDiagnostics(DTDValidator.java:60)
> 	at org.eclipse.lemminx.extensions.dtd.participants.diagnostics.DTDDiagnosticsParticipant.doDiagnostics(DTDDiagnosticsParticipant.java:53)
> 	at org.eclipse.lemminx.services.XMLDiagnostics.doExtensionsDiagnostics(XMLDiagnostics.java:67)
> 	at org.eclipse.lemminx.services.XMLDiagnostics.doDiagnostics(XMLDiagnostics.java:49)
> 	at org.eclipse.lemminx.services.XMLLanguageService.doDiagnostics(XMLLanguageService.java:190)
> 	at org.eclipse.lemminx.services.XMLLanguageService.publishDiagnostics(XMLLanguageService.java:204)
> 	at org.eclipse.lemminx.XMLTextDocumentService.validate(XMLTextDocumentService.java:716)
> 	at org.eclipse.lemminx.XMLTextDocumentService.lambda$validate$35(XMLTextDocumentService.java:691)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796)
> 	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
> 	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
> 	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
> 	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
> 	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
> ```

??What do you mean ? That the xml file is wrong ? Its well formed accorded to vs-code, xml-copy editor and netbeans....

**Comment by ejgutierrez74** [comment]
> I tested now and I discover the same problem. @ejgutierrez74 vscode-xml should manage your DTD validation like you wished (show error detail instead of just 1 error) but it seems that we have a bug with your DTD

Also if possible would be nice like XML Copy Editor, from Command Palette or whaever....one instruction to test if the xml file is well formed...and other to Validate XML. No seems that vs-code runs it all together.... Just a suggestion
Thanks for your work

**Comment by fbricon** [comment]
The NPE is a bug in the language server, we need to fix it. Hopefully, this should restore the DTD validation as you expect it.

Once the DTD bug is fixed, the validation should work OOTB, no need for a specific command. XML errors are visible in the problems view like:

<img width="1321" alt="Screenshot 2023-11-14 at 13 07 27" src="https://github.com/redhat-developer/vscode-xml/assets/148698/9f7474b9-d693-48ba-8a25-055665afbe19">

**Comment by angelozerr** [comment]
@ejgutierrez74 indeed it is a bug from vscode xml. I plan to fix soon

**Comment by ejgutierrez74** [comment]
But id 

> The NPE is a bug in the language server, we need to fix it. Hopefully, this should restore the DTD validation as you expect it.
> 
> Once the DTD bug is fixed, the validation should work OOTB, no need for a specific command. XML errors are visible in the problems view like:
> <img alt="Screenshot 2023-11-14 at 13 07 27" width="1321" src="https://user-images.githubusercontent.com/148698/282769464-9f7474b9-d693-48ba-8a25-055665afbe19.png">

Thank you very much.
Would it possible or as i said make two different instructions: one to test if a xml file is well formed and other to validate it against DTD file.
Or at least in problems output, make a clear difference ( ideally separated by horizontal line or something like that ) between the xml file ( errors of not well formed file) and errors that came from DTD ( from validation of the xml file against DTD). Because mixing the two diferent source of errors, would be some kind of mess....specially to my students.

Hope this would be fix soon.
Thanks for your effort and work.

**Comment by angelozerr** [comment]
> Would it possible or as i said make two different instructions: one to test if a xml file is well formed and other to validate it against DTD file.
Or at least in problems output, make a clear difference ( ideally separated by horizontal line or something like that ) between the xml file ( errors of not well formed file) and errors that came from DTD ( from validation of the xml file against DTD). Because mixing the two diferent source of errors, would be some kind of mess....specially to my students.

I understand what you mean, please create a new issue for that and let this issue to fix your DTD bug.

> Hope this would be fix soon.

I'm working on it now.

**Comment by angelozerr** [comment]
@ejgutierrez74 I have fied the bug and now you can see the error in XML:

![image](https://github.com/redhat-developer/vscode-xml/assets/1932211/92083bf0-fd3a-4fc7-b4e0-2f5d056840f6)

if you click on the DTD error, it opens the DTD file and you can see the error

![image](https://github.com/redhat-developer/vscode-xml/assets/1932211/69a22cf2-3de7-4f6a-8295-0abf1a9430ff)

Is it the behavior that you expect?

**Comment by ejgutierrez74** [comment]
First of all thank you for your effort and work.

Second when can i test it ? New release ?

Third: for me not a bad solution, for me i dont know even if its possible, in the output/problems console put a list of all the validation errors, not just the first one ( just like when you test a xml file is well formed).

pd: i opened as you suggested a new issue regarding this, and i have answer you

**Comment by fbricon** [comment]
the DTD parser is not really fault tolerant, so you only get 1 DTD error at a time.

The fix will be available has a pre-release soon after it's merged

**Comment by angelozerr** [comment]
We stop reporting dtd error when there are a fatal error coming from Xerces. It will avoid reporting bad errors once the first error is fixed.

**Comment by angelozerr** [comment]
@ejgutierrez74 once pre release build will be done (I think tomorrow), you will able to install pre release https://github.com/redhat-developer/vscode-xml#contributing to enjoy with the fix.

**Comment by angelozerr** [comment]
@ejgutierrez74 is it working now with the pre release?

**Comment by ejgutierrez74** [comment]
Lets say 50%:

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/492f1f3e-22be-482f-a3da-9bac795a35d9)


![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/a9a409af-4287-49b7-92eb-7d8394ce4523)


![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/88e2a494-50db-4600-85a0-0bc916f9dc42)

And finally:

![imagen](https://github.com/redhat-developer/vscode-xml/assets/11474846/65529be3-cbd8-4aec-bfe1-302bbc79e992)

**Comment by angelozerr** [comment]
Your screenshot is about completion, we have not fixed that

This original issue was about DTD errors descriptions which was not displayed, now ypu can see the error:

![image](https://github.com/redhat-developer/vscode-xml/assets/1932211/92083bf0-fd3a-4fc7-b4e0-2f5d056840f6)

**Comment by ejgutierrez74** [comment]
Oh sorry then its fixed...as far as i have tested these days...

**Comment by angelozerr** [comment]
Great thanks for your feedback.

If there are no bugs you should see dtd error now in the description for other dtd écrous and you click on the link error to open the dtd file and jump to the proper location of the error.

**Comment by ejgutierrez74** [comment]
Can i expect some new release with this fix near soon ?... Because in my institute we have a strict policy of manage software( students dont have admin permissions).. so one teacher have to install the software and extensions...
Would be nice that also the file detection was fixed.....just for asking i dont loose anything ;)

Thanks for your effort and work
