### ISSUE TITLE
Contributing XSD schemas from a different extension

### ISSUE THREAD

**Issue by unilynx** [redhat-developer/vscode-xml#952]
Is it possible to contribute XSD schemas from a different extension?  (pointing to local or remote files)

I assume there's a way to do it through the Java SPI interfaces, but it seems overkill to fire up Java just to supply a few additional XSD files

**Comment by angelozerr** [comment]
In short answer we don't provide some extension point to provide this feature.

But I know [pretext-tools](https://github.com/oscarlevin/pretext-tools) vscode extension configures the proper RelaxNG fortheir pptx files by using [`xml.fileAssociations`](https://github.com/redhat-developer/vscode-xml/blob/main/docs/Preferences.md#file-associations) [with configurationDefaults package.json](https://github.com/oscarlevin/pretext-tools/blob/e481b9d08ae3b9b4a0060d1ed0753a0d2a1c5b67/package.json#L177)

I don't know if you could use this strategy. 

If you don't want to use xml.fileAssociations you could write an XML catalog.xml and declare mapping for XSD Schema. After that I don't know if you define this XML catalog as configurationDefaults if it can retrieve your XSD coming from your vscode.

I suggest that you share your XML and XSD that you would like to manage with yoru vscode extension and we could provide a more robust solution with new participant like we did for XMLLanguageParticipants and xml.JavaExtensions (seehttps://github.com/redhat-developer/vscode-xml/blob/e08f3788bdb8669feefce4417d4d4fdd1a5d5734/schemas/package.schema.json)

**Comment by angelozerr** [comment]
Another vscode sample extension uses TypeScript to add custom XML catalogs and file associations, see https://github.com/forcedotcom/salesforcedx-vscode/blob/b2170969cfdc4c5c4454da45c00cfd8bf59db3ee/packages/salesforcedx-vscode-lwc/src/metasupport/metaSupport.ts#L47

**Comment by unilynx** [comment]
Yep, it works. XMLExtensionApi.addXMLCatalogs‎ is the one I needed. https://github.com/redhat-developer/vscode-xml/blob/184bdd95a61e82612416141c92b29c18dcdc1427/src/api/xmlExtensionApi.ts#L24 

Too bad it only takes a path and my catalog is quite dynamic, but as far as I see the path gets passed directly to the XML process  so this isn't something the extension API can offer might now
