### ISSUE TITLE
Error when booting extension

### ISSUE THREAD

**Issue by robertmoura** [redhat-developer/vscode-xml#974]
Thanks for working on this extension! Really love using it for formatting XML files.

I recently upgraded my Mac and this extension used to work but is failing on start up now. I think it may have something to do with the M1 chip? Any idea what could be causing this issue? Here's what I'm getting in the XML Support output:

```
[Error - 11:50:19] XML Support client: couldn't create connection to server.
Error: spawn Unknown system error -86
    at ChildProcess.spawn (node:internal/child_process:413:11)
    at Object.spawn (node:child_process:795:9)
    at transports (/Users/___/.vscode/extensions/redhat.vscode-xml-0.26.1-darwin-arm64/node_modules/vscode-languageclient/lib/node/main.js:424:46)
    at w.connection [as createConnection] (/Users/___/.vscode/extensions/redhat.vscode-xml-0.26.1-darwin-arm64/node_modules/vscode-languageclient/lib/common/client.js:1030:15)
    at w.start (/Users/___/.vscode/extensions/redhat.vscode-xml-0.26.1-darwin-arm64/node_modules/vscode-languageclient/lib/common/client.js:612:19)
```

**Comment by angelozerr** [comment]
@fbricon have you the same problem ?

**Comment by Estreuselito** [comment]
I second that, I have a the exact same issue as described by @robertmoura. Thank you for looking into this! I highly appreciate your effort!

**Comment by angelozerr** [comment]
@fbricon @datho7561 @rgrunber have you some idea about the problem?

**Comment by fbricon** [comment]
Tried on a MacBok Air M1 without any problem.

`spawn Unknown system error -86` might suggest a corrupt file. 

Can you try the latest vscode-xml pre-release?

**Comment by Estreuselito** [comment]
Hm, sadly that did not work. I am running a MacBook Pro M3. Here are some screenshots after switching to pre-release:

![Screenshot 2024-03-13 at 14 12 04](https://github.com/redhat-developer/vscode-xml/assets/64653141/20bfbfc4-5448-47fc-8376-8125e1252564)

After clicking on yes:

![Screenshot 2024-03-13 at 14 12 34](https://github.com/redhat-developer/vscode-xml/assets/64653141/a69291a3-9397-4566-b7b9-7f5fb8911778)

I would appreciate any help :)

**Comment by fbricon** [comment]
can you check in the Mac security settings if the binary was blocked from running?

**Comment by rgrunber** [comment]
For darwin-arm64, the binary should be `lemminx-osx-aarch_64`, and not `lemminx-osx-x86_64`

```
$ ls
redhat.vscode-xml-0.26.2024022308@darwin-arm64.vsix
$ unzip -Z1 redhat.vscode-xml-0.26.2024022308@darwin-arm64.vsix | grep server
extension/server/lemminx-osx-aarch_64
extension/server/lemminx-osx-aarch_64.sha256
extension/server/org.eclipse.lemminx-uber.jar
```

How was your vscode-xml installed ? Did you download it from somewhere, or did you install it through the VS Code Marketplace ?

**Comment by datho7561** [comment]
> For darwin-arm64, the binary should be lemminx-osx-aarch_64, and not lemminx-osx-x86_64

We haven't done a release since we merged the change to build the binary for ARM macOS.

**Comment by robertmoura** [comment]
I got the same issue as @Estreuselito when installing the pre-release.

> can you check in the Mac security settings if the binary was blocked from running?
Hmm, not exactly sure how to check that but in the Privacy & Security section of the System Settings I can't see anything out of the ordinary. Was there something specific that you were looking for?

> How was your vscode-xml installed ?
Just via the VS Code Marketplace. Nothing out of the ordinary that I know of.

**Comment by rgrunber** [comment]
https://github.com/redhat-developer/vscode-xml/blob/4549a379a1c539efa37b3db4b1676ff0bf6f69f8/src/server/binary/binaryServerStarter.ts#L216-L218

:neutral_face: thanks @datho7561 for reminding about this. I'll propose a fix.

As a workaround, could anyone with the issue try :

1. Going into `/Users/.../vscode/extensions/redhat.vscode-xml-0.26.20204022308-darwin-arm64/server/`.
2. Confirm there is a file there named `lemminx-osx-aarch_64`, and rename it to `lemminx-osx-x86_64`.
3. Start VS Code and see whether the XML functionality works through the binary. You will likely have to click "Yes" to trust the binary on the prompt, when it comes up.

**Comment by robertmoura** [comment]
@rgrunber Thanks for looking into this issue! When going to that folder I already had that file. On the pre-release version I had both files in that folder so I'm not sure what to do in this case. Did you have any ideas?

<img width="283" alt="Screenshot 2024-03-15 at 3 36 26 PM" src="https://github.com/redhat-developer/vscode-xml/assets/17804984/eef6d73b-4224-44d5-b159-2b9bec0244e0">

Pre release version:

<img width="264" alt="Screenshot 2024-03-15 at 3 30 13 PM" src="https://github.com/redhat-developer/vscode-xml/assets/17804984/8072a345-fe21-4d35-8c0d-9846edad523c">

**Comment by rgrunber** [comment]
The first screenshot makes sense. Looks like it's of the 0.26.1 release, which did package the x86_64 LemMinX binary for macos-arm64 (relying on Rosetta layer to work).

As for the pre-release, I think I found yet another (similar) issue : 
https://github.com/redhat-developer/vscode-xml/blob/4549a379a1c539efa37b3db4b1676ff0bf6f69f8/package.json#L27-L31

In the event a binary can't be found locally, we download based on that logic. My guess is if the "aarch_64" (macos-arm64) binary failed to be located (because it was wrongly looking for the x76_64 one), the extension tried to download a pre-release version.. of the wrong version.

I'll need to update this part of the build. @robertmoura , if you're able to do so the following would help :

1. call `file lemminx-osx-aarch_64 lemminx-osx-x86_64` and confirrm the output looks something like :

```
$ file lemminx-osx-aarch_64 lemminx-osx-x86_64
lemminx-osx-aarch_64: Mach-O 64-bit arm64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
lemminx-osx-x86_64:   Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE>
```

Specifically, the aarch64 one should say something about arm64 and the x86_64 one should say something about x86_64.

2. Just replace the aarch64 file with the x86_64 file

`$ mv lemminx-osx-aarch_64 lemminx-osx-x86_64`

This should just allow the extension to use the wrong file path, which now has the correct binary.

3. Now start VS Code and see how the XML functionality works. You'll likely have a prompt asking to trust the binary.

Hopefully that works and confirms all the changes we need to make to fix things.

**Comment by robertmoura** [comment]
I've run that and got the following which matches what you've said.

```
lemminx-osx-aarch_64: Mach-O 64-bit executable arm64
lemminx-osx-x86_64:   Mach-O 64-bit executable x86_64
```

After running step 2 and restarting VSCode the extension seems to work as intended! I believe you may have hit this one on the head! Thanks heaps @rgrunber for being on top of this one! Really appreciate it 😊

**Comment by rgrunber** [comment]
The next pre-release (20240318.. in a few hours from now), should have the necessary fix.

**Comment by kasthack** [comment]
@rgrunber I've got a similar issue but on Windows:

ESET antivirus detects the last version as a trojan:

> `C:\Users\<redacted>\.vscode-insiders\extensions\redhat.vscode-xml-0.26.2024031317-win32-x64\server\lemminx-win32.exe - ESET LiveGuard trojan - retained`

![AV screenshot](https://github.com/redhat-developer/vscode-xml/assets/1292818/5b32c231-f2de-4f72-add8-bb740779e47a)


Extension version:  `v0.26.2024031808`

VS Code version info:
```
Version: 1.88.0-insider (user setup)
Commit: 99a19815253d91900be5ec1016e0ecc7cc9a6950
Date: 2024-03-14T05:49:42.201Z (4 days ago)
Electron: 28.2.6
ElectronBuildId: 27476517
Chromium: 120.0.6099.291
Node.js: 18.18.2
V8: 12.0.267.19-electron.0
OS: Windows_NT x64 10.0.22621
```

Windows version:

```
Edition	Windows 11 Pro
Version	22H2
Installed on	‎10/‎13/‎2023
OS build	22621.3296
Experience	Windows Feature Experience Pack 1000.22687.1000.0
```

ESET version:

```
ESET Endpoint Security, Version 11.0.2044.0
```

**Comment by datho7561** [comment]
@kasthack The bug reported in this issue was specific to apple on ARM64 and is resolved, could you please open a new issue for this bug?

**Comment by kasthack** [comment]
@datho7561 #979
