### ISSUE TITLE
Alpine support

### ISSUE THREAD

**Issue by cirolosapio** [redhat-developer/vscode-xml#986]
as [eclipse/lemminx](https://github.com/eclipse/lemminx?tab=readme-ov-file#generating-a-native-binary) readme says: 

> On Linux, compile with ./mvnw clean package -Dnative -DskipTests -Dgraalvm.static=--static in order to support distributions that don't use glibc, such as Alpine Linux

is it possible to add an alpine build with the `-Dgraalvm.static=--static` ?

**Comment by cirolosapio** [comment]
is there a released version of the vscode extension that use the compiled lemminx with that property?

**Comment by fbricon** [comment]
No there is not. We can't release 2 linux versions to the marketplace. 
Ideally, the binary would be generated and stored as a release artifact in this repo, but our team is stretched too thin at the moment so we can't commit to address this issue anytime soon.

**Comment by rgrunber** [comment]
At first we had the static flag to support https://github.com/redhat-developer/vscode-xml/issues/457 . Then we realized in https://github.com/redhat-developer/vscode-xml/issues/597#issuecomment-930343104 that the flag broke for all other linux distros.

However, I just had a look at my old comment at https://github.com/redhat-developer/vscode-xml/issues/597#issuecomment-952988946 . VS Code does support `alpine-x64`. If all that's needed is a a static glibc, and if we can just use a GH Actions Ubuntu runner that simply has the static flag enabled, I think it could work.

But yeah, it adds yet another part to the build+release process.

**Comment by cirolosapio** [comment]
something like this #989 ?

**Comment by fbricon** [comment]
Alpine extension is now available in the VS Code Marketplace

<img width="1240" alt="Screenshot 2024-04-24 at 12 48 59" src="https://github.com/redhat-developer/vscode-xml/assets/148698/4d108bf3-ff71-4571-9d3b-4acc30c5e4e4">

As well as https://github.com/redhat-developer/vscode-xml/releases/tag/latest
